### ISSUE TITLE
Zoro server isnt working

### ISSUE THREAD

**Issue by ITADORI-15** [saikou-app/saikou#1]
![Screenshot_20220215-204357_Saikou.jpg](https://user-images.githubusercontent.com/83289685/154091123-d0a0487a-9652-471f-a99c-0399aca06335.jpg)

**Comment by Jeb0978** [comment]
@ITADORI-15  Zoro is currently broken and this was mentioned somewhere earlier, Use others Until fixed and probably join discord to be updated with the community.

**Comment by ITADORI-15** [comment]
Sure thanks
