### ISSUE TITLE
I Have Suggestions 

### ISSUE THREAD

**Issue by Maryjane726** [saikou-app/saikou#10]
![ce40ee4dc20e1bb2c460c422ceff1dec](https://user-images.githubusercontent.com/99521093/155429398-b507e733-6845-4ade-9a9b-0649fe6d9123.jpg)
![f8b9f912881caac3800e66c635f60491](https://user-images.githubusercontent.com/99521093/155429406-84774cab-2ca5-425d-9e41-4492c4ca03d7.jpg)

Something like this ^^
![Picsart_22-02-23_20-45-15-800](https://user-images.githubusercontent.com/99521093/155429456-39dde3a7-bd60-421d-8298-95615dc97b2a.jpg)

**Comment by SamarthMehta** [comment]
But dark theme

**Comment by Shahilmshah06** [comment]
Which sites are this screenshots frome

**Comment by M4RiU3** [comment]
eyow the ui looks clean, what app is that?

**Comment by ITADORI-15** [comment]
It's not an app....its just a ui design from dribbble if I am ot wrong
