### ISSUE TITLE
Small Font and Display

### ISSUE THREAD

**Issue by MrConqueror** [saikou-app/saikou#102]
![Screenshot_2022-04-05-21-45-30-875_ani saikou](https://user-images.githubusercontent.com/102837820/161986195-414d7c4b-0395-48d5-b94c-ec2acf558b97.jpg)
Can we have this as a Default? This is smaller settings we got.

**Comment by brahmkshatriya** [comment]
The app was made on Display Size set to small, so I somehow made everything large for everybody else
I cant really find a way to set everything on the app small, without changing everything on the app.

So for now it will stay the current size, & when I work on reworking the app from scratch again, I'll keep it small

**Comment by brahmkshatriya** [comment]
as of now? no, If I find a way to do it in future? yes.
