### ISSUE TITLE
Download button for Episodes with auto select server

### ISSUE THREAD

**Issue by Zeroo097** [saikou-app/saikou#103]
Can u add a download option at the extreme right side of the episode number because if i set vidstream as a default server the episode plays automatically and i don't have any other option to download.

**Comment by brahmkshatriya** [comment]
Hmm that could be useful, 🤔

**Comment by brahmkshatriya** [comment]
But Idk, it would be really werid to implement, I think it would be better if #15 was to implemented

**Comment by Zeroo097** [comment]
Yeah i think that will be much much more good

**Comment by brahmkshatriya** [comment]
I'll close the issue ig, would be best suited for #15
