### ISSUE TITLE
Request :)

### ISSUE THREAD

**Issue by Pebrd** [saikou-app/saikou#104]
Heyy, I've some ideas that would be amazing to add: 
  Introduce sources in spanish as animeflv or animefenix and if it's possible upload the app on f-Droid for easier updating. 
  Thanks for the effort, the app looks amazing.

:)

**Comment by brahmkshatriya** [comment]
use [Saikou SP](https://github.com/Diegopyl1209/saikouSP)

the app will be on fdroid, after mangareader update

**Comment by Pebrd** [comment]
Thanks:)
