### ISSUE TITLE
Myanimelist integration 

### ISSUE THREAD

**Issue by RyanNL1994** [saikou-app/saikou#105]
Are there any chances of getting a myanimelist integration besides aniilist in the future?

**Comment by brahmkshatriya** [comment]
Not in this version, but I am planning to rework the whole app, after I am done with this version

There is no ETA for it

**Comment by EstebanOD** [comment]
Sorry for the notification, I'd like to add this is a surprisingly well made app, the UI is fantastic and the integration of AniList + multiple streaming sources for both anime and manga makes this app incredibly practical. However it is unfortunate it works only for AniList and not MAL, but I understand the reasons why, hope one day it'll be possible tho!
