### ISSUE TITLE
Floating screen (if needed)

### ISSUE THREAD

**Issue by DrakeWillXML** [saikou-app/saikou#106]
Hi, i just wondering if a floating screen is coming, it can be helpful or no, just wishing for it to come 

Idk how to label this as enhancement

**Comment by brahmkshatriya** [comment]
@AsfandToor uh yeah i kinda fucked it up thinking it
would disallow sending me crashlogs on other people's forks
 But for now use this https://github.com/saikou-app/saikou/blob/6cca6a613052ce0f549e5382ec2b1b245f7f577f/app/google-services.json
