### ISSUE TITLE
Extension and questions

### ISSUE THREAD

**Issue by bobamos1** [saikou-app/saikou#109]
Hi, first thanks for the amazing app, take your time but please don't give up.
First, i have a small issue, it's that sometime when i open the app, it dosen't always login to my account, by restarting it it works fine but if you find an easy way to fix it it would be nice, if not, it's not the end of the world
It would be nice to have the mangalife extension for the mangas and i saw that you hat intention to make a swipe left to right and right to left navigation, but can you add a vertical page bya page too?
I also wonder if you have any intention to add extension to have acces to us show like avatar or castlevania?
Finnaly, I wonder the same about if you can add extension like readcomiconline to have comics plus mangas?
Ps. Is there a better place to put suggestions than by reporting an issue?
Thanks in advance

**Comment by KillerDogeEmpire** [comment]
Here is a better place to suggest. It's their discord server.
https://discord.gg/PyWD46n8eD

**Comment by brahmkshatriya** [comment]
Mangalife = mangasee
