### ISSUE TITLE
Support Comick.fun

### ISSUE THREAD

**Issue by meotimdihia** [saikou-app/saikou#110]
Hi, I think you should support https://comick.fun 😀
Since the site has API docs, it is easy to integrate into the app: https://api.comick.fun/docs
Comick library included Mangadex, Mangasee, and most other popular translation groups.
I am a Comic developer. I'll support you to integrate this.

**Comment by brahmkshatriya** [comment]
Hey thanks for the suggestion, if possible, join the discord server, and i can guide you, how you can add it into the app
