### ISSUE TITLE
Multiple language

### ISSUE THREAD

**Issue by ArtanisInc** [saikou-app/saikou#113]
Hello can you add the possibility of choosing multiple language for the mangas and animes like tachiyomi app

**Comment by brahmkshatriya** [comment]
It looks like you did not read the Readme.md

It clearly states
![image](https://user-images.githubusercontent.com/69040506/162569227-e5043840-afed-48b8-9b93-34980058649e.png)

I do not plan to add any other sources except for English in this version of the app, More language support will be added when I rewrite the app to be extension based.

till then you can look at other languages fork -

Spanish : https://github.com/Diegopyl1209/saikouSP
