### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by SamarthMehta** [saikou-app/saikou#115]
yugen.to ??

**Comment by brahmkshatriya** [comment]
It's a gogo & vrv scraper

For vrv, we gonna add allanime

**Comment by SamarthMehta** [comment]
Sure sir 🐐

**Comment by SamarthMehta** [comment]
Wait wait allanime also does have anime and music as well soooo??? Like will it be available? Or just for anime source

**Comment by brahmkshatriya** [comment]
Nah only anime & possible manga too

**Comment by SamarthMehta** [comment]
Sure sar

**Comment by rollingmoai** [comment]
Can you reconsider this? Animixplay is shutdown now, and we need another alternative for it.
