### ISSUE TITLE
Bug in Popular Anime Tab

### ISSUE THREAD

**Issue by dude-shah** [saikou-app/saikou#117]
This bug is quite annoying the list just repeat itself rather than showing new more anime.

https://user-images.githubusercontent.com/63038690/162597931-80610c04-2f26-482a-80b1-b188098ba4d0.mp4

I'm using latest version of app 1.1.4
Android 11.

**Comment by brahmkshatriya** [comment]
I can not reproduce the bug, is there something specific you did?

**Comment by dude-shah** [comment]
No just scrolling casually ...

**Comment by brahmkshatriya** [comment]
Welp, i can't seem to reproduce it on my end, please confirm that it still happens after a restart

**Comment by dude-shah** [comment]
Try scrolling for a Long time or stop for some time between scrolling ... 
Idk it's happening again and again on my end

**Comment by brahmkshatriya** [comment]
I asked beta testers about the bug, no one was able to reproduce it.
Perhaps try clearing cache and if that doesn't work try clearing app data, And if that doesn't work I don't i think i can fix it, without being able to reproduce the bug

**Comment by dude-shah** [comment]
> I asked beta testers about the bug, no one was able to reproduce it.
> Perhaps try clearing cache and if that doesn't work try clearing app data, And if that doesn't work I don't i think i can fix it, without being able to reproduce the bug

Will clearing app data etc. remove all my lists like planning, favorite anime etc

**Comment by dude-shah** [comment]
> > > I asked beta testers about the bug, no one was able to reproduce it.
> > > Perhaps try clearing cache and if that doesn't work try clearing app data, And if that doesn't work I don't i think i can fix it, without being able to reproduce the bug
> > 
> > Will clearing app data etc. remove all my lists like planning, favorite anime etc
> 
> It won't.
I did clear the app data, it was taking near 400mb of storage

Scroll down... After a long time did the same thing List start to repeat itself

**Comment by brahmkshatriya** [comment]
Can you provide a video of it not the bug not happening and then "starts happening after a long time"

**Comment by dude-shah** [comment]
> Can you provide a video of the bug not happening and then "starts happening after a long time"

Yeah about that ... I was submitting a full video when i opened this issue but   it was too long and size was over 100MB ... **Github size restrictions** ... So i had to make a small video for that under 10MB for the issue.

**Comment by brahmkshatriya** [comment]
Send the 10mb vid

**Comment by dude-shah** [comment]
> Send the 10mb vid

It's above mentioned in issue .. that's the one with 10mb size

**Comment by brahmkshatriya** [comment]
Couldn't be reproduced by anyone, so closing the issue
