### ISSUE TITLE
Please Remove trackers in app

### ISSUE THREAD

**Issue by JustaUser00** [saikou-app/saikou#119]
Please remove trackers in app or add option to disable the tracker . Dub anime shows are not showing in recently updated tab

**Comment by brahmkshatriya** [comment]
What do you mean trackers

**Comment by JustaUser00** [comment]
![saikou](https://user-images.githubusercontent.com/103359654/162612867-336642e5-b855-40e3-b60f-c862de886655.jpg)

**Comment by JustaUser00** [comment]
> What do you mean trackers

![saikou](https://user-images.githubusercontent.com/103359654/162613222-a468e8dc-f034-4000-805f-cf649c1f22a2.jpg)

**Comment by brahmkshatriya** [comment]
Firebase is added for sending crash reports, So I can improve crashes which are unable go noticed & I wont be removing it until final release.
Simply do not use the app if you are that paranoid
Or learn programming & remove it yourself.
