### ISSUE TITLE
ho is stupid enough to use Android in 2022 when Apple sounds is crushing the pc crap and so much simpler no ofence tho u doing good cheer

### ISSUE THREAD

**Issue by Vilseifittan** [saikou-app/saikou#120]

**Comment by brahmkshatriya** [comment]
what

**Comment by knightmob** [comment]
Um Android is worldwide, mostly Americans only use Iphones now try to discover the world sometimes

**Comment by Vilseifittan** [comment]
- - [ ] all live performances with stil good ears after almost 25 years in the rave scene use apple 4 a reason daang pc is shit and have alway been![image](https://user-images.githubusercontent.com/103186186/162620459-f942f4a3-4094-407c-a7b7-ad144b0ef178.jpeg)

**Comment by brahmkshatriya** [comment]
such a shitpost
