### ISSUE TITLE
Add custom DL location 

### ISSUE THREAD

**Issue by jooomoooj** [saikou-app/saikou#124]
There should be no download button in settings it confuses me at first run. It should have custom dl location so that users could freely choose whether to  put in sdcard or externalsd for both anime and manga. If its hard i respect that dont waste time for this. 

Oh one more thing can manga4life.com be added in source or if its possible to have extensions like tachhi thanks iin advance.

**Comment by brahmkshatriya** [comment]
Mangasee = Manga4life

**Comment by jooomoooj** [comment]
> Mangasee = Manga4life

Didnt realized it was same hehe
