### ISSUE TITLE
bottom navbar padding issue

### ISSUE THREAD

**Issue by subby2006** [saikou-app/saikou#125]
Bottom navbar appears too large and has a gap between the navigation buttons since version 1.1.3.
Device: Samsung Galaxy S10
Android: 12 API 31
![Screenshot_20220412-081426_Saikou](https://user-images.githubusercontent.com/65925208/162972647-a215ad55-a4b8-4810-bb77-fa766271bde8.jpg)
![Screenshot_20220412-081441_Saikou](https://user-images.githubusercontent.com/65925208/162972658-38d609fa-a24d-4121-837b-3962213b896c.jpg)

**Comment by brahmkshatriya** [comment]
Will be fixed in the next update, already fixed if you compile from the current source
