### ISSUE TITLE
Video Player showing error when I increased the quality 

### ISSUE THREAD

**Issue by Xms512m** [saikou-app/saikou#128]
Hello Developers of Saikou,

Recently I found a glitch/bug on the saikou app. The glitch/bug was: When I clicked on a episode it played on auto quality but when increased the quality to 720/1080p the video player showed a error and it didn't played the episode.

Regarding this issue I seek help of your team.

Regards,
![Screenshot_20220413-195622_Saikou](https://user-images.githubusercontent.com/99712565/163197924-61cf107f-1f49-4a50-84f6-15519a2afa5f.jpg)

**Comment by brahmkshatriya** [comment]
Are you selecting the right quality?
Zoro has 2 qualities, one with 30fps & one with no fps (the which fails)

Also please mention your device name & android version

If problem persists please try clearing your cache

**Comment by Xms512m** [comment]
Hello Shivam,

Thanks for your suggestions. I realised in the past I clicked on 720p with no fps but when I tried with only 720p with 30 fps it worked.

Thanks for your help, in future if I find any more issue I will update the team.
