### ISSUE TITLE
Add hanime.tv 

### ISSUE THREAD

**Issue by Adbc3949** [saikou-app/saikou#135]

**Comment by brahmkshatriya** [comment]
No, hanime doesn't seasonalize it's shows, that is 
Overflow has "8 different shows" rather than it being "one show with 8 episodes"

hence adding hanime.tv is would always show one episode at a time

**Comment by ShiSix** [comment]
> No, hanime doesn't seasonalize it's shows, that is Overflow has "8 different shows" rather than it being "one show with 8 episodes"
> 
hanime only merge shows with episodes shorter then 10 min into one episodes. overflow ep are 7-8 min long. otger show are seasonalize
