### ISSUE TITLE
1.1.6: Anime progress not showing for favourites section.

### ISSUE THREAD

**Issue by Taimoor-Tariq** [saikou-app/saikou#140]
The progress for your favourite anime is not shown when this section is enabled for the "anime" page.
![Screenshot_20220416-093135_Saikou.jpg](https://user-images.githubusercontent.com/45585081/163676925-3ea9c919-968a-43b5-9808-7c5bbe55d5cd.jpg)

**Comment by brahmkshatriya** [comment]
yea thats something bugged on anilist's side, I can't really fix it.
