### ISSUE TITLE
Rework Search

### ISSUE THREAD

**Issue by Pen-Wait** [saikou-app/saikou#146]
Would be great if you could add a way to sort by "format" by grouping tv shows together and somewhere else movies together same with OVAs and etc. I also think the placing of the list search is a little weird, it's in the search area rather than in the list area but that's not really a big deal. Great work, love the app!

**Comment by Sutslec** [comment]
same with manga and novels? 👍

**Comment by alexzerozeroone** [comment]
Would be great if you could also sort by tags (Swordplay, Kuudere, etc)
