### ISSUE TITLE
add realese order and no. of ep available in dub

### ISSUE THREAD

**Issue by ShiSix** [saikou-app/saikou#153]
![Screenshot_20220421-113937_Fennec_1](https://user-images.githubusercontent.com/101547113/164386118-01e2d662-3b02-4098-b671-69092b7a51f4.png)

![Screenshot_20220421-113856_Fennec_1](https://user-images.githubusercontent.com/101547113/164386376-53b0a465-fd85-4513-861c-baf918c979b8.png)

**Comment by brahmkshatriya** [comment]
That's not possible, since anilist doesn't provide dub ep information

**Comment by ShiSix** [comment]
what about release order

**Comment by brahmkshatriya** [comment]
I guess I'll just sort relations by release date
