### ISSUE TITLE
Option to Hide watched shows from Popular Lists

### ISSUE THREAD

**Issue by ghost** [saikou-app/saikou#158]

**Comment by MrConqueror** [comment]
@brahmkshatriya replace it with recommended it's currently placed in Homepage ATM. if Only it's possible?

**Comment by Sutslec** [comment]
maybe switch them around but still remove the watched anime from the popular list?

**Comment by MrConqueror** [comment]
> maybe switch them around but still remove the watched anime from the popular list?

Yeah i agree, recommended should be in anime page or homepage not in library or homepage
