### ISSUE TITLE
Tenshi

### ISSUE THREAD

**Issue by Shahilmshah06** [saikou-app/saikou#16]
Tenshi not working, otherwise this is one off the best apps for manga and anime, would like to see an ios compactablity and maybe desktop(like as a website)

**Comment by brahmkshatriya** [comment]
Working here!
[Ss.png](https://user-images.githubusercontent.com/69040506/155844138-008c35de-26f1-4b43-945a-00f565237ca0.png)

**Comment by brahmkshatriya** [comment]
Also, there will be no app for iOS, but we are thinking of making something like website, but we will see

**Comment by Shahilmshah06** [comment]
It's not working for aot

**Comment by brahmkshatriya** [comment]
Please provide a screen shot or video

**Comment by brahmkshatriya** [comment]
Closed due to inactivity
