### ISSUE TITLE
9anime source: dub version automatically chosen while sub is preferred

### ISSUE THREAD

**Issue by Sutslec** [saikou-app/saikou#162]
since the real 9anime has been introduced in the beta release, there are some problems with choosing the sub/dub. 

whenever you pick an anime there is a chance that the dub comes up while preferring the subs. "Shikamori's not just a cutie" is one of those.

**Comment by brahmkshatriya** [comment]
the one who reported it, meant animekisa & its search is fucked
nothing can be done bout it. tv needs wrong title button.

**Comment by Sutslec** [comment]
:thumbsup:
