### ISSUE TITLE
Add few websites.

### ISSUE THREAD

**Issue by AdriBD83** [saikou-app/saikou#166]
Well Saikou is a very awesome app for watching anime and reading manga, based on anilist.
but there are so many good websites has not included in this apps, like: Manga4life, mangareader.to, kissmanga, and for anime: animixplay.to, kissanime etc. so atleast adding manga4life and animixplay.to would be great.

**Comment by brahmkshatriya** [comment]
manga4life = mangasee
animixplay is a gogo scraper, & for vrv streams wait for AllAnime on next update.
afaik kissanime streams will be in allanime too

also mangareader in the app is mangareader.to, mf doesnt even use the app fully before making an issue smh my head

**Comment by AdriBD83** [comment]
> manga4life = mangasee animixplay is a gogo scraper, & for vrv streams wait for AllAnime on next update. afaik kissanime streams will be in allanime too
> 
> also mangareader in the app is mangareader.to, mf doesnt even use the app fully before making an issue smh my head

Sorry, my bad. I didn't understand it before.
Thanks for the reply.
