### ISSUE TITLE
Desktop version request.

### ISSUE THREAD

**Issue by AdriBD83** [saikou-app/saikou#167]
Saikou app is a very good app in sync with anilist for watching and downloading anime and manga. But if there was a desktop version of this app it would be great. Since all pcs doesn't run emulators and WSA properly, so a desktop version would be very helpful for desktop users.

**Comment by brahmkshatriya** [comment]
already in works,
https://github.com/saikou-app/saikou-api

unofficial preview : https://saikou.realyami.in/

**Comment by AdriBD83** [comment]
> already in works, https://github.com/saikou-app/saikou-api
> 
> unofficial preview : https://saikou.realyami.in/

It was helpful. Thanks for your kind information and for the reply.

**Comment by ProtoManGG** [comment]
> already in works, https://github.com/saikou-app/saikou-api
> 
> unofficial preview : https://saikou.realyami.in/

Hey Shivam,

I really don't know if this is the right platform to discuss this but here I go:

I first and foremost love the  project and have high respects for the efforts you, the team and the community who have contributed to the project.

I myself want to do so, but here is the thing I lack:
I have only knowledge about Flutter framework (Dart Lang),
Although I know concepts such as DI, Architectures, SOLID Principles.


Seeing this code I feel like I cannot do even a meagre help codewise.



Hence stretching my arms in need of help, I would really like to know could you (If not bothersome) assign me some low level tasks and tell me some rough idea around how should I proceed with the problem ( I will try to google my way out of the problem), by that means I could help the project and learn

Only if it is not much of a pain.

Also on a sidenote; if I can help by using Flutter I'm all in...so do let me know

**Comment by brahmkshatriya** [comment]
@ProtoManGG It would be best to communicate on the [discord server](https://discord.gg/saikou-app/)

Also idk what low level need help at this point

**Comment by venkat2305** [comment]
> already in works,
> https://github.com/saikou-app/saikou-api
> 
> unofficial preview : https://saikou.realyami.in/

Do desktop and the mobile versions share the same code base?

**Comment by brahmkshatriya** [comment]
No they don't yet
