### ISSUE TITLE
Quality error

### ISSUE THREAD

**Issue by Jasonsmith236** [saikou-app/saikou#17]
For each of the sources I selected 1080p which was supported on the site but when I chose 1080p in the app it works once or twice then suddenly loads and pauses and I cannot now use 1080p please fix this when you have time

**Comment by brahmkshatriya** [comment]
Can you please elaborate which anime this happened on which source & server?

**Comment by Jasonsmith236** [comment]
It happened on all that I tried and I only watched 2 anime till now which are strike the blood 1 to 4 and one piece I had to keep deleting and reinstalling it to make it work.

**Comment by JasonSmith20** [comment]
Disregard this issue it is my garbage device error the app actually works great
