### ISSUE TITLE
Support for Animixplay + Customizations

### ISSUE THREAD

**Issue by Tanay2804** [saikou-app/saikou#17]
If possible please add AnimixPlay.to(Gogo server) as it's incredibly Fast.... 

This app is Soo good but it can be even better with customizations like: view X items per row, or Change the accent colors Etc...
Looking forward for light novel support too!!! 
Thank you Soo much for this app!!!🙌🏻

**Comment by brahmkshatriya** [comment]
I am not going to add animixplay & will instead add allanime, cuz it has more server options including vrv streams

& for customization you need to wait for settings update, though there probably won't be accent color customization

**Comment by Tanay2804** [comment]
Thanks a lot man!! I really appreciate it!

**Comment by brahmkshatriya** [comment]
> Animepahe is coming as well right?

yes, please join the discord server & read the #planned channel
