### ISSUE TITLE
Auto quality selection is broken

### ISSUE THREAD

**Issue by JimZiii** [saikou-app/saikou#170]
The Auto quality selection isn't working.
If you start something in 1080p, then start another video without 1080p support, let's say it has 720p and 360p, for some reason it's always locking you to the lowest setting, so if you then start anything at all, it's all running in 360p. And they'll all keep running in 360p until you manually change the resolution to something higher.
Then we're back in the same loop. Watch a few 720p videos, come across something in 1080p, and as soon as you try watching a video without 1080p available it automatically locks you into the lowest resolution setting until it's manually changed again.

Since it's currently auto detected and changed after each video, even without this bug, there's no way to set a preferred resolution yourself, so it being visible in settings is useless.
I suggest scrapping it and adding two options instead, "preferred quality on wifi" and "preferred quality on mobile data" which lets you select the resolution you want to use on each and the app then selects that resolution or the one below it if the preferred resolution isn't available.

Other than that it's a really awesome app, just found it yesterday and i hope it stays active for a long time.

**Comment by Zeroo097** [comment]
You can set preferred quality by tapping on the your profile pic on top right and then go to settings,then player setting and set your preferred quality like this-:
![Screenshot_20220503-204426.jpg](https://user-images.githubusercontent.com/91909890/166482273-a1f823b4-5fda-4018-96b5-22d031f9bf05.jpg)

**Comment by JimZiii** [comment]
> 

If you're talking about the "auto quality selection" you're wrong. That's not how it's used and it's definitely not how it's working at the moment.
If you read the text under it you'll even see it says "auto changes upon playing a video"
Try setting it to 360p and the play a 720p video in multi quality and you'll see it'll be right back at 720p. If you then play a 1080p video and check its suddenly at 1080p instead.

I even explained how to replicate the issue

**Comment by brahmkshatriya** [comment]
> > 
> 
> If you're talking about the "auto quality selection" you're wrong. That's definitely not how it's working at the moment and I'm pretty sure it's not even it's intended use.
> If you read the text under it you'll even see it says "auto changes upon playing a video"
> Try setting it to 360p and then play a 720p video in multi quality and you'll see it'll be right back at 720p. If you then play a 1080p video and check its suddenly at 1080p instead.
> 
> I even explained how to replicate the issue

That is intentional & I don't think it's something I can fix

**Comment by JimZiii** [comment]
> > > 
> > 
> > 
> > If you're talking about the "auto quality selection" you're wrong. That's definitely not how it's working at the moment and I'm pretty sure it's not even it's intended use.
> > If you read the text under it you'll even see it says "auto changes upon playing a video"
> > Try setting it to 360p and then play a 720p video in multi quality and you'll see it'll be right back at 720p. If you then play a 1080p video and check its suddenly at 1080p instead.
> > I even explained how to replicate the issue
> 
> That is intentional & I don't think it's something I can fix

Is it intentional for it to adjust upwards to 1080p and if you then play a video without 1080p support it locks you into the lowest available resolution instead of the closest?

Also, that's why i have the suggestion of changing the system altogether to something more useful because currently it's not doing anything useful
