### ISSUE TITLE
Manga Reader Enhancements

### ISSUE THREAD

**Issue by Shahilmshah** [saikou-app/saikou#18]
Ok last comment for today,
In the manga, you can give a continue from chapter xyz, like in the anime page

**Comment by brahmkshatriya** [comment]
Planned for Manga Reader : 
- Left to right, Right to left  &  Webtoon page viewer, 
- Dual Page layout
- Manga Title & Chapter
- Page SeekBar & Page Number
- Auto Continue from where you left off on that chapter
- Goto Next/Prev Chapter
- Chapter List in reader
- Long Click will open the page in browser
- Autoload Images (before you scroll to that image)
- Auto mark as read after completing the chapter

**Comment by Shahilmshah** [comment]
Awesome
