### ISSUE TITLE
Tenshi not working

### ISSUE THREAD

**Issue by Zeroo097** [saikou-app/saikou#180]
Tenshi server are not working anymore.It just stuck at an endless loop of buffering.And sometimes while selecting quality it shows java timeout thingy

**Comment by brahmkshatriya** [comment]
I cannot replicate your issue, try to send a video, or wait for the update

**Comment by brahmkshatriya** [comment]
that seems like an isp or server problem most likely,
try playing the same episode on tenshi site

If the video loads & shows the time, saikou is doing it's job as intended
anything beyond that is out of the app's control
