### ISSUE TITLE
Downloading Anime

### ISSUE THREAD

**Issue by giovanny-martinez** [saikou-app/saikou#189]
is there a way to download anime episodes from the app?

**Comment by brahmkshatriya** [comment]
Read the README.md

**Comment by giovanny-martinez** [comment]
> Read the README.md
i wanted to know how to download the episodes not if you can download episodes.

**Comment by brahmkshatriya** [comment]
![image](https://user-images.githubusercontent.com/69040506/168391580-f09f7990-cd3e-4064-b3f3-726642ee55b2.png)

only some sources support downloading
