### ISSUE TITLE
Favorite Shows on Homepage for Quick Access

### ISSUE THREAD

**Issue by ishimagi** [saikou-app/saikou#19]
Give a favorite section for app not for anilist where we can store anime or manga so we wont have to search it again

**Comment by ITADORI-15** [comment]
Dont u think what u r trying 2 ask is already present![Screenshot_20220227-185239_Saikou.jpg](https://user-images.githubusercontent.com/83289685/155884157-70966248-89ee-447f-b235-698ec0288e56.jpg)

**Comment by brahmkshatriya** [comment]
> Give a favorite section for app not for anilist where we can store anime or manga so we wont have to search it again

yea good idea, I'll just add an option to show favorited shows on home page

**Comment by ishimagi** [comment]
> Dont u think what u r trying 2 ask is already present![Screenshot_20220227-185239_Saikou.jpg](https://user-images.githubusercontent.com/83289685/155884157-70966248-89ee-447f-b235-698ec0288e56.jpg)

This is favourite for anilist or MAL im actually asking a separate favourite for app
