### ISSUE TITLE
[request]

### ISSUE THREAD

**Issue by imxcr** [saikou-app/saikou#19]
subtitles option for zoro, zoro has external subs so

**Comment by brahmkshatriya** [comment]
Subtitles are already supported in the app for Zoro, If you are using streamSB on zoro, then they won't have subs, Because the subs are not available on streamsb, So use Vidstream or  VidCloud servers

**Comment by imxcr** [comment]
> Subtitles are already supported in the app for Zoro, If you are using streamSB on zoro, then they won't have subs, Because the subs are not available on streamsb, So use Vidstream or  VidCloud servers

no i mean to edit the subs appearance?

**Comment by brahmkshatriya** [comment]
Oh my bad then, but sorry an option for editing subtitles won't be added in this version of the app, if you want to change them, please fork the repo and do it yourself.
