### ISSUE TITLE
Can you please not release any anime chapter by chapter 

### ISSUE THREAD

**Issue by Meboy123** [saikou-app/saikou#192]
Can you please not release any anime chapter by chapter  like in baruto it says that there is from 151 to 155 and episode 249 has released so why doesn't every ep get released there is about 90 episodes not showing while it is showing in 9 anime as you can see in the pictures included
![Screenshot_20220516_143005_com android chrome](https://user-images.githubusercontent.com/105642911/168583413-6e1078c2-48d5-44e8-92ba-b37c1c402944.jpg)
![Screenshot_20220516_142650_ani saikou](https://user-images.githubusercontent.com/105642911/168583420-9537b1b5-d838-4f99-8618-e908d3ab28d0.jpg)

**Comment by brahmkshatriya** [comment]
one more invalid issue & @vorobyovgabriel has to ban you from making issues

**Comment by Meboy123** [comment]
Sorry

**Comment by Meboy123** [comment]
Is it considered to be an issue that the nine anime source doesn't work like in the photo 
![Screenshot_20220516_145328_ani saikou](https://user-images.githubusercontent.com/105642911/168587138-744d7a55-1c1d-4df9-ad1b-0458f2a29b01.jpg)

**Comment by brahmkshatriya** [comment]
try clicking wrong title
