### ISSUE TITLE
Downloading to SD-Card & viewing Downloads not working.

### ISSUE THREAD

**Issue by saintly2k** [saikou-app/saikou#194]
Hey there!

I've been on the search for an Anime app since I won't be able to access my computer anymore for some time and stumbled upon this... and it's great! Thanks for your hard work~

So the problem is, if I set `Download in SD card` to true, then download an Episode and then click `Downloads` to view them, it gives me the Error: `Couldn't find any File Manager to open SD card`. I thought this may could be because it has missing permissions so I granted Saikou access to my storage, however I couldn't allow manually access to SD-Card, so if that's it, how can I solve it?

After searching for a possible solution in other issues, I found one that was closed some time ago due to inactivity, and that's why I'm opening a new. I hope that's fine~

I use Android 10 (latest update) and the latest version of the App, as well as a 64gb SD-Card. If you need any more details, just ask! I will answer as fast as I can (and when school allows me to).

It would be great if anybody could take their time to help me out ^-^

Best regards!

**Comment by brahmkshatriya** [comment]
Download solid explorer (available on playstore), or any explorer which allows 3rd party apps to open a folder
