### ISSUE TITLE
Streaming bug.. Whenever i try to play it shows this error

### ISSUE THREAD

**Issue by Hanzixt** [saikou-app/saikou#20]
![Screenshot_2022-02-27-18-40-46-13_f4add486f0ca06883ca4fa789e77e31e](https://user-images.githubusercontent.com/85128094/155884815-a093a6ab-a877-472e-802f-eff53b67a574.jpg)

**Comment by brahmkshatriya** [comment]
Will be fixed in the next update, Please use a different source for now

**Comment by seekwoo** [comment]
I downloaded the new version 1.0.10.8 couple hours ago in anime streaming Gogo server not working, seems to be crushed again.

![Screenshot_2022-03-03-12-48-27-096_ani saikou](https://user-images.githubusercontent.com/100714133/156512289-e37260e3-5287-4c36-8622-1418016e142c.jpg)

**Comment by Ghost5555K** [comment]
Same problem

**Comment by ErrorErrorError** [comment]
Gogoanime has some issues retrieving server info. The developer needs to replace `gogohd.pro` with `gogohd.net`

**Comment by SenpaiMax-hiro** [comment]
Gogo server error
