### ISSUE TITLE
Zoro is not working 

### ISSUE THREAD

**Issue by Kasvab** [saikou-app/saikou#200]
Hello , I donot know why but the extension for zoro is not working  since I think 5- 6 hours here is msg that keeps coming . I am able to see all the titles when I click wrong title button ( see screen shot ) which I think this problem is not related to DNS which happen often in zoro  . Is there mistake from my side or there is a bug relate to server or something  ( I think may be) 

![Screenshot_20220523-141801_Saikou](https://user-images.githubusercontent.com/102959370/169781665-9937b3b8-0ee8-4038-9839-80175ccfb0dc.jpg)
![Screenshot_20220523-141809_Saikou](https://user-images.githubusercontent.com/102959370/169781738-e7f3344c-3313-4b86-a5c3-63f953ad77fa.jpg)

Thank you

**Comment by brahmkshatriya** [comment]
Wait for update
