### ISSUE TITLE
Add New pt-BR (Português do Brasil) Sources

### ISSUE THREAD

**Issue by RickyM7** [saikou-app/saikou#201]
If possible, can you add this sources to this app?
- Goyabu: https://goyabu.vip/
- AnimesZone: https://animeszone.net/

Thank you so much for this amazing app!

**Comment by brahmkshatriya** [comment]
![image](https://user-images.githubusercontent.com/69040506/169846453-8d121c92-684f-4012-bd69-6553032c358d.png)

**Comment by brahmkshatriya** [comment]
Also wait for update, as kamyroll might give you option to watch Português dub
