### ISSUE TITLE
Kamyroll

### ISSUE THREAD

**Issue by venkat2305** [saikou-app/saikou#207]
![Screenshot_2022-05-27-15-56-43-74_f4add486f0ca06883ca4fa789e77e31e.jpg](https://user-images.githubusercontent.com/55329452/170682468-c2345108-8f8e-4552-a56a-df441946b21d.jpg)

Dub is not present in the list for black clover. This is because, crunchyroll has two separate titles one with the sub and the other with dub.
![Screenshot_2022-05-27-15-57-57-12_c27f02666d83ff042cca5b16d12834f5.jpg](https://user-images.githubusercontent.com/55329452/170682695-54bbdd07-f07a-4ab1-9df0-951a93332664.jpg)

Can you do something about this?

Also , the dub title cannot be found in the wrong title menu.

**Comment by brahmkshatriya** [comment]
Report this to kamyroll's end point, not here
