### ISSUE TITLE
9anime servers issue 

### ISSUE THREAD

**Issue by AEStudios** [saikou-app/saikou#209]
I don't know why I'm receiving this error while using 9anime and the servers don't show up.

Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title></title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<base href="/">
<link href="/assets/mcloud/favicon.png" type="image/x-icon" rel="shortcut icon">

<link rel="stylesheet" href="/assets/mcloud/cache/styles.css?v=1653669301">

</head>
<body>
<script>window.postMessage('player.error', '*');</script>

    <div style="text-align:center">
        <div class="[truncated 537 chars]; line: 1, column: 2]

**Comment by brahmkshatriya** [comment]
What version are you on?

**Comment by AEStudios** [comment]
I am on the latest version (1.2.0.10)

**Comment by brahmkshatriya** [comment]
I am unable to reproduce it

**Comment by AEStudios** [comment]
https://files.catbox.moe/85wnq1.mp4

Here, I'm getting the same issue on both my tablet and mobile device. Only Steamtape loads, and sometimes even it doesn't load. This happening on every anime and episode

**Comment by Kasvab** [comment]
Yes I am also facing same issue on latest version 


Error msg-----

Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title></title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<base href="/">
<link href="/assets/mcloud/favicon.png" type="image/x-icon" rel="shortcut icon">



<link rel="stylesheet" href="/assets/mcloud/cache/styles.css?v=1653674409">


</head>
<body>
<script>window.postMessage('player.error', '*');</script>

    <div style="text-align:center">
        <div class="[truncated 537 chars]; line: 1, column: 2]
