### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Subbarao6338** [saikou-app/saikou#21]
Please add anime sources
Kiss-cartoon
Watchcartoononline

**Comment by brahmkshatriya** [comment]
send links

**Comment by Subbarao6338** [comment]
https://kisscartoon.city/
https://www3.kiss-cartoon.tv/

**Comment by brahmkshatriya** [comment]
Won't be added, they are not anime only.

**Comment by Subbarao6338** [comment]
These contains English cartoons, animated series, shows like Ben 10, power rangers, monsuno etc.
And English animated movies.

**Comment by brahmkshatriya** [comment]
yea those arent available on anilist, so no point in adding them in saikou
