### ISSUE TITLE
9anime and all anime isn't working 

### ISSUE THREAD

**Issue by Asker101pls** [saikou-app/saikou#215]
The last update the version 1.2.0.10 was great cause I can stream in 9anime without errors in servers and the same as in allanime but this update version 1.2.0.11 won't play any 9anime anime and couldn't find any sources in allanime.

**Comment by Kasvab** [comment]
Yup !!! Same issue with 9 anime again
And in all anime no source is coming( like we have to continuously tap on dub and sub button in all anime for any anime to come)

**Comment by Kasvab** [comment]
And zoro is also not working there is no source for it too
Error msg------
![Screenshot_20220528-073731_Saikou](https://user-images.githubusercontent.com/102959370/170805602-09fd55b8-92ff-456e-a1e7-a7d1a15cc403.jpg)
![Screenshot_20220528-073722_Saikou](https://user-images.githubusercontent.com/102959370/170805605-3d38ee54-a4c3-47b7-8686-fe02f15c4ac7.jpg)

Error msg from zoro ------ 


Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style>
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue""[truncated 9912 chars]; line: 1, column: 2]
