### ISSUE TITLE
NEVER ENDING LOADING

### ISSUE THREAD

**Issue by sting07** [saikou-app/saikou#22]
without VPN connection  this app doesn't work properly..i dunno what the hell wrong with this loading things.my internet works well tho but its still go loading and loading until connect with vpn..but when i connected with vpn this app running like butter. so, my humble request is please fix this issue asap.thank you.

**Comment by ITADORI-15** [comment]
Bro which country r u from?

**Comment by Blatzar** [comment]
In Australia and India some piracy sites are blocked, you're likely experiencing that. 
Might be possible to solve by going to phone settings and enabling a private DNS (Google it).

**Comment by brahmkshatriya** [comment]
Fixed in the latest commit, please wait for the update
