### ISSUE TITLE
add more video servers in 9anime like before 

### ISSUE THREAD

**Issue by Asker101pls** [saikou-app/saikou#224]
The latest update is great but still hoping to add more video servers in 9anime like the servers before videovard isn't that good and zoro vidstreaming sub is not working.

**Comment by Kasvab** [comment]
Try using adguard as your dns in setting of app . 
I resolved my issue in zoro 

In 9 anime vidstream isn't available may be due to keys but I recommend using adgaurd ( by using it I get vidstream for something and sometimes it get broken)

> The latest update is great but still hoping to add more video servers in 9anime like the servers before videovard isn't that good and zoro vidstreaming sub is not working.

**Comment by Kasvab** [comment]
Yes pls look into this I am too facing this issue
