### ISSUE TITLE
Request sources

### ISSUE THREAD

**Issue by AhmedShiryu34** [saikou-app/saikou#231]
Request to add Arabic Sources like anime4up

**Comment by brahmkshatriya** [comment]
mf doesnt read the readme

**Comment by AhmedShiryu34** [comment]
Option to add subtitles at least ? Is that possible ?

**Comment by brahmkshatriya** [comment]
it is possible, 
will I do it? no
would someone else does it & prs it? yes

**Comment by AhmedShiryu34** [comment]
There is an app called cloudstream They already have this feature
