### ISSUE TITLE
Slow loading home rab

### ISSUE THREAD

**Issue by Light7654** [saikou-app/saikou#233]
It's taking alot of time to load as compared to before 

https://user-images.githubusercontent.com/87866912/171815701-adfea974-366d-4c77-9e46-31d3304d5c26.mp4

**Comment by brahmkshatriya** [comment]
Now show the time of old version

**Comment by Light7654** [comment]
This is version - 1.1.6

https://user-images.githubusercontent.com/87866912/171842862-b364c662-5428-40e4-90f1-80f4d6b84b54.mp4
