### ISSUE TITLE
Manga page cropping

### ISSUE THREAD

**Issue by lewdpatriot** [saikou-app/saikou#239]
Automatically cropping manga page white borders will be super helpful. 
Before: 
![Screenshot_2022-06-06-07-38-19-11_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/63286528/172083215-91b38660-695d-42db-aadf-3c719c122b97.jpg)
After:
![Screenshot_2022-06-06-07-38-36-16_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/63286528/172083240-527272e8-8845-4a78-9fa8-3e05add7c266.jpg)

**Comment by lewdpatriot** [comment]
Can you kindly give a reason why you won't implement it? It is quite important to me as I have a smaller phone and am quite certain will be beneficial for others as well. If it is too much work for now then please consider it for future.

**Comment by brahmkshatriya** [comment]
The problem, is Idk how I can implement it correctly, and I don't think it's worth wasting my time for such a small feature

If anybody else wants to add it, i don't mind it

**Comment by lewdpatriot** [comment]
> The problem, is Idk how I can implement it correctly, and I don't think it's worth wasting my time for such a small feature
> 
> If anybody else wants to add it, i don't mind it

Ok, I understand. Thanks for the clarification.
