### ISSUE TITLE
Feture requests..

### ISSUE THREAD

**Issue by iCeY3** [saikou-app/saikou#24]
-MAL sync
-animekisa source addition
-picture in picture for player
- autoplay next episode for player

Thanks for awesome app

**Comment by brahmkshatriya** [comment]
-MAL sync
will not be added in the current version of the app, I am planning to rewrite the structure of the app & I am considering adding mal with it.

-animekisa source addition
idk which animekisa you are talking bout, If it's .tv then the website gives error 1020 for most of the users, & isnt much usable
if you are talking bout .in, then it already added

-picture in picture for player
planned for the rewrite of the app.

**Comment by iCeY3** [comment]
Thanks for the reply
