### ISSUE TITLE
Showing same anime two times

### ISSUE THREAD

**Issue by srkrmogno55** [saikou-app/saikou#242]
### Summary

When I searched domestic girlfriend anime and a few other anime I saw two anime titles but with same name and info

### Reproduction Steps

*

### Expected Result

*

### Actual Result

*

### Device Information

Device-
Samsung Galaxy Tab A
Android Version 11
Saikou Version 1.2.0.14

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Image/Screenshot- [https://bg-so-1.zippyimage.com/2022/06/07/bb4c455a4b7a12ff9a072abcb9f30f72.jpg](url)

**Comment by brahmkshatriya** [comment]
Duplicate because of #146
