### ISSUE TITLE
Missing Anime titles

### ISSUE THREAD

**Issue by srkrmogno55** [saikou-app/saikou#243]
### Summary

When I wanted to watch some anime I found it was missing. Is this bug/glitch? Or done purposely?

### Reproduction Steps

'

### Expected Result

'

### Actual Result

'

### Device Information

Device-
Samsung Galaxy Tab A
Android Version 11
Saikou Version 1.2.0.14

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Screenshot- [https://bg-so-1.zippyimage.com/2022/06/07/eb8152c983f35fbc0908baf99c4b52be.jpg](url)

**Comment by scrazzz** [comment]
It's an adult anime. 18+ contents are not shown unless you login with Anilist.

Login using Anilist and enable "18+ content" in Anilist settings (https://anilist.co/settings/media).

![piss](https://user-images.githubusercontent.com/70033559/172375921-c392ea1d-54e5-4b3a-95af-fa0c8fdd5e55.jpg)
