### ISSUE TITLE
Connection error In servers 

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#245]
### Summary

Slow Server findings and Connection error

### Reproduction Steps

I'm just gonna watch anime on the newest update  and when Im about to click on a episode it's says connection error and many corresponding words 
And when I watch an anime when I try to change multi quality server it just stop and say connection error I have a fast Wi-Fi so I don't expect that to happen.
![Screenshot_20220607_230819](https://user-images.githubusercontent.com/107057902/172415564-ffed43cd-ab98-4759-8118-b53ad7287382.jpg)

### Expected Result

Please fix the error and the slow searching of Multiple quality of Servers if an update can happen please approve my request.

### Actual Result

Having Connection error finding multi quality on a server and slow loading

### Device Information

Vivo1606
Android 6.0.1
Saikou β/ 1.2.0.14

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Please fix some opening issue about Job was cancelled 
![Screenshot_20220607_230326](https://user-images.githubusercontent.com/107057902/172414486-a09a55af-2e52-499f-b171-45b734461663.jpg)

**Comment by brahmkshatriya** [comment]
It really seems like a device specific error, 
best thing you can do is use VPN & hope it gets fixed
Because I am unable to reproduce this
