### ISSUE TITLE
Zoro giving source exception error

### ISSUE THREAD

**Issue by srkrmogno55** [saikou-app/saikou#246]
### Summary

When I started to watch I suddenly got source exception errors from zoro

### Reproduction Steps

*

### Expected Result

Please fix this issue

### Actual Result

*

### Device Information

Samsung Galaxy Tab A
Android Version 11
Saikou Beta 1.2.0.14

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![This is an image](https://bg-so-1.zippyimage.com/2022/06/07/5df026a51d460c5e1ac9a532951e0376.jpg)

**Comment by Shemar890** [comment]
Need to fix

**Comment by brahmkshatriya** [comment]
Fill all the fields.
