### ISSUE TITLE
Episode names are not showed correctly .

### ISSUE THREAD

**Issue by soymadip** [saikou-app/saikou#248]
### Summary

More precisely after changing anime season or after selecting correct anime when app selected wrong anime( what happens most of the times ), the episode names doesn't change . It remains just it was before.         But the content changes correctly.

### Reproduction Steps

1. Open a anime with several seasons(like Attack on Titan).
2. Then change the season by selecting it through 'Wrong Title?' button.
3. You can see that anime season or more precisely content is changed but episode names and thumbnails remains same as before (default ones selected by app at first.) .

It mostly happens with `GoGo, AllAnime , 9Anime, Tenshi` provider. I didn't noticed it frequently with `Zoro`. 

### Expected Result

Episode names should have changed according to season.

### Actual Result

It didn't changed 😑

### Device Information

`Realme Narzo 30` and I also checked with `Redmi Note 11`

### Checklist

- [x] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
> Open a anime with several seasons(like Attack on Titan).
> Then change the season by selecting it through 'Wrong Title?' button.
> You can see that anime season or more precisely content is changed but episode names and thumbnails remains same as before (default ones selected by app at first.) .

why are you changing seasons from wrong title? 🤨

**Comment by soymadip** [comment]
> > Open a anime with several seasons(like Attack on Titan).
> > Then change the season by selecting it through 'Wrong Title?' button.
> > You can see that anime season or more precisely content is changed but episode names and thumbnails remains same as before (default ones selected by app at first.) .
> 
> why are you changing seasons from wrong title? 🤨 you are supposed to goto the next season on the app, instead of doing that

I understand what you are saying. Leave about the season. 
When the app picks wrong content by default (like sometimes it fetches anime movies instead of main series) , after picking correct content, also the name doesn't change. 

And besides, it would be really too good to able to change season through one there😅. I guess then this is a feature request not a bug

**Comment by brahmkshatriya** [comment]
> after picking correct content, also the name doesn't change.
provide an example, where it is using a wrong name 🤨

> And besides, it would be really too good to able to change season through one there
Not gonna happen

**Comment by soymadip** [comment]
> > after picking correct content, also the name doesn't change.
> 
> provide an example, where it is using a wrong name 🤨
> Let me use it more, if it happens again, I will take screenshot.
> > And besides, it would be really too good to able to change season through one there
> 
> Not gonna happen
😇

**Comment by brahmkshatriya** [comment]
closed due to inactivity
