### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by aatihonora** [saikou-app/saikou#25]
A few suggestions to make the built-in player a bit more convenient 

Add brightness lock so the user won't have to set it while changing episodes. 

Adding a default video quality option. It is a real hassle to change it every time.

**Comment by SamarthMehta** [comment]
And if finished 1 episode, automatically go to the next ep , idk if its there , mine didnt work

**Comment by brahmkshatriya** [comment]
![image](https://user-images.githubusercontent.com/69040506/156151814-aaedc2e8-df15-4a52-aff3-89a2d2ad150e.png)
This button can be used to disable brightness & volume gestures.

> default video quality option.
Use ``make default`` option when selecting a server, it will automatically select the server.
& if open a Multi Quality Server, clicking on HQ button, to select your quality (The last chosen quality will be saved, it will auto select the same quality for next time.)

**Comment by aatihonora** [comment]
I didn't mean disabling the gesture but to use a set brightness for all the eps rather than going back to system brightness after selecting a new episode

**Comment by brahmkshatriya** [comment]
What do you mean? the brightness is based on your system brightness
Do you mean for an option to having a set brightness for the video player?

**Comment by aatihonora** [comment]
Kinda like what mxplayer has once you set a brightness through gesture it saves it and recalls it rather than recalling system brightness
