### ISSUE TITLE
App stops on it's own


### ISSUE THREAD

**Issue by ITADORI-15** [saikou-app/saikou#25]

**Comment by brahmkshatriya** [comment]
please provide more information, I cannot do anything with the amount of information you've provided

**Comment by ITADORI-15** [comment]
@brahmkshatriya 
https://user-images.githubusercontent.com/83289685/150791491-0132bc11-3492-405d-a677-1fbf0d191cf4.mp4

**Comment by ITADORI-15** [comment]
Bro the problem is with anilist
As soon as I login it crashes
But if I dont login it works properly
