### ISSUE TITLE
Rotating the screen causes the pages to change

### ISSUE THREAD

**Issue by ChronoStriker1** [saikou-app/saikou#256]
### Summary

Rotating the screen causes the pages to change

### Reproduction Steps

Rotate the phone

### Expected Result

Rotating the phone does not change what page you're looking at

### Actual Result

Rotating the phone causes the pages to jump sometimes all the way to the end of a chapter.

### Device Information

Samsung Galaxy s21 ultra
Android 12

Saikou 1.2.0.15

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

 I'm assuming it's due to the dual page option.

**Comment by DemonLordDiablo** [comment]
i've also had this problem and i've got dual pages turned off.
