### ISSUE TITLE
Add https://muchohentai.com as a Hentai Source.

### ISSUE THREAD

**Issue by BestRestUp3300** [saikou-app/saikou#258]
### Summary

Addding MuchoHentai as Source. It offers 1080p to almost all existing animes. 

### The Problem

The current offer for hentai is bad because the HentaiMama Quality is pretty low. HentaiStream is good but it lacks in amout of series. Coudn't test haho or hentaiff since they don't work at the moment.

### The Ideal Solution

Adding [MuchoHentai](https://muchohentai.com ) as a source will fix the problem. Since it has a huge library of 1080p Series. The are AI Upscaled if the series doesn't support 1080p.

### The Current Solution

Adding [MuchoHentai](https://muchohentai.com ) as a source for Hentai.

### Additional Context

Series are released super quickly after actual release date and it is constantly updated.

**Comment by Diegopyl1209** [comment]
It is possible to implement it but you would have to treat the chapters as different hentai or all the results as the same, because when searching for a hentai the results are from all the chapters in different formats and different languages
![Screenshot_20220612_213240](https://user-images.githubusercontent.com/80992641/173264103-a2f7cbf1-2499-402b-87b6-f458e15fa589.jpg)

**Comment by Diegopyl1209** [comment]
The short answer is no

**Comment by BestRestUp3300** [comment]
> The short answer is no

Welp. Anyways just tried haho also low quality. And HentaiFF from the looks of it, it rips the episodes from muchohentai, so it kinda actually works out.

**Comment by Diegopyl1209** [comment]
> > The short answer is no
> 
> Welp. Anyways just tried haho also low quality. And HentaiFF from the looks of it, it rips the episodes from muchohentai, so it kinda actually works out.

The problem Is the way of organice the episodes not the video.

**Comment by BestRestUp3300** [comment]
> > > The short answer is no
> > 
> > 
> > Welp. Anyways just tried haho also low quality. And HentaiFF from the looks of it, it rips the episodes from muchohentai, so it kinda actually works out.
> 
> The problem Is the way of organice the episodes not the video.

Yeah their website is kinda a mess. But they are the only ones providing ai upscale along with hentaistream, from what i am aware. Rest of them copy from eachother. HAnime too maybe but that is premium.

**Comment by Diegopyl1209** [comment]
> > > The short answer is no
> > 
> > 
> > Welp. Anyways just tried haho also low quality. And HentaiFF from the looks of it, it rips the episodes from muchohentai, so it kinda actually works out.
> 
> The problem Is the way of organice the episodes not the video.

For example a hentai with only 1 EP. Have 6 different results from
English sub
Spanish sub
Raw
Raw uncensored
English uncensored
Spanish uncensored
