### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by Dmnboruto** [saikou-app/saikou#26]
After watching an anime episode if you try to watch another it's, out likely not to work even if I switch sources that's the main problem for me

**Comment by brahmkshatriya** [comment]
Please download the latest version (1.0.10.7) & send me the error you get

**Comment by seekwoo** [comment]
in this release v1.0.10.8 Gogo anime seems not working.😭

![Screenshot_2022-03-03-15-40-46-603_ani saikou](https://user-images.githubusercontent.com/100714133/156539711-8e52cae6-cc8e-425c-b592-b72b3985bbad.jpg)
