### ISSUE TITLE
Split Double pages to Single Pages

### ISSUE THREAD

**Issue by glasszay** [saikou-app/saikou#265]
### Summary

Split the double page into two pages

### The Problem

Double pages can be annoying when reading it on single-page mode because the reader tries to cram it in, this then may make the page unreadable unless the user zooms in to enlarge the content.

### The Ideal Solution

An option that allows the user to enable "dual split mode", which splits the image into two pages. This means that no matter what the pages will always be singular. 

### The Current Solution

Pinch zoom, or just using dual page mode.

**Comment by scrazzz** [comment]
> **The ideal solution**
> ... This means that no matter what the pages will always be singular.

Why not just read it in single page mode instead?

**Comment by brahmkshatriya** [comment]
I don't know any way to efficiently do that, without fucking up other things

**Comment by germaniuss** [comment]
Might give this a shot later on today.

**Comment by brahmkshatriya** [comment]
> Might give this a shot later on today.

you are gonna have a hard time

**Comment by brahmkshatriya** [comment]
Not gonna happen
