### ISSUE TITLE
Add more anime sources

### ISSUE THREAD

**Issue by yutubeare456** [saikou-app/saikou#268]
### Summary

Add more anime source

### The Problem

Some anime OVA is not in almost anime sources if there is any... it's Dub I can't find any sub. I think if you add more sources it's gonna be great.

### The Ideal Solution

Add more sources like Animepahe, or animixplay.

### The Current Solution

Nothing, I need to exit the app and go to some anime websites just to find it.

**Comment by brahmkshatriya** [comment]
animixplay is a simple gogoscraper, allanime is basically an alt in saikou
animepahe is not currently possible to add due to cloudflare protection
