### ISSUE TITLE
I ain't here to report issue but to suggest.

### ISSUE THREAD

**Issue by Bungeexgum** [saikou-app/saikou#27]
![IMG_20220125_090501](https://user-images.githubusercontent.com/88455631/150894008-9a6127d6-4a15-4ad1-b989-04a784cff60a.jpg)
Hi, can you make your player look like this instead? put those buttons under, like in this photo. Why double tap to seek? We're not use to it, when we tap the anime to pause because you know sometimes subs is fast, we need to tap in the center so the the buttons shows up fast. That's hassle 😩😩 the first photo i used old anime so the format is small you know what i mean?

![IMG_20220125_093021](https://user-images.githubusercontent.com/88455631/150894667-8c12ee8c-5cf0-4fcb-b3b6-6ff7008e050b.jpg)  
Thanks in advance, but if you won't change it or something, it's fine to me thou😊 just suggesting try ask my co-member in discord if they vote it.

**Comment by brahmkshatriya** [comment]
Sorry no more changes will be made to the video player layout now, probably not in the future either.

If you do need buttons for it, you can always fork the repo and build with your own ui
