### ISSUE TITLE
HD support on emulators

### ISSUE THREAD

**Issue by john-ioannides** [saikou-app/saikou#272]
### Summary

HD support on emulators (like Bluestacks)

### The Problem

It seems that the app does not allow 720p or 1080p resolutions on emulators. This is quite possibly a restraint of the app.
Tried on Bluestacks 5 with the Kamyroll multiquality server.

### The Ideal Solution

If this is indeed a constraint, it could perhaps be resolved.

**Comment by scrazzz** [comment]
Duplicate of #235
