### ISSUE TITLE
Add a tap option when reading a manga using the direction L to R/R to L

### ISSUE THREAD

**Issue by yurishein** [saikou-app/saikou#274]
### Summary

Add a tap version when the direction mode in the manga is 'Left to right' or 'Right to left'.

### The Problem

Saikou only provides swipe feature when you enable the mode to 'left to right' or 'right to left'

### The Ideal Solution

Add a feature or a option that you can tap when the mode direction is Left to right or Right to left

https://user-images.githubusercontent.com/80819031/174477165-69c090b9-ef6b-44d8-9582-3b527fbc30d7.mp4

### The Current Solution

Adding an option that you can tap the screen to see nex page/slide of the chapter when the direction is "Left to Right" or "Right to Left".

An Example:

https://user-images.githubusercontent.com/80819031/174477365-42145f6e-377a-4d29-8ee5-504fd049b5ff.mp4

### Additional Context

(idk if you understand my explaination but yeahh 😅😅,
 the 'current solution' app used in the explaination is Tachiyomi fyi)

**Comment by rahaaatul** [comment]
And also add support for remote buttons for Android TV to navigate. I have to use mouse to do that and it hurts my finger if I use it for long time.
