### ISSUE TITLE
Add a screenshot & screen record botton in anime player.

### ISSUE THREAD

**Issue by yurishein** [saikou-app/saikou#275]
### Summary

Add a screenshot botton & screen record botton that only records the anime sound when watching you favorite scene on the anime you're watching.

### The Problem

Would be easier to screenshot scenes and record breath taking scenes in the anime episode you're watching.

### The Ideal Solution

A feature that can screenshot & screen record a scene of the anime episode, because when you do it in you're own device it can be a hassle to swipe 3 of your finger and can cause error when swiping your fingers for you to screenshot a beautiful, romantic scene. And also screen recording your favorite scene in just a easy one click right on where you're watching.

### The Current Solution

Add a botton where you can screenshot & screen record a scene using the anime sound only anywhere on player.

Like this: (the results) (screenshot botton)
![2022-06-20 14_08_56](https://user-images.githubusercontent.com/80819031/174536342-7d0eb5dd-217f-4cd9-8cc2-a55d9cda312e.jpg)
![Untitled1_20220620141016](https://user-images.githubusercontent.com/80819031/174536356-56ee3410-6317-44b7-8931-9c7707320c30.png)

### Additional Context

You can put it beside the window to window botton to access it very easily. (hope this can be approved hehe, hope its understandable)

In here:
![Untitled2_20220620141442](https://user-images.githubusercontent.com/80819031/174537163-be358ad5-acb3-4068-a373-e1a64348d297.png)

**Comment by brahmkshatriya** [comment]
Nope not gonna happen,
this is something really unnecessary, in my point of view & not something I am gonna waste my time on
