### ISSUE TITLE
Community Plugins

### ISSUE THREAD

**Issue by HoriKyoukosimp** [saikou-app/saikou#276]
### Summary

Allow community to create their own plugins and release it to saikou plugins library (or discord server idk)

### The Problem

its solve nothing actually

i think that this idea might be great for some creative developers or community that want to make saikou better on their own way
the plugins idea might be
- Better manga reader (example auto scroll and stuff)
- video filter
- sleep timer
- allow user to add their own source 
- themes

but the problem is
- people might just release random plugins that ruins the experience
how to solve 
- all plugins have to be open source and have the mod teams (or we will call it plugins manager team if this feature get approved) 

### The Ideal Solution

i dont know how to answer this because this feature is literally community based
so yeah...

**Comment by scrazzz** [comment]
> i think that this idea might be great for some creative developers or community that want to make saikou better on their own way
the plugins idea might be

Won't it be easier to just PR the feature to the app directly instead of making it a plugin?

> all plugins have to be open source and have the mod teams (or we will call it plugins manager team if this feature get approved)

Very tedious to maintain in my opinion.

**Comment by venkat2305** [comment]
Actually can you guys make this app extension based(reducing the chances of getting a DMCA)

**Comment by HoriKyoukosimp** [comment]
> Actually can you guys make this app extension based(reducing the chances of getting a DMCA)

That's a plan when reaork after getting archived

Rework after the app gets archived :
- Extension Based
- Rework the app design to be an Single Activity App, (& possibly use navigation?)
- Material 3 ui theming
- Mal sync
- Forums & activity support

**Comment by venkat2305** [comment]
Why will the app get archived. CS3 is figuring out an extension based system to avoid dmca
