### ISSUE TITLE
Manga page spacing issue on tablet 

### ISSUE THREAD

**Issue by Wubman** [saikou-app/saikou#279]
### Summary

When using a tablet, there is a lot of empty space between pages in any manga in continuous scroll

### Reproduction Steps

Using a tablet device, open any manga and there will be large gaps between each page when scrolling. Toggling spaced pages off just slightly decreases the spacing issue, but the gap is still large.

### Expected Result

I expected the beginning of each page to be flush with the end of the previous page

### Actual Result

There is a large gap between each page regardless of settings. It makes it difficult reading manwha or webtoons that normally function in continuous scroll. 

### Device Information

Saikou Version: 1.2.0.15
Device: Samsung Galaxy Gab 7s+
Android: 12

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
I am unable to reproduce this, please try latest version

**Comment by Blatzar** [comment]
This happens due to some weird issue with WRAP_CONTENT and is created by updateLayoutParams in [ImageAdapter.kt](https://github.com/saikou-app/saikou/blob/main/app/src/main/java/ani/saikou/manga/mangareader/ImageAdapter.kt#L64)

Using bitmap and reading the height works, but the recyclerview gets fucked when scrolling up and down, the wrong images gets placed. This might possible to fix with onViewRecycled

```kotlin
                    override fun onResourceReady(resource: File, transition: Transition<in File>?) {
                        imageView.visibility = View.VISIBLE
                        val bitmap = BitmapFactory.decodeFile(resource.absolutePath, BitmapFactory.Options())

                        if (settings.layout != PAGED)
                            parent.updateLayoutParams {
                                if (settings.direction != LEFT_TO_RIGHT && settings.direction != RIGHT_TO_LEFT)
                                    height = bitmap.height
                                else
                                    width = ViewGroup.LayoutParams.WRAP_CONTENT
                            }
                        view.setImage(ImageSource.bitmap(bitmap))
                        ObjectAnimator.ofFloat(parent, "alpha", 0f, 1f).setDuration((400 * uiSettings.animationSpeed).toLong())
                            .start()
                        progress.visibility = View.GONE
                    }
```
