### ISSUE TITLE
Server Not Working

### ISSUE THREAD

**Issue by Zeroo097** [saikou-app/saikou#28]
Gogo Anime Server is Not Working and when i use 9anime in place of gogoanime it starts any random episode of random anime.![Screenshot_20220128-123622.jpg](https://user-images.githubusercontent.com/91909890/151502854-6d721374-abe7-4b8f-9a69-e60351d0f51a.jpg)

**Comment by brahmkshatriya** [comment]
Use "wrong title" button to change the wrong anime picked by 9anime, & select the one you were looking for, in this case one piece
Gogo anime seems to be blocked for some people it seems
