### ISSUE TITLE
black screen when reading

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#280]
### Summary

sometimes when swiching chapters or open a new manga, or just scrolling down to load new pages, it sometimes just not load the images and will just be black.

### Reproduction Steps

swich chapters, open a new manga, or just scroll down to load new pages.
it doesn't allways happen, but it's on all sources so i know that it's not just a bug with a certan server.

### Expected Result

i expected the pages to load

### Actual Result

pages never loaded

### Device Information

saikou version:1.2.0.15/1.2.0.12
brand: samsung
android version: 5.1.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

the copying didn't work so i just typed it.

**Comment by brahmkshatriya** [comment]
Closed due to inactivity
