### ISSUE TITLE
when reentering the app after having it open, but not focused for a while it will act like on lightmode until you close and reopen it again.

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#282]
### Summary

when reentering the app after having it open, but not focused for a while it will act like on lightmode until you close and reopen it again.

### Reproduction Steps

open the app
leave it open for a while but have a different app in forgroung
open the app from the curently open apps screen
then it will try to load, but it will load in lightmode.

### Expected Result

should have the usual darkmode theme

### Actual Result

has a lightmode theme

### Device Information

saikou version:1.2.0.15/1.2.0.12
brand: samsung
android version: 5.1.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

the copying didn't work so i just typed it.

**Comment by brahmkshatriya** [comment]
this is something unfixable, due to how it has been coded
