### ISSUE TITLE
wrong tab when leaving an anime/manga from your list

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#284]
### Summary

when you go to your anime/manga list and click on one, after you close it it will allways take you back to the watching tab

### Reproduction Steps

click on anime list
go to a tab other then watching
click on an anime
click the x to close the anime
it will then switch you to the watching tab

### Expected Result

it will leave you on the tap you scelected the anime from

### Actual Result

it will switch you to the watching tab

### Device Information

saikou version:1.2.0.15/1.2.0.12
brand: samsung
android version: 5.1.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

i would also like an option to combine the "completed ova", "completed tv", "completed movie", "completed ona", "completed special", and possibly others into a single "completed" tab

**Comment by scrazzz** [comment]
I can't reproduce this issue

https://user-images.githubusercontent.com/70033559/176580557-9a300ee1-62da-4cc5-80fd-c378a2e67492.mp4
