### ISSUE TITLE
crash on chapter completion

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#287]
### Summary

crash on chapter completion

### Reproduction Steps

this has happened 4 times in a row not, but when i reach the end of a chapter the last page won't load and after about 5 secs it will just close out the manga and take me back to the read section and reset the theme to white again until closing and reopening. i am using the mangakakalot server if that would matter, this just started happening for me today. i've not seen if this happens on other servers yet.

no idea if this is just be because of somthing else i did or that particular server, or an actual issue with the app.

### Expected Result

 loads last page

### Actual Result

goes to read section

### Device Information

saikou version:1.2.0.15/1.2.0.12
brand: samsung
android version: 5.1.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
Please tell the Reproduction Steps on what you did to make this error occur.

You're basically telling a summary of the bug report in the Reproduction Steps.

**Comment by DemonLordDiablo** [comment]
set the server to mangakakalot
open the manga
read until you reach the bottom of the page
the last page should be blank and it'll hang for about 5 secs then close the manga.

**Comment by scrazzz** [comment]
> the last page should be blank and it'll hang for about 5 secs then close the manga.

I can't reproduce this issue. I tried it on Chainsaw Man.
