### ISSUE TITLE
Add new manga sources

### ISSUE THREAD

**Issue by yutubeare456** [saikou-app/saikou#288]
### Summary

Add new manga sources.

### The Problem

For better manga scans and translation... And sometime I when was reading berserk I realized that I read it the wrong way using manggabuddy cause the chapter in manga buddy isn't the right order they're in Volumes format and the order is messy so I tried another source and almost sources is the same except mangadex but the problem in mangadex is the scans sometimes its really confusing.

### The Ideal Solution

Add Mangalife or Mangahub as a new manga sources.

### The Current Solution

Just change source to mangadex.

### Additional Context

![Screenshot_2022-07-02-09-29-30-22](https://user-images.githubusercontent.com/107675483/176981805-b4d172dc-4b32-4ebb-b453-5be44514689d.png)

This one is from mangadex ⬆⬆⬆

![Berserk - #130 - Berserk 130 - 4](https://user-images.githubusercontent.com/107675483/176981831-8ba4f6df-0ba5-4841-8195-5fbd046eb63c.jpg)

And this one is from Mangahub ⬆⬆⬆

**Comment by brahmkshatriya** [comment]
Send a link to a "mangahub"

**Comment by yutubeare456** [comment]
> Send a link to a "mangahub"

Here...
https://mangahub.io/
