### ISSUE TITLE
Enable/Disable hentai

### ISSUE THREAD

**Issue by Chargersx619** [saikou-app/saikou#289]
### Summary

Ability to disable or filter adult shows/hentai

### The Problem

I love the app and features but don't use it to watch anything considered hentai. An ability to disable the topic altogether would be nice.

### The Ideal Solution

An enable or disable checkbox in settings

**Comment by scrazzz** [comment]
Adult content is disabled/filtered by default.
The Manga page and Anime page doesn't contain any adult content.
When searching for anime/manga, you need to tick the Adult checkbox for NSFW content (if you are logged into Anilist and have enabled 18+ in Anilist settings).
