### ISSUE TITLE
add streched video ratio option 

### ISSUE THREAD

**Issue by shiiii6** [saikou-app/saikou#29]
There is only zoomed in option available

**Comment by shiiii6** [comment]
![Screenshot_20220128-163703285](https://user-images.githubusercontent.com/97912949/151536613-820c9107-ea4e-44ee-961a-050127c4bef5.jpg)

**Comment by GoluLiliput** [comment]
I would love that to be a feature too. U can add all the 3 views switch from the single button which I already present in the app player
