### ISSUE TITLE
have an option to have joined chapters

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#290]
### Summary

have an option to have joined chapters

### The Problem

makes it easier to read many chapters one after another

### The Ideal Solution

on paged mode: be able to scroll down on the last page of a chapter to go to to the next chapter

on continuis mode: just have the chapters be joined together in the same way the pages are so you can seemlessly scroll between chapters.

### The Current Solution

just click then click on next chapter

**Comment by brahmkshatriya** [comment]
Duplicate of #190
