### ISSUE TITLE
what does "Auto Update Progress has now been Reset-ed "

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#292]
### Summary

just a question

### The Problem

i have no idea what this means

### The Ideal Solution

add a different type for just questions

### Additional Context

i held on the "current" dropdown button to get this

you should also add a different type when submitting an issue for just questions

**Comment by scrazzz** [comment]
> you should also add a different type when submitting an issue for just questions

There's a discord server available which you can join to ask your question.

What I understood from the code is that when you click the "Current" button, it updates the progress on AniList. Not sure why it says "Auto update progress has been reset-ed'.
