### ISSUE TITLE
Optimize the app for tv 

### ISSUE THREAD

**Issue by Adi-MayNotSpeak** [saikou-app/saikou#3]
Well.  I use apps only on TV and use websites on mobile and laptops so yeah , also , this is the case with most people

**Comment by Adi-MayNotSpeak** [comment]
> Well. I use apps only on TV and use websites on mobile and laptops so yeah , also , this is the case with most people

I reallt like ( https://github.com/deceptions/no ) this app's video player (for tv version ofc ) you can take inspiration from here

**Comment by brahmkshatriya** [comment]
I personally do not plan to make TV, neither do I have resources to test it & neither do I the time for it.
If someone experienced with TV, wanna contribute I don't mind it.

**Comment by LagradOst** [comment]
ye, tv dev is fucked. dont do it

**Comment by zakius** [comment]
I wonder if optimizing keyboard navigation wouldn't cover most usecases already, depending on the way TV/STB interprets inputs from remote that may just work

**Comment by Pahiro** [comment]
> I wonder if optimizing keyboard navigation wouldn't cover most usecases already, depending on the way TV/STB interprets inputs from remote that may just work

Nanoc6 is doing an excellent job with the TV version. It's working well and kept up-to-date.

**Comment by rollingmoai** [comment]
https://github.com/Nanoc6/SaikouTV

**Comment by brahmkshatriya** [comment]
Yea TV support is no longer planned for this repo, please go to any other forks of SaikouTV
