### ISSUE TITLE
9anime Real time issue 

### ISSUE THREAD

**Issue by Igrissid** [saikou-app/saikou#30]
When it comes to 9anime, I notice that the app does not have the latest episodes out just like the site does. It takes an hour or two for the latest episode to come out. For example, Blue Peroid is on the 9anime site at this moment but I am not able to access it on the app.

**Comment by brahmkshatriya** [comment]
The app does not directly scrape 9anime, it scrapes a [scraper](http://animekisa.in/), which takes embeds from 9anime, & the scraper takes time to update, or sometimes outright doesn't update an anime. It's the limitation of a working 9anime scraper

**Comment by Igrissid** [comment]
@brahmkshatriya  Is it harder to scrape directly from 9anime? If so, you don't have to change the server; I'm fine with it.

**Comment by brahmkshatriya** [comment]
> @brahmkshatriya  Is it harder to scrape directly from 9anime? If so, you don't have to change the server; I'm fine with it.

I wonder why there are no other apps with 9anime as source 😂
