### ISSUE TITLE
a simple background patern for when reading manga

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#306]
### Summary

a simple background patern for when reading manga so you can easily tell if a page isn't loaded yet.

### The Problem

to tell if the pages havn't loaded yet, or if there is just a massive black space in the pages.

### The Ideal Solution

just add a simple patern to the background, such as stripes to help people know what is actusly bg.

**Comment by brahmkshatriya** [comment]
Not gonna happen
