### ISSUE TITLE
Bug about the new update.

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#309]
### Summary

Has a error about having a list

### Reproduction Steps

Update my app

### Expected Result

Fixing the error 

### Actual Result

Can't see my favorite list 

### Device Information

App:1.2.0.16
vivo1606
snapdragon425
Android: 6.0.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
Not sure what you're talking about. Please be more specific. 
Anyways, the error you are facing is most likely already reported on the Discord server. So I'm closing this issue.
