### ISSUE TITLE
Vidstreaming server does not work

### ISSUE THREAD

**Issue by TitansSami** [saikou-app/saikou#31]
Hey there, 

I just would like to express my earnest gratitude for making such an amazing anime streaming app. I really love your work.

But there's one problem I have been encountering since I left Netflix for watching anime. That is the full screen problem. Everytime I go full screen on the saikou app the subtitles just get zoomed in and it happens on all the servers except the Zoro one. The Zoro vidstreaming server actually didn't zoom in the subtitles when going full screen. I just would love to see you fix the problem with the vidstreaming server for Zoro while watching naruto Shippuden.

**Comment by brahmkshatriya** [comment]
Please try using a vpn, & report to me

**Comment by TitansSami** [comment]
I tried with the VPN but regretfully it's not working. Please fix the Zoro vidstreaming server for naruto Shippuden. It's the only server which does not crop in subtitles when going full screen mode

**Comment by brahmkshatriya** [comment]
well I havent looked into it, but zoro has up their security & requires more stuff to play the video & I couldn't figure how to do it, so yeah, this will take time.

**Comment by TitansSami** [comment]
Then can you make sure that on the remaining servers while watching Naruto Shippuden in the full screen state the subtitles don't get cropped in. That would be of great help. Thanks

**Comment by TitansSami** [comment]
Can you fix it in the next update?

**Comment by brahmkshatriya** [comment]
Will be fixed in the next update
