### ISSUE TITLE
Manga & anime list items per row.

### ISSUE THREAD

**Issue by yutubeare456** [saikou-app/saikou#311]
### Summary

Manga & anime list items per row

### The Problem

I think it's great to add an option to manage and change the item number in rows and columns in your manga and anime library... For a much more convenient look at your list that suits the user's preferrence.

### The Ideal Solution

Add an option to change item per rows and columns in your library.

### The Current Solution

Nothing.

### Additional Context

I'm not sure if you understand what I'm pointing I'm not really good at English...

But here are some example...

2 items per rows and column ⬇⬇⬇
![Screenshot_2022-07-11-00-20-19-12](https://user-images.githubusercontent.com/107675483/178153516-092a3ed6-6590-4e52-adab-3d9c473d7049.png)

3 items per rows and column ⬇⬇⬇
![Screenshot_2022-07-11-00-20-01-45](https://user-images.githubusercontent.com/107675483/178153545-710b1678-f5e5-45b2-98fa-2728102f8136.png)

4 items per rows and column ⬇⬇⬇
![Screenshot_2022-07-11-00-20-38-57](https://user-images.githubusercontent.com/107675483/178153572-6b6ad0b2-0455-4622-9689-6e0b0e23cbbc.png)

It's from aniyomi app.

**Comment by brahmkshatriya** [comment]
Not gonna happen
