### ISSUE TITLE
Manga Download

### ISSUE THREAD

**Issue by ImranMZ** [saikou-app/saikou#314]
### Summary

Download feature for Manga

### The Problem

Is it possible to add a download feature for Manga ?
I don't have internet access all day so it would really help if we can download manga for offline view 👍
Thanks for this app btw 🫶

### The Ideal Solution

....idk

**Comment by scrazzz** [comment]
Duplicate of #177
It's already planned: https://github.com/saikou-app/saikou/projects/1#card-81978963
