### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Dmnboruto** [saikou-app/saikou#32]
I have 2 bugs when you read manga or watch anime for a long time like 2 episodes when you go back the app will lag. The other one is when I change to 9anime from gogo and change quality it doesn't load like when I tap play button it loads approx 2 sec then stops

BTW ty for this amazing app maybe consider adding settings ☺

**Comment by brahmkshatriya** [comment]
> when you read manga or watch anime for a long time like 2 episodes when you go back the app will lag

Which is why I am gonna rewrite the app

> The other one is when I change to 9anime from gogo and change quality it doesn't load like when I tap play button it loads approx 2 sec then stops

Fixed in #31
