### ISSUE TITLE
JkAnime Source bug

### ISSUE THREAD

**Issue by iNeoxx** [saikou-app/saikou#326]
### Summary

@Serializable JKAnime Source 

### Reproduction Steps

When you want to watch an episode of some anime when loading the players, it does not load any and the error occurs.
![Screenshot_20220719-172134_Saikou ](https://user-images.githubusercontent.com/44181928/179917101-0857fcee-fd05-4df1-89bf-c4ba1c92dd55.jpg)

### Expected Result

Be able to view all video sources.

### Actual Result

Serializable erorr in JKAnime source

### Device Information

Saikou Version: 1.2.0.17
Device: samsung r9s
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Post in  https://github.com/Diegopyl1209/saikouSP/issues
