### ISSUE TITLE
Add MangaLife as a source

### ISSUE THREAD

**Issue by cheesuscrisp** [saikou-app/saikou#330]
### Summary

MangaLife is a mirror to mangasee, which faces frequent downtimes

### The Problem

MangaSee (already implemented, https://mangasee123.com/) frequently goes down, and MangaLife (https://manga4life.com/) is a mirror of it, so it can compensate for downtimes. It seems similar so I *think* it should be easy to implement, but I don't know.

### The Ideal Solution

Implementing MangaLife as a source for manga, similar to how mangasee and other sources are implemented.

### The Current Solution

there is no solution as of now, as I'm requesting a new source addition

**Comment by brahmkshatriya** [comment]
I have never seen, Mangasee go down
& I am pretty if it did, manga4life would also go down

**Comment by cheesuscrisp** [comment]
MangaSee was down yesterday, and goes down every few weeks for hours at a time, so adding a mirror makes sense to me. But I also understand if it isn't worth what I think is minimal effort as they are a mirror.
