### ISSUE TITLE
All sources except 9 animes working. It was fine before but after i uninstalled and reinstalled it , error pops up

### ISSUE THREAD

**Issue by farzana840** [saikou-app/saikou#332]
### Summary

9anime source is not working. Error pops up saying : Expected start of the object '{', but had 'EOF' instead at path: $JSON input: .....et.js#pubid=ra-62cc6bf4fa910743"></script></body></html>

### Reproduction Steps

Installing and reinstalling the app 

### Expected Result

Should have been working fine

### Actual Result

9anime is not working, and this error pops up :
Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: .....et.js#pubid=ra-62cc6bf4fa910743"></script>

</body>

</html>

### Device Information

Saikou Version: 1.2.0.17
Device: Redmi dandelion
Architecture: arm
OS Version: REL 10 (29)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Please help out ASAP !

**Comment by brahmkshatriya** [comment]
they changed their site recently, will take some time to adapt to new changes

**Comment by Shemar890** [comment]
Update the app

**Comment by farzana840** [comment]
> Update the app

I am already using the latest version of saikou

**Comment by Shemar890** [comment]
Send me the latest version

**Comment by farzana840** [comment]
> Send me the latest version

The latest is 1.2.0.17

**Comment by SkAfif** [comment]
The latest one is beta. Shivam will be updating beta for a while. So leave the normal one

**Comment by farzana840** [comment]
> The latest one is beta. Shivam will be updating beta for a while. So leave the normal one

So which version you say should i install?

**Comment by SkAfif** [comment]
Simply download this
https://github.com/saikou-app/saikou/releases/download/v1.2.0.17/Saikou-1.2.0.17.apk
And don't doubt more 🙏

**Comment by farzana840** [comment]
> > The latest one is beta. Shivam will be updating beta for a while. So leave the normal one
> 
> So which version you say should i install?

Yeah downloaded this , but the bug persists

**Comment by SkAfif** [comment]
> Update the app

This one comment up there isn't expected

**Comment by SkAfif** [comment]
9anime changed their whole site. As saikou is set to scrap 9anime in their previous website, it's currently not scrapping the new site. So it will take some time till developer fixes it. Use other sources till then

**Comment by brahmkshatriya** [comment]
mf repeats the same shit I wrote 💀

**Comment by SkAfif** [comment]
This person is clinging onto the comment about updating the app ignoring yours. So just cleared the confusion for him.

**Comment by Shemar890** [comment]
9Anime Animepahe Animixplay AllAnime
These are sites not working some is taking long load other are doing some thing

**Comment by Searchcat37** [comment]
> 9Anime Animepahe Animixplay AllAnime
> These are sites not working some is taking long load other are doing some thing 

Again 9Anime site changed, give devs a couple of days. For all of these your isp could be blocking it. Animixplay, works on my end, could be you are choosing the backup mirror or the anime does not exist on the site. Animepahe, works for me if I choose the 720p mirror, the 1080p is slow/does not work. AllAnime seems to not work or has a very small library of anime.

**Comment by Shemar890** [comment]
> > 9Anime Animepahe Animixplay AllAnime
> > These are sites not working some is taking long load other are doing some thing 
> 
> Again 9Anime site changed, give devs a week. For all of these your isp could be blocking it. Animixplay, works on my end, could be you are choosing the backup mirror or the anime does not exist on the site. Animepahe, works for me if I choose the 720p mirror, the 1080p is slow/does not work. AllAnime seems to not work or has a very small library of anime.
> 
> I recommend (Using app, when using browser Zoro is best):
> 1. Kammyroll (Does not have some niche anime but mirrors always work)
> 2. Zoro [Very big library, don't use StreamSB mirror for sub . Vidstreaming and Vidcloud work as long as you don't turn off your phone while watching (causes mirrors to not work unless you start for being)]
> 3. Animixplay (a few niche ones are not on there)
>  
> 9Anime pretty good in browser not sure about app
> 
> I would not recommend Gogo as the audio quality is noticeably different from the rest
> 
> 
> (Is the comment too long, yes)

Is there going to be any new update yet 
We need one cause sites update

**Comment by zbue** [comment]
Y'all build the app yourselves if you're that impatience lul

**Comment by chenkaslowankiya** [comment]
> Y'all build the app yourselves if you're that impatience lul

Lmao

**Comment by AdriBD83** [comment]
When will new update arrive?
It has been about more than a week since 9anime changed their site. 
How long it will take for the patch??

**Comment by Searchcat37** [comment]
> When will new update arrive?
> It has been about more than a week since 9anime changed their site. 
> How long it will take for the patch??

I has been fixed just build the app yourself and stop complaining.

**Comment by Shemar890** [comment]
> > When will new update arrive?
> > It has been about more than a week since 9anime changed their site. 
> > How long it will take for the patch??
> 
> It has been fixed just build the app yourself and stop complaining. What is so special about 9Anime that you have to have it?

Need new update
