### ISSUE TITLE
9anime server error

### ISSUE THREAD

**Issue by Dharmender-Kumar** [saikou-app/saikou#336]
### Summary

Anime episodes unable to upload from 9anime server

### Reproduction Steps

Tried to open anime episodes list with 9anime server.

### Expected Result

There should be episode list of anime.

### Actual Result

Episode list was empty and below error shown:

Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: .....et.js#pubid=ra-62cc6bf4fa910743"></script>

</body>

</html>

### Device Information

Saikou Version: 1.2.0.17
Device: realme RMX3085L1
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Diegopyl1209** [comment]
ok mr obvious

**Comment by junaidd09** [comment]
9anime still doesn't work. This issue needs to be reopened and fixed.
