### ISSUE TITLE
Sources as plugins

### ISSUE THREAD

**Issue by Lunarequest** [saikou-app/saikou#337]
### Summary

Sources should be plugins to the app

### The Problem

Currently sources are some what hardcoded to the app. When a source change like say 9anime a update to the app needs to be pushed out while this works it's not ideal.

### The Ideal Solution

Sources should be separated from the app. By having sources seperated from the app more sources can be added and independentaly updated. A similar plugin system is used by tachiyomi

**Comment by scrazzz** [comment]
Duplicate of #276
