### ISSUE TITLE
not all tags are shown

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#338]
### Summary

some tags that are shown on anilist, but not in the app.

### Reproduction Steps

go to [Oshi no Ko] on app and anilist
on anilist the tag tsundere is there mut not in the app
some other tags are also hidden too.

### Expected Result

all tags should allways be visiable

### Actual Result

some tags were hidden

### Device Information

Saikou Version: 1.2.0.17
Device: samsung gtexswifi
Architecture: arm
OS Version: REL 5.1.1 (22)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

i would also like to have a way to search for both adault and non adault manga/anime at the same time.

**Comment by brahmkshatriya** [comment]
duplicate of #146

**Comment by DemonLordDiablo** [comment]
can you tell my why this was marked as a duplicate? it seems different then the other question.

**Comment by brahmkshatriya** [comment]
reworking search will have all tags

**Comment by DemonLordDiablo** [comment]
oh, okay.
