### ISSUE TITLE
Request for Addition of Anime release Calendar 

### ISSUE THREAD

**Issue by rsmyst** [saikou-app/saikou#339]
### Summary

I figured it would be nice to see on what days the anime I'm watching airs.

### The Problem

Currently, all anime in "watching" are just there. You can only see when they're airing by tapping into the anime.

### The Ideal Solution

Addition of a calendar view of anime episode release.
Perhaps it can indicate episode number of an anime with its name and have it color coded in a weekly calendar view.

### The Current Solution

None

### Additional Context

For reference, something like https://anichart.net/airing but in weekly Google calendar form. 
Feature would make it easier to keep track of anime!

**Comment by RuboGubo** [comment]
Would also be nice if this was added to the native calendar
