### ISSUE TITLE
[Enhancement] Home page loading.

### ISSUE THREAD

**Issue by Mano5JP** [saikou-app/saikou#34]
If i open a app then close from recent and then open app again it's working fine, but if i don't close app from recent then and open again it doesn't load properly.

[Reference Video](https://sh-ort.app/bcs3v)

**Comment by brahmkshatriya** [comment]
video needs access, please make it public
or join the discord server & send there

**Comment by Mano5JP** [comment]
https://imgur.com/a/C1GfcJE

**Comment by brahmkshatriya** [comment]
Please download the app again & try doing it, I made some changes, so bug might appear again

**Comment by Mano5JP** [comment]
Works as expected.

Thx 

Closed #34
