### ISSUE TITLE
Cast option

### ISSUE THREAD

**Issue by Demon-blood** [saikou-app/saikou#343]
### Summary

A cast feature for anime playing

### The Problem

/

### The Ideal Solution

/

### The Current Solution

/

### Additional Context

I would love to see a feature to cast, since I'm mainly watching my anime on TV. Currently I'm just casting my phone screen to my chromecast, but that's very impractical  cause it causes the streaming to stutter really badly at times.

**Comment by Nanoc6** [comment]
While you can indeed cast video directly to your TV, it could have issues as you are experiencing and im afraid even if saikou where able to directly cast the video you would still experience the same issues, for that reason, apps like youtube or netflix do not work that way.

The usual is to cast only a link to the content to a matching app on TV, so it can directly reproduce it.

Soo if im not wrong this would need to be done on the TV fork, could be a great enhancement.

BTW: using the TV fork directly with the remote would probably give you a better experience than casting your screen, once logged in its pretty fast to use.

**Comment by Nanoc6** [comment]
nevermind, google says its restricted to apps on google play only cause security reasons

https://developers.google.com/cast/docs/android_tv_receiver/core_features#register_developer_devices
