### ISSUE TITLE
Tracker status doesn't update.

### ISSUE THREAD

**Issue by Mano5JP** [saikou-app/saikou#35]
I just watch Vinland <**plan to watch**>, it uptdated my episodes that i watch but it didn't change from **plan to watch** to **watching**
![Screenshot_20220131-223800_Saikou.png](https://user-images.githubusercontent.com/64928088/151860879-c7bdeda4-81ff-46b0-bcbf-5018dda4d490.png)

![Screenshot_20220131-223840_Chrome.png](https://user-images.githubusercontent.com/64928088/151860999-1b8c6962-eec1-4816-8fd2-51305049ddf1.png)

**Comment by Dmnboruto** [comment]
Probably u have to change it manually

**Comment by Mano5JP** [comment]
👍
