### ISSUE TITLE
Any chance of adding the OnePace source for OnePiece?

### ISSUE THREAD

**Issue by Fatcakes** [saikou-app/saikou#357]
I know aniyomi has a working extension so is it possible for this app? This app is superior in just about every way.

**Comment by scrazzz** [comment]
Please follow the feature request template.

**Comment by Diegopyl1209** [comment]
anyway the answer is no

**Comment by ITADORI-15** [comment]
Can u add the DubbedAnime  source.....its gr8 for ppl who watch dubbed shows@Diegopyl1209
