### ISSUE TITLE
we need more websites to choose from for Doujins and hentai

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#358]
### Summary

we need more websites to choose from for Doujins and hentai

### The Problem

there is only 1 (because the other doesn't work) website to choose from for Doujins and hentai, and it's also hard to find what you want because of their weird way of doing titles there.

### The Ideal Solution

add about 3 to 4 more websites to choose from for Doujins and hentai

**Comment by scrazzz** [comment]
> we need more websites to choose from for Doujins and hentai

Suggest some sources that you want to be added.
