### ISSUE TITLE
Media control notification and PiP

### ISSUE THREAD

**Issue by SLDDL** [saikou-app/saikou#359]
### Summary

Please add support for the media control notification and allow picture in picture 

### The Problem

The current app does not support the media control notification and picture in picture 

### The Ideal Solution

Add support for the media control notification and PiP

### Additional Context

![Screenshot_2022-08-17-02-07-12-463_com miui home-edit](https://user-images.githubusercontent.com/29633620/185005959-2b7635e3-695a-471a-aa8b-4c61d0cbe64d.jpg)

**Comment by scrazzz** [comment]
PiP is already supported.

Not sure why adding media controls in notifications would be a feature because this isn't a music player app.
