### ISSUE TITLE
Keyboard media control support.

### ISSUE THREAD

**Issue by ni3x** [saikou-app/saikou#360]
### Summary

Video player can user keyboard arrow keys or other keys to control playback.

### The Problem

I am using Saikou on Windows WSA which helps me to automatically keep track of anime on anilist instead of using websites. Instead of using a mouse to control playback back and forward it will be easier if there is a support for keyboard to control playback or other functions like change to next episode or skip 85 seconds. This feature can be beneficial for tablets with keyboards.

### The Ideal Solution

Video player can use the following keyboard keys for functions:

1. Arrow keys left and right - Control back and forward playback.
2. B and N keys - Backward an episode and Forward an episode.
3. Spacebar - Toggle playback(play/pause) 
4. M key - Mute
5. Z key - Show available qualities
6. X key - List of episodes in player.
7. C key - Toggle caption (optional)

**Comment by scrazzz** [comment]
> I am using Saikou on Windows WSA which helps me to automatically keep track of anime on anilist instead of using websites.

What do you mean by this? Saikou already has AniList integration built-in.

I don't think it's possible to add this feature since you're running this on an emulator and it's out of the scope of this app.

**Comment by Adolar0042** [comment]
I'd also like to mention extensions like [MAL-Sync](https://chrome.google.com/webstore/detail/mal-sync/kekjfbackdeiabghhcdklcdoekaanoel) that track for official and unofficial sites to either anilist or MAL

**Comment by SLDDL** [comment]
> > I am using Saikou on Windows WSA which helps me to automatically keep track of anime on anilist instead of using websites.
> 
> What do you mean by this? Saikou already has AniList integration built-in.
> 
> I don't think it's possible to add this feature since you're running this on an emulator and it's out of the scope of this app.

Actually its pretty simple, add the feature as if it was for a bluetooth/usb keyboard connected to the phone and it will also work with wsa. ( also wsa is not an emulator but a subsystem, so it runs way better )

**Comment by brahmkshatriya** [comment]
Honestly, I dont mind adding this

**Comment by ni3x** [comment]
Devs, thank you for implementing this feature. It is functioning well, but there is a minor issue where a white overlay with 25% transparency appears when using keyboard functions and only disappears when clicking on the screen with a mouse, which is quite frustrating. Could this problem be fixed in the next upgrade, if possible?
