### ISSUE TITLE
Private Entries

### ISSUE THREAD

**Issue by lonewolf0211** [saikou-app/saikou#367]
### Summary

Would like to be able to toggle anilist entries as private 

### The Problem

I can't mark content as private from the built in list editor so I have to use another app to manage my lists.

### The Ideal Solution

Add a checkbox in the list editor to set shows as private or the option in settings to auto private adult content. That way people can choose to make certain anime or adult content from their lists private. 

### The Current Solution

Use a different app to manage my list (Oujo).

**Comment by scrazzz** [comment]
> Add a checkbox in the list editor to set shows as private or **the option in settings to auto private adult content.**

![whenthe](https://user-images.githubusercontent.com/70033559/186560298-c92020d7-a2e4-43b2-bd0b-f639feaf915a.jpg)
Keeping "Update Progress for Hentai" off will not update it.

**Comment by lonewolf0211** [comment]
That's not a solution, it's a work around and it only works for adult content. Anilist allows private entries for a reason. Not updating entries that could simply have been set as private using the API is wasted potential for the app. I love Saikou and I just want to see it at it's best. 

For now I'll just keep using Oujo to change the entries to private. No big deal, appreciate all the work you guys do.

**Comment by Shemar890** [comment]
Oujo anime app
