### ISSUE TITLE
9anime not working

### ISSUE THREAD

**Issue by pakodx** [saikou-app/saikou#368]
### Summary

9anime hasn't been working for some weeks

### Reproduction Steps

Set 9anime as the server on any anime

### Expected Result

Episode list to appear so I could watch them

### Actual Result

Expected start of the object '{', but had 'EOF'
instead at path: $
JSON input: .....et.js#pubid=
ra-62cc6bf4fa910743"></
script>

</body>

</html>

### Device Information

Latest saikou
Motorola E7 play
arm7a i think, I'm not a dev idk these things
Android 10

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

It worked fine before, I hadn't updated or anything when this happened. I just now updated to the latest beta version and it didn't solve the issue.

**Comment by Shemar890** [comment]
Need a new update
