### ISSUE TITLE
Request for Fixing download issue

### ISSUE THREAD

**Issue by Devansh7u** [saikou-app/saikou#373]
### Summary

Request for Fixing download issue

### The Problem

![Screenshot_20220828-154939_Saikou ](https://user-images.githubusercontent.com/109319315/187069182-fed81e4e-0280-4f33-9695-9fba04584adc.jpg)
I like to watch anime without buffering So I Prefer to download anime Episodes. But when l use Your app to dowload episodes It shows that download was unsucessfull. Due to some reason or issues.

### The Ideal Solution

The ideal solutions is that the app should also support 3rd party app/ downloaders to download episodes. Like IDM+ or something of that sort.
![Screenshot_20220828-155044_1DM+](https://user-images.githubusercontent.com/109319315/187069392-7ebffae0-5e1e-423e-a8e0-a9e1b2a6e164.jpg)

### The Current Solution

The current solution can be that the app can have an inbuilt downloader like other apps.But it should be fast.
![Screenshot_20220828-155001_Aniyomi](https://user-images.githubusercontent.com/109319315/187069529-5c63a245-8254-488c-b92f-bc0ef5e703da.jpg)

### Additional Context

I really love this app It is beautiful and has very nice Interface and if this issue is Fixed than I will deferately use this app more than Aniyomi.

**Comment by brahmkshatriya** [comment]
long click on the download button, it will copy the url of the video
paste it your fav download manager

**Comment by Devansh7u** [comment]
Ya I'm facing it too
