### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by skaveh1384** [saikou-app/saikou#375]
### Summary

A widows version would be a great feature

### The Problem

Some people dont have access to and android device a windows version is great

### The Ideal Solution

A windows version would be great combo with the bulk download feature and the rest

**Comment by TusharCoder-Ing** [comment]
Imagine asking for this lol

**Comment by xidsyed** [comment]
I can't be the only one trying to run this on WSA (Windows Subsystem for Android)

**Comment by brahmkshatriya** [comment]
> I can't be the only one trying to run this on WSA (Windows Subsystem for Android)

That's what people with w11 do
