### ISSUE TITLE
This is not issue just a request.

### ISSUE THREAD

**Issue by Bungeexgum** [saikou-app/saikou#38]
![IMG_20220202_100542](https://user-images.githubusercontent.com/88455631/152082346-3dc98c61-b8bf-4530-8209-9062a8ff96c8.jpg)
 Sir, i hope this time you'll Accept my request hehe what do you think? Just Try it maybe that scroll ep title you add would not be use. Because it's not exceeding anymore

**Comment by brahmkshatriya** [comment]
> Not outside the black thing

Please elaborate on the black thing

**Comment by Bungeexgum** [comment]
> > Not outside the black thing
> 
> Please elaborate on the black thing

That black in the corner, i searched it on Google i know what it's called now, it's black bar, every video has that but especially for old anime/movie it's big the aspect ratio look at that skip +85 it's perfect. It's outside in the video he is in black bar, but that's okay because it feels like it should place there. But for the Anime/EP title they're in black bar, Look at "Episode 1" and then the word "Case Clo" they're in the black bar, doesn't feel right, it doesn't feel okay. So I suggest use old anime like detective conan or One Piece EP 1, to adjust them. Anyway I noticed the word. "Case Closed" look like this ___________________ it is long. Takes too much space, unlike mine "Case Closed" not too long right??  And for EP title make it Thin like Anime Title but the white colour of the EP Title stays so they will not look the same because Anime Title colour is Gray or not too white.

**Comment by brahmkshatriya** [comment]
That's not possible to do(without doing it the hacky way), because the way how exoplayer works, Also I dislike the idea of making the title limited to sidebar, because the title and video are 2 seperate layer
I did implement making the title font thin.
