### ISSUE TITLE
Source error 

### ISSUE THREAD

**Issue by Obinash69** [saikou-app/saikou#384]
### Summary

Any video i play gets playback error or source error 

### Reproduction Steps

Every other video gets this error 
![Screenshot_2022-09-11-19-01-31-45_8fdea02c47a76e0fe7eccbf0ee9f2748](https://user-images.githubusercontent.com/93205547/189530520-738c918a-1779-47a5-bb76-577111be0e2d.jpg)

### Expected Result

Expecting to watch a episode after long day of work 

### Actual Result

Not been able to watch 

### Device Information

1.2.0.19
Realme x7 5g

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
provide source and anime being watched
