### ISSUE TITLE
Saikou issue

### ISSUE THREAD

**Issue by Colorstips** [saikou-app/saikou#385]
### Summary

Unread feature in manga and anime this gave your app a great blast

### The Problem

Unread feature manga and anime

### The Ideal Solution

To currently to this feature give app mega blast and people attraction

### The Current Solution

To currently to this feature give app mega blast and people attraction

### Additional Context

And webtoon mode and clear picture server loading error and quality opt.. Manga & Anime

**Comment by Colorstips** [comment]
I"hope this give the app big appluse

**Comment by brahmkshatriya** [comment]
are you logged in with anilist?
delete the manga from your list, it will be marked as unread
are you even on latest beta?
