### ISSUE TITLE
Only recommend manga and anime not in my list

### ISSUE THREAD

**Issue by pavonismc** [saikou-app/saikou#389]
### Summary

That recommended area should only show anime and manga not in my list

### The Problem

When you been recommended something ideally you want to be recommended things you haven't heard of. that means when it's in your list it obviously means you've heard of it, so it shouldn't be recommended for you

### The Ideal Solution

Only recommend anime and manga not found in whatever persons list

**Comment by brahmkshatriya** [comment]
that is handled by anilist,
& Anilist recommends shows if they are not watched yet
