### ISSUE TITLE
Manga buddy source doesn't work...

### ISSUE THREAD

**Issue by ITADORI-15** [saikou-app/saikou#40]
![Screenshot_20220204-002236_Saikou.jpg](https://user-images.githubusercontent.com/83289685/152409652-13b90f7e-52ac-484b-bcc9-992b3af9f207.jpg)

**Comment by brahmkshatriya** [comment]
Click wrong title.

![image](https://user-images.githubusercontent.com/69040506/152409879-aff7ae29-3ab4-48e9-a671-b972fe513056.png)

**Comment by ITADORI-15** [comment]
Thank you
