### ISSUE TITLE
Very Small Change to search feature

### ISSUE THREAD

**Issue by Killermaschine88** [saikou-app/saikou#400]
### Summary

Auto open Keyboard when openning the search window

### The Problem

Basically very small quality of life to automatically open the keyboard when openning the page where u can search for manga / anime (can be a setting to toggle)

### The Ideal Solution

.

**Comment by scrazzz** [comment]
It does this already? Maybe it's an issue with specific devices.


https://user-images.githubusercontent.com/70033559/192083411-efe4740f-a4ff-45cb-b561-a6287d12a01f.mp4

**Comment by Killermaschine88** [comment]
hmm doesnt on my Huawei P40 Lite

**Comment by Shemar890** [comment]
![Screenshot_20220924-173843_Saikou .jpg](https://user-images.githubusercontent.com/106935450/192121038-4a353c2b-bb0f-42f0-86bc-386ec79b215f.jpg)

**Comment by Shemar890** [comment]
Need fix loading problems
