### ISSUE TITLE
Manga image doesn't get saved

### ISSUE THREAD

**Issue by scrazzz** [saikou-app/saikou#404]
### Summary

The "Save" button when long pressing a manga image does not save the image.

### Reproduction Steps

1. Open any manga
2. Long press a page
3. Click save

### Expected Result

Manga image gets downloaded.

### Actual Result

Manga image doesn't get downloaded, it just allows me to view the image on another app.

### Device Information

Saikou Version: 1.2.0.20

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
The issue is that I didn't give storage access. The app should show a pop-up to allow storage access if the app doesn't have it in this case.

**Comment by bxxbfvck** [comment]
Ok, looks like the image did get downloaded without storage perms but my gallery app didn't pick up on it.

**Comment by scrazzz** [comment]
> Ok, looks like the image did get downloaded without storage perms but my gallery app didn't pick up on it.

Yeah same here, I just found out that recently
