### ISSUE TITLE
Single Cover request

### ISSUE THREAD

**Issue by Fireboy6** [saikou-app/saikou#41]
This is very cool moving Cover feature i wanted to see it properly, i wonder what it looks like. Can this be the main Cover?

![Screenshot_2022-03-06-13-14-41-32](https://user-images.githubusercontent.com/75554729/156910290-cce769ff-859e-49bc-a91f-b206a72cb212.png)

**Comment by brahmkshatriya** [comment]
You can long click the banner to see the full image
