### ISSUE TITLE
Search Error & Watching show not showing 

### ISSUE THREAD

**Issue by killerlearner** [saikou-app/saikou#410]
### Summary

Manga search problem and currently watching/reading shows not showing in continue watching/reading list. 

### Reproduction Steps

Just search "the beginning after the end" in manga reader page and you will see blank result while that manga is available in every server site! 
And currently watching/reading anime and manga not updating in continue watching/reading home page. 
So plss solve the watching/reading issue first. 

### Expected Result

When search the manga it should be in result as it is available in server. 
And watching list should be updating after i close watching a anime/manga. 

### Actual Result

Not showing

### Device Information

Saikou Version: 1.2.0.22
Device: Redmi begonia
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Adolar0042** [comment]
Saikou gets its anime information from anilist, and afaik they don't have the beginning after the end, because it is an english original. You can still watch it with "wrong title?", but tracking is done with anilist

**Comment by Adolar0042** [comment]
![image0-1.jpg](https://user-images.githubusercontent.com/39769465/192695355-fd29ac41-8428-4a9c-b265-45819bcb042f.jpg)
From Rhemat#2215 on the Saikou discord

**Comment by killerlearner** [comment]
> Saikou gets its anime information from anilist, and afaik they don't have the beginning after the end, because it is an english original. You can still watch it with "wrong title?", but tracking is done with anilist

Ohh k then can you please tell me title using which i can watch

**Comment by Adolar0042** [comment]
Just go to any manga, choose the source you want, click "Wrong Title?" search for the beginning after the end, select it and then you should be able to start reading
