### ISSUE TITLE
Saikou Beta App

### ISSUE THREAD

**Issue by TheGoldenSun** [saikou-app/saikou#412]
### Summary

Saikou's Notification, Discord rpc, Manga extensions,

### The Problem

Hi Saikou Team,

Your app is amazing I love it very much however there has been an issue where I wish to be notified mobily through your saikou beta app just in case if any anime or manga stories is released or aired. 

### The Ideal Solution

There should be some changes within saikou beta app since it would be suitable for saikou users to notice the notification for when both anime and manga stories will be released or aired.

### The Current Solution

Would be it be possible to add more manga extensions besides the main ones you had added within saikou beta app because as you stated some of them doesn't work which is true because their website usually updates their extension version into a new stable version.

### Additional Context

![184505472-e8e5d740-e3f9-47a5-8279-4025f125efb0](https://user-images.githubusercontent.com/104534608/193224938-7dd084ea-c101-4b50-b9b6-fc7c53a18922.png)

I have a suggestion that may change your opinion about this but, saikou beta users, would adding discord rpc allow saikou beta users know other people what kind of anime or manga are they reading benefit any difference between anime shows or manga stories?

**Comment by scrazzz** [comment]
> I wish to be notified mobily through your saikou beta app just in case if any anime or manga stories is released or aired.

#60

> Would be it be possible to add more manga extensions besides the main ones you had added

Sure, open a new feature request requesting to add a source. Make sure that source has not been requested already. 

I did not understand what you said regarding discord rich presence. If you're asking to add an option for Discord Rich Presence in Saikou, then no, it's simply not feasible to add it on a mobile app.

**Comment by Adolar0042** [comment]
I think a few of the most expensive Samsung phones have a collab with discord that allows them, and only them, to display mobile rpc, maybe he meant that

**Comment by scrazzz** [comment]
Keep in mind that issues should only be opened for a specific thing. However, GitHub discussions is a good place to ask these questions.
