### ISSUE TITLE
Saikou Beta gives CertPathValidatorException Black Screen on WSA

### ISSUE THREAD

**Issue by xidsyed** [saikou-app/saikou#419]
### Summary

Trying to run Saikou on WSA gives 

### Reproduction Steps

- Install Saikou onto Windows Subsystem for Android (my version : 2208.40000.5.0). Installs successfully
- Open Saikou Beta
- After the splash screen following toast message shows up on screen
![image](https://user-images.githubusercontent.com/26184016/194726402-d52c25e3-1b3d-45ff-9341-beaeb3d96fca.png)
- Then all you see is the black screen.

### Expected Result

Expect for saikou to load the homepage

### Actual Result

Error : CertPathValidatorException : trust anchor for certification path not found

### Device Information

Saikou Version 1.2.0.22
Windows Subsystem for Android 2208.40000.5.0
Windows 11 22h2 (22621.608)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by xidsyed** [comment]
I know this might not be on your priority list, but honestly i feel this would make saikou infinitely more useful for most people, their dedicated android app to work on both their phone and laptop/pc, so they can pick up where they left off on their laptop🤯🤯🤯.

WSA is surprisingly fast and light

**Comment by brahmkshatriya** [comment]
Your problem something related to your was installation, Its working completely fine for me on wsa

**Comment by brahmkshatriya** [comment]
> I know this might not be on your priority list, but honestly i feel this would make saikou infinitely more useful for most people, their dedicated android app to work on both their phone and laptop/pc, so they can pick up where they left off on their laptop🤯🤯🤯.
> 
> WSA is surprisingly fast and light

I did think of making this work, but it's very hacky so uh yea, didn't implement

**Comment by Adolar0042** [comment]
Works for me with same Windows 11 Build and WSA version, maybe try reinstalling WSA

**Comment by xidsyed** [comment]
> Your problem is something related to your wsa installation, Its working completely fine for me on wsa

oh. Since i live outside the US i simply download it from https://store.rg-adguard.net/ and downloaded WSA Pacman, and installed Saikou apk. Every other app ive tried works (the ones that dont require google play services) eg:  newpipe, droidify.

**Comment by xidsyed** [comment]
![image](https://user-images.githubusercontent.com/26184016/194744225-feea84b5-152c-485f-b668-44bf8cbbf399.png)
is there perhaps anyway to install certificates manually?

**Comment by xidsyed** [comment]
> Works for me with same Windows 11 Build and WSA version, maybe try reinstalling WSA

Tried it. Didn't Work 😔. How did you install it.

**Comment by Adolar0042** [comment]
> > Works for me with same Windows 11 Build and WSA version, maybe try reinstalling WSA
> 
> Tried it. Didn't Work 😔. How did you install it. Actually, I just received this error on my mobile app as well. even though the app works perfectly well. I dont know whats causing it
> 

Its likely that ut doesn't work, becaus eyou didn't install it from the microsoft store. It has been availabe globally for a while now, so you should be able to install it trough the ms store

**Comment by xidsyed** [comment]
Nevermind, my college blocks most sites, and the WSA traffic was not going through the VPN installed on my laptop. Works like a charm @brahmkshatriya Youre an artist. I wish i can become a developer as good as you. btw are you maintining this app all by yourself? or do you accept contributions

**Comment by brahmkshatriya** [comment]
> Nevermind, my college blocks most sites, and the WSA traffic was not going through the VPN installed on my laptop. Works like a charm @brahmkshatriya Youre an artist. I wish i can become a developer as good as you. btw are you maintining this app all by yourself? or do you accept contributions
> 

Thank you, Been on a break for a while, and yes all contributions are appreciated

**Comment by xidsyed** [comment]
Works pretty well for me, did you try the version that i am trying? It's not bloat, it isnt pre installed. When running in the background it consumes 0 cpu or gpu
