### ISSUE TITLE
'Wrong Title?' feature not working on most sources. 

### ISSUE THREAD

**Issue by xXAceNoob** [saikou-app/saikou#422]
### Summary

I was trying to watch MONSTER but 'Wrong Title?' could not locate the anime. The only souces that worked correctly are Gogo and 9Anime (including the backup), the rest do not show MONSTER but other anime that do not even have the word MOSTER in their title. 

### Reproduction Steps

Tapped on 'Wrong Title?' to select the correct anime. 

### Expected Result

To show the anime that's searched for and replace the automatically found anime. 

### Actual Result

Shows other anime but not the one that was searched for. 

### Device Information

Saikou Version: 1.2.0.22
Brand: Samsung
Architecture: aarch62
Android Version: 11

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
How is this a bug? Some sources don't have it and we can't do anything about it.

> The only souces that worked correctly are Gogo and 9Anime

Then I get that there is no issues here?
