### ISSUE TITLE
mangareader crashes when loading large images

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#427]
### Summary

mangareader crashes when loading large images

### Reproduction Steps

load manga which has few, but larger pages

### Expected Result

load page

### Actual Result

crash

### Device Information

Saikou Version: 1.2.0.22
Device: samsung gtexswifi
Architecture: arm
OS Version: REL 5.1.1 (22)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Can you specify your hardware specs?
I think this is most likely a low ram issue

And i don't think it can be solved, best advice would be to get a better mobile

Saikou does use subsampling, which potentially reduces the image buffer on ram, but it seems like your device can't even handle that

**Comment by scrazzz** [comment]
Dude's running Android 5 in 2022.
