### ISSUE TITLE
Source Suggestions

### ISSUE THREAD

**Issue by Maddyhf** [saikou-app/saikou#43]
Please add animepahe https://animepahe.com/

**Comment by shiiii6** [comment]
https://muchohentai.com/

**Comment by brahmkshatriya** [comment]
> Please add animepahe https://animepahe.com/

planned

**Comment by brahmkshatriya** [comment]
> https://muchohentai.com/

won't be added, due to hentai not being series-ified.

**Comment by Maddyhf** [comment]
Also, is there an option to hide hentai providers?

**Comment by brahmkshatriya** [comment]
> Also, is there an option to hide hentai providers?

It doesnt show hentai providers if the show isnt hentai

To hide hentai shows, turn off 18+ content on your anilist settings
