### ISSUE TITLE
cbz  on download

### ISSUE THREAD

**Issue by MaiSan9999** [saikou-app/saikou#432]
### Summary

lazy asf

### The Problem

lazy asf

### The Ideal Solution

lazy asf

### The Current Solution

lazy asf

### Additional Context

lazy asf

**Comment by xwaay12** [comment]
lol

**Comment by scrazzz** [comment]
Please follow the issue template :trollface:

**Comment by MaiSan9999** [comment]
> Please follow the issue template :trollface:

Lazy :l
