### ISSUE TITLE
App freezing after Closing StudioActivity, before it is able to load info

### ISSUE THREAD

**Issue by Marco-9456** [saikou-app/saikou#436]
### Summary

The app freezes 

### Reproduction Steps

1. Open Saikou
2. Go to a random show
3. Click on INFO
4. Click on Studio
5. Before it finishes loading the studio work go quickly back
6. The app will freeze

Here is a Screen record to better understand what is happening:[GDrive](https://drive.google.com/file/d/1FBgXv_IUUm2178IEehJc3jbXlMkaAbo7/view?usp=drivesdk) 

### Expected Result

To show the studio work

### Actual Result

Instant crash after going back before it finishes loading info

### Device Information

Saikou Version: 1.2.0.22
Device: samsung t2s
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

To get the app working after this happens:
1. Force stop the app
2. Clear cache
3. Switch Airplane mode on
4. Switch it of
5. The app should work after this

**Comment by brahmkshatriya** [comment]
Can reproduce 👍

**Comment by Marco-9456** [comment]
> Can reproduce 👍

👍

**Comment by Shemar890** [comment]
> Can reproduce 👍

Fix 9anime and 9anime backup

**Comment by SunglassJerry** [comment]
> Fix 9anime and 9anime backup

Even if they do, 9animes will destroy it again. And 9anime backup doesn't even exist. Idk why Shivam still keeps it there
