### ISSUE TITLE
Playback speed 

### ISSUE THREAD

**Issue by henrique2222** [saikou-app/saikou#437]
### Summary

More playback speed options

### The Problem

The first slowed playback speed option is 0.75x, It makes the sound a bit off.

### The Ideal Solution

If you guys could add 0.85x it would be great.

**Comment by brahmkshatriya** [comment]
Not gonna implement it

If you want to add it

https://github.com/saikou-app/saikou/blob/main/app/src/main/java/ani/saikou/anime/ExoplayerView.kt#L896

Just change one of the speed in his line,
Compile the app, and you will have your desired speed there
