### ISSUE TITLE
Filter button looks weird

### ISSUE THREAD

**Issue by Marco-9456** [saikou-app/saikou#438]
### Summary

Filter button looks weird in light mode

### Reproduction Steps

Go to Anime or Manga search

### Expected Result

To not look gray i guess

<details markdown='1'><summary> Show Screenshot </summary>

![Screenshot_20221027-212523_Saikou ](https://user-images.githubusercontent.com/41828058/198381239-2a2ebadb-bf14-4406-a8b3-8055eea732ab.jpg)

### Actual Result

<details markdown='1'><summary> Show Screenshot </summary>

![Screenshot_20221027-211019_Saikou ](https://user-images.githubusercontent.com/41828058/198381273-893955e6-bdbf-44de-8230-78cd9a200dcd.jpg)

### Device Information

Saikou Version: 1.2.0.23
Device: samsung t2s
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
That's just me being lazy 👍

**Comment by Marco-9456** [comment]
> That's just me being lazy 👍

😂😂

**Comment by Marco-9456** [comment]
🎉🎉 finally
