### ISSUE TITLE
Wrong manga found in source

### ISSUE THREAD

**Issue by AyanoYuugiri** [saikou-app/saikou#441]
### Summary

Wrong manga found in source

### Reproduction Steps

1. Search for "MagiRevo" in anime.
2. Open the result named "Tensei Oujo to Tensai Reijo no Mahou Kakumei"
3. Open the relations of manga.
4. Try read it through source named "MANGAPILL"

### Expected Result

Found the correct manga like what Tachiyomi does.
![Screenshot_20221029-191434](https://user-images.githubusercontent.com/111672613/198828290-5f5e9806-bb3d-443e-94b3-09bd29e70bd4.png)

### Actual Result

Found the wrong manga.
![Screenshot_20221029-191106](https://user-images.githubusercontent.com/111672613/198828243-2e848e15-c5f3-44e5-83c7-802e9d7693b2.png)

### Device Information

Saikou Version: 1.2.0.23
Device: lge alphalm
Architecture: aarch64
OS Version: REL 10 (29)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Marco-9456** [comment]
I just checked,
MANGAPILL doesn't have a manga called `Tensei Oujo to Tensai Reijou no Mahou Kakumei` so maybe try with another source
Also if you click wrong title and it didn't find it, that means that the source doesn't have it.

**Comment by AyanoYuugiri** [comment]
> @AyanoYuugiri 
> I just checked,
> MANGAPILL doesn't have a manga called `Tensei Oujo to Tensai Reijou no Mahou Kakumei` so maybe try with another source
> Also if you click wrong title and it didn't find it, that means that the source doesn't have it.

ah my fault
