### ISSUE TITLE
Mal Error

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#443]
### Summary

Error reading MAL

### Reproduction Steps

Whenever I reload there's a bug which I can't see my list and even the recommended anime and manga.

### Expected Result

I will be able to reload again normally without any casualties .

### Actual Result

Fix a Anime list error

### Device Information

Saikou version 1.2.0.23
Vivo 1606 
1.4GHz Snapdragon 425 Quad-core
Android: 6.0.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![Screenshot_20221101_022218](https://user-images.githubusercontent.com/107057902/199082593-be6279e2-f142-4ac9-8f1f-e520d9e4b902.jpg)

**Comment by brahmkshatriya** [comment]
Anilist was most likely overloaded at that time, try again later
