### ISSUE TITLE
Hide or import manga

### ISSUE THREAD

**Issue by Lukerator** [saikou-app/saikou#446]
### Summary

Be able to hide manga from app or import from Tachiyomi

### The Problem

I use Tachiyomi and my manga library is mostly there, so I don't really use this app for manga

### The Ideal Solution

Be able to either import manga from Tachiyomi or hide manga from home and category bar, whichever is easier for the developers

### The Current Solution

None

**Comment by Jjjggh** [comment]
U can hide the "continue manga" section from home already
