### ISSUE TITLE
can't connect to anilist

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#447]
### Summary

can't connect to anilist

### Reproduction Steps

open the app

### Expected Result

load

### Actual Result

gives error of Seems like Anilist is down, maybe try using a VPN or you can wait for it to comeback.

### Device Information

Saikou Version: 1.2.0.23
Device: samsung gtexswifi
Architecture: arm
OS Version: REL 5.1.1 (22)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

if if i visit anilist in the browser it works fine.

**Comment by Adolar0042** [comment]
anilist seems to be having hardware problems right now, so sit tight until they fix their problems

**Comment by Shemar890** [comment]
> anilist seems to be having hardware problems right now, so sit tight until they fix their problems

Anilist is Down and try VPN on my phone but it still now letting me inside don't know why

**Comment by Jjjggh** [comment]
It's fixed now
