### ISSUE TITLE
Hide Manga for anime you've already watched and vice versa

### ISSUE THREAD

**Issue by Meiloorun** [saikou-app/saikou#448]
### Summary

Hide Manga or Anime if you have seen it in another format.

### The Problem

It's annoying going through the manga tab where the main manga that is on there is all anime that I have already watched previously. it's also annoying going through the anime tab and seeing series that I've already seen the manga for. It makes it harder to find new manga/anime that you haven't seen before.

### The Ideal Solution

Have an option to hide the manga that you've already seen the anime for and hide the anime that you've already read the manga for. 

In addition this, if you wanted to read the manga for an anime because the manga is ahead of the anime then there should also be a sub option so that the manga shouldn't be hidden and vice versa.

All of this would probably be implemented by looking through the related anime/manga and hiding the ones that are marked as Source and Adaptation. Don't hide alternatives, side-story etc. If the source is continuing but the adaptation is finished then the source shouldn't be hidden.

### Additional Context

I love this app.

**Comment by SunglassJerry** [comment]
I don't think that's ever gonna be implemented. The Dev doesn't even implement things he promised to. Guess what now he has 5 times the donation goal.

**Comment by brahmkshatriya** [comment]
Yea sorry this is way too of a specific feature to add

What it requires the app to do is check relations of every media, and if those media are already watched/read or not
This would be way too memory consuming & make the app slower

A better alternative would be to just add the manga/anime that you dont want to read to "dropped", "finished"  or "planned"
& turn off the "include list" button on the page/ "list only" in search
