### ISSUE TITLE
Real continue (continue watching from where you're really at)

### ISSUE THREAD

**Issue by Jjjggh** [saikou-app/saikou#449]
### Summary

The continue watching feature doesn't keep up with the list updates 

### The Problem

When you update your list outside of the without watching the specific anime that you already update on the app
Then go back to the app and try to "continue watching "
It'll start at the same spot where you left - wich isn't bad - but that episode is already marked as watched so dont need to re watch it

Uploading Screen_Recording_20221106_170426_Saikou .mp4…

### The Ideal Solution

Maybe add an option to not "continue watching " an already marked as watched episode or you can give the option for selected to not go directly to the link and make the user choose or to ask the user something like this "this episode is already watched, do you want to go to the first unwatched episode " or something 

Hope it's not too much trouble

**Comment by Jjjggh** [comment]
https://user-images.githubusercontent.com/102470504/200175968-d79aa958-7eaf-49a6-a041-7bfa0dc901ca.mp4

**Comment by brahmkshatriya** [comment]
I failing to understand what you mean

**Comment by Adolar0042** [comment]
I think he meant that "continue watching" starts the last marked watched episode instead of the one after that, that wasn't watched yet

**Comment by Jjjggh** [comment]
> I am failing to understand what you mean

It continues from the last episode i started (on the app) even though i updated my list and watched (this specific episode or even several episodes after ) on anilist before going to the app and clicking continue watching 


The solution i can think of is that if the last episode i was in -the last point that i watched through the app- is marked is watched the app goes to the next unwatched episode
