### ISSUE TITLE
Little change request

### ISSUE THREAD

**Issue by Bungeexgum** [saikou-app/saikou#45]
What do you think of this sir,? Wouldn't it look good if they were move there? Because i don't think they're fit in the info. I believe Genre, Synopsis, and The Cast of Character are fit there. And of course when the Related or Recommended is selected the white colour will change into Saikou Colour.

![IMG_20220205_134427](https://user-images.githubusercontent.com/88455631/152631232-fdf5e3a5-c078-4f95-8e84-ef584fccf485.jpg)

This is how the info would look like, how's that?

![Picsart_22-02-05_14-05-47-756](https://user-images.githubusercontent.com/88455631/152631316-53647949-8fcb-452b-9633-19df44793439.png)

I worked hard to cropped them and Collage.

![IMG_20220205_142126](https://user-images.githubusercontent.com/88455631/152631624-2c065db9-4dde-4c64-a120-67038a902d90.jpg)

**Comment by brahmkshatriya** [comment]
Won't happen.
