### ISSUE TITLE
Soft subs are broken

### ISSUE THREAD

**Issue by Vortex786** [saikou-app/saikou#450]
### Summary

Soft subs dont appear correctly when two or more people speaking

### Reproduction Steps

Idk

### Expected Result

Soft subs one at bottom one at top.

### Actual Result

Soft subs either missing one dialouge (kamyroll) or overlapping (Zoro 

### Device Information

Saikou Version: 1.2.0.23
Device: motorola nicklaus_f
Architecture: arm
OS Version: REL 7.1.1 (25)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Not fixable by us, all you can do is change the subtitle size
would need to switch to subtitle provider
