### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Maniac-Mit** [saikou-app/saikou#451]
### Summary

Keep showing "Error data loading"

### Reproduction Steps

![Screenshot_20221111-233554](https://user-images.githubusercontent.com/103870652/201402080-73fab5db-dd99-4716-a844-14c7a1932e11.jpg)
 This is showing 
When opening the app
I uninstalled it and re installed it again

### Expected Result

Fixing it would be great

### Actual Result

Dont know why is this happening 

### Device Information

The isn't opening..
Black screen is showing 

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Adolar0042** [comment]
Anilist is having problems right now, wait for anilist to be back to normal
