### ISSUE TITLE
Error downloading data

### ISSUE THREAD

**Issue by assassinsandrew** [saikou-app/saikou#452]
### Summary

Not able to search anime and not able to continue watching anime 

### Reproduction Steps

I tried rebooting but didn't work 

### Expected Result

To stop showing error 

### Actual Result

It didn't stop show error 

### Device Information

Brand: vivo 

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by xwaay12** [comment]
this is happening becuase the anilist api is not working right now

**Comment by assassinsandrew** [comment]
When will it work

**Comment by Shemar890** [comment]
Went it gonna work then

**Comment by scrazzz** [comment]
Not an issue with Saikou itself.

**Comment by assassinsandrew** [comment]
But do you when it will work?
