### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#453]
### Summary

I can't see my anilist list

### Reproduction Steps

![Screenshot_20221112_214517](https://user-images.githubusercontent.com/107057902/201477040-49d6d470-120a-42ef-92b4-f7f8c89abdeb.jpg)

### Expected Result

I will be able to watch again anime

### Actual Result

Fix the anilist server error 

### Device Information

Saikou version 1.2.0.23
Vivo 1606 
1.4GHz Snapdragon 425 Quad-core
Android: 6.0.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![Screenshot_20221112_211504](https://user-images.githubusercontent.com/107057902/201477091-9da5b908-f2c5-409c-951b-e4c9a759b51a.jpg)

**Comment by Shemar890** [comment]
Went it gonna back online

**Comment by ArijitKHaldar** [comment]
This is happening for nearly two weeks on my device. Randomly starts working again sometimes, but this exact issue comes up every now and then..Happens on both WiFi and mobile data with all the DNS servers available...

**Comment by Nevenon** [comment]
Same

**Comment by CoinSpyre** [comment]
Exact same problem.

**Comment by piyush-panpaliya** [comment]
yup getting the same issue from past 2 days

**Comment by Shemar890** [comment]
Need to  fix now

**Comment by scrazzz** [comment]
Duplicate for #451 and #452. 

I'm going to keep this issue open because people still don't follow the checklist when making new issues. 

![image](https://user-images.githubusercontent.com/70033559/201484426-7a4a7faa-af84-4ad6-bd9f-1c5570357117.png)

**Comment by Shemar890** [comment]
![Screenshot_20221112-043450_Saikou.jpg](https://user-images.githubusercontent.com/106935450/201484442-4db8d597-c587-4cb0-8998-3e5e2db83d17.jpg)

**Comment by Nevenon** [comment]
This is really a bad situation because I'm not the only one who experience this problem.

**Comment by Ptachv** [comment]
Same for me
![Screenshot_2022-11-13-12-22-51-66_8fdea02c47a76e0fe7eccbf0ee9f2748](https://user-images.githubusercontent.com/118108643/201519223-aa770c47-2dc8-4d9d-bb08-3217c77971ff.jpg)

**Comment by fal3n-4ngel** [comment]
> 

I think it's an Api level issue since only the data fetching is facing the error, we can still stream the videos of the ones in the homescreen
Ig Maybe Anilist modified their api or something

**Comment by CoinSpyre** [comment]
> > 
> 
> I think it's an Api level issue since only the data fetching is facing the error, we can still stream the videos of the ones in the homescreen Ig Maybe Anilist modified their api or something

Yes scrazzz confirmed it in a previous post.  it's an Api issue on anilist.
They have mostly disabled their Api due to so.e traffic issues they are facing.

**Comment by beyond9thousand** [comment]
Damn, so is this permanently dead now?

**Comment by fal3n-4ngel** [comment]
I am try to create a fork and use myanimelist instead of anilist, but too much work and too lazy

**Comment by InsaneHunterr** [comment]
> I am trying to create a fork and use myanimelist instead of anilist, but too much work and too lazy

Can we use myanimelist account for saikou ?

**Comment by CoinSpyre** [comment]
> > I am trying to create a fork and use myanimelist instead of anilist, but too much work and too lazy
> 
> Can we use myanimelist account for saikou ?

Lol probably not. IndaneHunter stated that they wanted to fork the project and make a MAL integrated version. But also said it was to much work and that they are too lazy.
So I wouldn't get your hopes up.

**Comment by fal3n-4ngel** [comment]
Exactly Anilist api is better for this ig. Not much experience with mal api , but yeah imma try .
Got no other work.

**Comment by CoinSpyre** [comment]
> > > Exactly Anilist api is better for this ig. Not much experience with mal api , but yeah imma try . Got no other work.
> > > Also who is IdaneHunterr?
> > 
> > 
> > Lol Typo.. InsaneHunter
> 
> Who dat? Give his id or something

Probably no one lol I am just waking up and probably misread something...

**Comment by fal3n-4ngel** [comment]
Bruh..., And yes this ain't reddit so we should stop

**Comment by Shemar890** [comment]
Anilist api need to fix very annoying 😒

**Comment by Hekel1989** [comment]
> ![Screenshot_20221112-093032](https://user-images.githubusercontent.com/95498903/201481477-d075e00c-5a17-4f82-b142-3da0f2f0e3e5.png)
> 
> Exact same problem as the first post. But I also get the message Empty response, does your internet connection perhaps suck. It's not my internet connection. Refreshing the app multiple times reproduces the error message in the first post.

I get the exact same issue as this one, I just came to report it, and I found it mentioned here.

For context, 
Android 13
Pixel 7 Pro

**Comment by Nevenon** [comment]
Hello guys I think The anilist server is Back I just got in and it's all good again
![Screenshot_20221117_151331](https://user-images.githubusercontent.com/107057902/202380421-e6ab9657-e510-4729-8822-dd7e3f936cb1.jpg)

**Comment by Nevenon** [comment]
The time has come.

**Comment by Shemar890** [comment]
> The time has come. 

Fix allanime and 9anime zoro

**Comment by V1per77** [comment]
![Screenshot_2023-05-27-09-30-27-536_ani.saikou.jpg](https://github.com/saikou-app/saikou/assets/134309967/4e49a34d-d4c1-480f-936c-f00d74555417)

![Screenshot_2023-05-27-09-30-19-257_ani.saikou.jpg](https://github.com/saikou-app/saikou/assets/134309967/ca4486b9-badc-46db-a404-42eed8bb31c4)

I was Having This Problem Since Yesterday there Other Server Is Not Showing And its annoying The STREAMSB is Error 😕😕
