### ISSUE TITLE
Mangahub

### ISSUE THREAD

**Issue by BlackSmoke100** [saikou-app/saikou#454]
### Summary

I cant see any chapter from mangahub

### Reproduction Steps

I just use mangahub and click a manga

### Expected Result

That i can see a better chapter

### Actual Result

Couldn't find any chapter

### Device Information

Saikou Version: 1.2.0.23
Device: vivo 1817
Architecture: aarch64
OS Version: REL 8.1.0 (27)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Please make it better I was looking forward to this app because there's no mangahub in tachiyomi but there's mangahub here so please fix it

**Comment by Searchcat37** [comment]
What manga were you looking for?

**Comment by brahmkshatriya** [comment]
Yea they changed their whole site, 
They are using graphql now, and search has some encryption added to it
And honestly I dont have time to do it rn

If someone is free, please try going their encryption

**Comment by scrazzz** [comment]
Mangahub has CloudFlare protection + their own `x-mghub-access` token headers protection on their graphql API. Other apps like tachiyomi and kotatsu don't have this source. So I don't think it's possible at the moment.
