### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by NeoS4ma** [saikou-app/saikou#456]
### Summary

I'm trying to watch or search animes but everytime i get Infinite loading screen with a message "empty response, perhaps your internet sucks ?"

### Reproduction Steps

I tried watching animes or searching

### Expected Result

Being able to watch anime

### Actual Result

I'm getting an Infinite loading screen with a message saying "empty response, perhaps your internet sucks ?" 

### Device Information

Saikou Version: 1.2.0.23
Device: Redmi sunny
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Pj551** [comment]
I have a same issue when open the app it 'Empty Response, Does your
internet perhaps suck?'
I can't watch anime it show loading screen.
Please fix the empty response problem

**Comment by Adolar0042** [comment]
We can't fix it, as it isn't a problem on our end, anilist is currently experiencing technical difficulties which caused them to shut down their API which we use to get information of the different manga/ anime
