### ISSUE TITLE
Option to remove anime/manga from recommended section

### ISSUE THREAD

**Issue by itsgoretime** [saikou-app/saikou#458]
### Summary

Option to remove anime/manga from recommended section

### The Problem

Being able to get different recommendations (personally I have 2 anime im not intrested in as recommended for whole time)

### The Ideal Solution

Long hold > mark as hidden/non intrested

### The Current Solution

none

**Comment by brahmkshatriya** [comment]
Long hold the anime in the section, mark it as dropped or planned
I am not planning to add this
