### ISSUE TITLE
Auto skip not working on bluestacks

### ISSUE THREAD

**Issue by fifomicas** [saikou-app/saikou#466]
### Summary

Says "handshake failed" every episode and auto skip doesn't work

### Reproduction Steps

I use bluestacks on my computer to watch anime and it always says "handshake failed" and auto skip doesn't work.
That's it

### Expected Result

I was hoping it would work like on my phone and auto skip without the handshake failed thing.

### Actual Result

"Handshake failed" at every episode and no auto skip function.

### Device Information

Saikou version: 1.2.0.23
BlueStacks version: 5

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by xwaay12** [comment]
try clearing app cache 
try a dns or vpn

**Comment by xwaay12** [comment]
if this doesn't work its just a general issue some people are facing it too

**Comment by fifomicas** [comment]
> try clearing app cache try a dns or vpn

I did both but i still have the same issues

**Comment by Rohan-511** [comment]
For some reason I'm facing the sam thing in both of my Android devices

**Comment by SunglassJerry** [comment]
Ok, so... How do I put it..... It's just that your whole device and location is the issue. You might be getting a "Handshake Failed" error which is somehow related to aniskip(the API they use to get the anime timestamps). And it doesn't get with a VPN. So yea.. No OPED Skip for you 🙏

**Comment by Rohan-511** [comment]
Any way to fix that?

**Comment by Rohan-511** [comment]
> Ok, so... How do I put it..... It's just that your whole device and location is the issue. You might be getting a "Handshake Failed" error which is somehow related to aniskip(the API they use to get the anime timestamps). And it doesn't get with a VPN. So yea.. No OPED Skip for you 🙏

Any way to fix the issue?

**Comment by SunglassJerry** [comment]
There might be one, deep in the woods. But I still couldn't find it. So yea.. I even tried going to different places. Still no fix

**Comment by Faresgmr** [comment]
I'm on android and get the same handshake error
Google DNS doesn't fix it
