### ISSUE TITLE
Mangabuddy

### ISSUE THREAD

**Issue by ITADORI-15** [saikou-app/saikou#47]
![Screenshot_20220205-224716_Saikou.jpg](https://user-images.githubusercontent.com/83289685/152651826-ad2a2f9c-17b6-4532-8d44-7ed4b002b755.jpg)
I also clicked on wrong title it shows this as a result

**Comment by Zeroo097** [comment]
Hey you were in cloudstream too @ITADORI-15

**Comment by ITADORI-15** [comment]
Yep I used to use that for anime .....
I use saikou for manga and anime most of the times nowadays

**Comment by brahmkshatriya** [comment]
They removed the cloudflare check

**Comment by ITADORI-15** [comment]
Thnx bro❤
