### ISSUE TITLE
Disable manga page long press bottom sheet

### ISSUE THREAD

**Issue by rakibdev** [saikou-app/saikou#474]
### Summary

Bad UX

### The Problem

New installed this. Trying to scroll managa pages with with fingers holding and bottom sheet literally getting triggered every few seconds treating as long press.

### The Ideal Solution

Bottom sheet "reload, save, share" are low priority buttons, rarely used. Put these in the transparent topbar 3 dot/setting icon menu. And option to disable this sheet or better completely remove.

### The Current Solution

.

### Additional Context

.

**Comment by scrazzz** [comment]
How about a double-tap on the screen instead of moving it somewhere else or removing it?
