### ISSUE TITLE
To add custom next and previous chapter button

### ISSUE THREAD

**Issue by KunalSucks** [saikou-app/saikou#480]
### Summary

I want that when reading a manga i can customize my next and previous chapter button so that i can put previous chapter button on right side and the other on left

### The Problem

When i read manga i read it from right to left and the previous chapter button is always on left side and next chapter button is always on right side but it is not comfortable for me thats why i want you to add custom side for previous and next chapter button so that i can put my previous chapter button on right and the next chapter on left and also if you can add going to next chapter without button just swipe the side you read manga and read the next or previous chapter. Thanks, I really love saikou app its great 

### The Ideal Solution

I told everything in above lines sorry

**Comment by brahmkshatriya** [comment]
Fork the app, and switch buttons
I wont be adding a specific setting for this
