### ISSUE TITLE
Source not working

### ISSUE THREAD

**Issue by Suriya2127** [saikou-app/saikou#481]
### Summary

Gogoanime,zoro,allanime showing source error or not working only tenshi,kamyroll, Animixplay working properly 

### Reproduction Steps

Nothing 

### Expected Result

Wanting to play the anime

### Actual Result

Source error or not showing any source 

### Device Information

Saikou ver 1.2.0.23
Brand: realme
Os: 10

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
**Gogo**
Only `streamsb` doesn't work, other 2 sources (`visdtreaming` and `xstreamcdn`) works for me.

**Zoro**
Can confirm, `streamsb` source doesn't work.

**AllAnime**
Can confirm, search + episodes doesn't work.

**AnimixPlay**
Yes, the source doesn't work properly if you skip. Not sure why it happens. It has been like that for a long time.

**Comment by Suriya2127** [comment]
Yes other sources for Gogoanime works such as vid stream but some animes only have stream sb link since it's the main source i believe this problem is from website

**Comment by scrazzz** [comment]
Fixed https://github.com/saikou-app/saikou/commit/6c86bb268e8ccd3a7caac006b403b4c576afc94b
