### ISSUE TITLE
Download time in negative

### ISSUE THREAD

**Issue by Faresgmr** [saikou-app/saikou#482]
### Summary

When downloading anime the download time becomes negative

### Reproduction Steps

1. Open app
2. Go to Vinland saga
3. Select tenshi
4. Remove make default so i can download in peace
5. Download 5 eps

### Expected Result

The time left for download time is correct

### Actual Result

![Screenshot_20221220-204824_Brave](https://user-images.githubusercontent.com/63611149/208743807-41f16970-7b6e-4ede-98f6-268386d0efd4.jpg)

### Device Information

Saikou Version: 1.2.0.23
Device: samsung gtaxllte
Architecture: arm
OS Version: REL 8.1.0 (27)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Faresgmr** [comment]
Also 2 of the downloads failed
Episode 1 was the last to finish and the download time was in negative until it was dond

im downloading to SD card not internal storage

Im unsure if these are related

**Comment by SunglassJerry** [comment]
kindly use adm. Join the discord server for more details

**Comment by scrazzz** [comment]
The in-built Download Managers differ on devices. On my device, the time to complete all downloads isn't seen.

Saikou also doesn't send any information about how much time is left for the download to get completed anywhere. So this isn't an issue with this app.

Additionally, I would suggest you to use an external download managers such as 1DM or DownloadNavi.

**Comment by Solovertical** [comment]
> The in-built Download Managers differ on devices. On my device, the time to complete all downloads isn't seen.
> 
> Saikou also doesn't send any information about how much time is left for the download to get completed anywhere. So this isn't an issue with this app.
> 
> Additionally, I would suggest you to use an external download managers such as 1DM or DownloadNavi.

Can you give download link of 1 dm

**Comment by scrazzz** [comment]
> Can you give download link of 1 dm

First result on the PlayStore: https://play.google.com/store/apps/details?id=idm.internet.download.manager
