### ISSUE TITLE
[Source request] https://pactedanime.com

### ISSUE THREAD

**Issue by ImpenetrableNoble** [saikou-app/saikou#485]
### Summary

Pacted anime is a new brand website since the old anime website they created no longer exists

### The Problem

No issues I've seen from this website since alot of people uses this website for anime streaming only however there are still small advertisement going on in that website so I hope some saikou beta users are willing to bare through it.

![Screenshot_20221223_052352](https://user-images.githubusercontent.com/104534608/209320870-d277c44b-6b8f-4be4-86ea-ae70915cabb1.png)

### The Ideal Solution

Well implementing a block against advertisments that comes from https://pactedanime.com/ might be a change of pace just like you did for other anime extensions. 

### The Current Solution

Animepahe, 9animebackup, 9anime should be removed from sailou beta's extension as it doesn't seem to work anymore. 
![Screenshot_20221223_052941](https://user-images.githubusercontent.com/104534608/209320780-31716db3-bdd6-4318-b3f1-b6f9bed6e639.png)
![Screenshot_20221223_052956](https://user-images.githubusercontent.com/104534608/209320784-d523b827-d139-4a8b-974c-8e0dd3d17bce.png)

![Screenshot_20221223_053744](https://user-images.githubusercontent.com/104534608/209321684-5544174c-4af5-49bd-bf17-458fb71107e0.png)

### Additional Context

I hope there would be a huge change going on for saikou beta users soon!

**Comment by CeoOfSleep** [comment]
I would like to add that AnimixPlay should be removed as well since they shutdown the site recently due to problems with their scapper system.

**Comment by Adolar0042** [comment]
AnimixPlay was already removed (9bb1efe)

**Comment by animegamer4422** [comment]
I'd also like to bring the attention towards nyaa as torrents will never be shut
I'm not a dev currently but I'm willing to learn skills in case required to implement something like Miru's torrent streaming into Saikou

**Comment by Adolar0042** [comment]
Torrents, however, directly expose the user to companies searching for breaches of copyright, increasing the risk of fines or whatever the punishment for copyright infringement in their country is.

_On a side note, many ISP's and networks also outright block torrenting from working in the first place._

**Comment by animegamer4422** [comment]
Could we at least have the option though?
Like we can disable it by default but if user needed he can turn it on

**Comment by scrazzz** [comment]
Pactedanime returns the entire episodes in one page. This makes it difficult to segregate and display the appropriate episodes according to each seasons. 
![image](https://user-images.githubusercontent.com/70033559/232274552-7dc39355-c92a-41d5-bb72-d08e6cc6b8b4.png)
