### ISSUE TITLE
New 9anime Extension Source 

### ISSUE THREAD

**Issue by TheGoldenSun** [saikou-app/saikou#488]
### Summary

This brand new 9anime website is the original website that streams both dub english and sub english for any users who's willing to watch anime.

### The Problem

Some of the 9anime websites has been stealing the original brand and creations from the developer's edits they made for their 9anime website, I suggest that saikou beta users and saikou developers should be more aware of this has this has been happening a lot to different anime websites lately. 

### The Ideal Solution

I hope that there wouldn't be anymore infringing issues with 9anime website that's that's now fully updated, maybe an extension can be implemented with a change.

### The Current Solution

There's a bunch of 9anime websites on Google search which I don't trust them to use as they would personally identify any users through advertisments easily.

### Additional Context

Here's the verified website of 9anime, my apologies for not notifying you guys about it:

https://9anime.to/

**Comment by Adolar0042** [comment]
both are correct websites (see https://9anime.me, the proxy list of 9anime, found on the 9anime subreddit)

![image](https://user-images.githubusercontent.com/39769465/209451887-1182073c-a126-4469-83a0-32f3d1eaebd2.png)

**Comment by TheGoldenSun** [comment]
@Adolar0042 The fact that you didn't read 9anime.to as an official domain and not 9anime.me because it only talks about apk mirrors of 9anime and fake websites of 9anime is blasphemous, but alright have it your way.

**Comment by Adolar0042** [comment]
I think you might have misunderstood me. 9anime.me is their official list of proxies (alternate websites). 
> This is the list of 9anime's official domains, [...]

It lists both 9anime.to, which you mentioned as the official site, and 9anime.pl which we currently use, so both are official sites and from the same creator. 

![image](https://user-images.githubusercontent.com/39769465/209452358-1b89bed2-216f-4f9e-88fe-0238ee56c275.png)

**Comment by TheGoldenSun** [comment]
Yes there are alternate websites of 9anime that they created, but it's not
the same official domain like 9anime.to for users who is willing to watch
anime shows or movies from their website, this cannot be confusing.

I think you might have misunderstood me. 9anime.me is their official list

**Comment by Adolar0042** [comment]
I don't really see the problem, both websites work and look the same and are from the same creators. 
It won't be an issue for the user if they get the 9anime.pl link from our readme or the 9anime.to link from somewhere else, as they both work the same way, offer the same content, and don't steal any data.

**Comment by TheGoldenSun** [comment]
There's no issue about it since created it for the sole purpose of 9anime
users just in case if one is slapped with a DMCA takedown they can use
another mirror website created by the same developer, but of now from what
can I tell all of their efforts they put when updating 9anime from their
official domain they created before releasing mirrored websites for all
9anime users is the main domain version not the mirrored domain like the
others they made.


I don't really see the problem, both websites work and look the same and

**Comment by TheGoldenSun** [comment]
I wonder why their Twitter is anime.to now, I'm so interested.

I don't really see the problem, both websites work and look the same and

**Comment by Adolar0042** [comment]
Ooh, I see. 
It is better when site changes take longer, as with each site change the scraper is highly likely to break. Changing to 9anime.to would just decrease the time that the 9anime scraper is working. 
Anyway, I'm not the guy that works/worked on 9anime, so the call whether to change from 9anime.pl to 9anime.to is not up to me, but I think it's unlikely.
