### ISSUE TITLE
Aniskip not working in emulator

### ISSUE THREAD

**Issue by venkat2305** [saikou-app/saikou#492]
### Summary

Aniskip not working in emulator

### Reproduction Steps

In ld9 player emulator. We can see this issue 

### Expected Result

Aniskip segments should appear

### Actual Result

Handshake failed

### Device Information

Latest version
Poco F4
Miui

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
Generally, this app does not support any emulators. So any issue with it should be dealt by yourself.

If you could replicate this issue on your smartphone, then maybe it can be looked into.

**Comment by venkat2305** [comment]
> If you could replicate this issue on your smartphone, then maybe it can be looked into.

It isn't working on my tablet either.

**Comment by venkat2305** [comment]
@brahmkshatriya 
**with proxy off**
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688327-b739e1b9-8c82-4c67-8281-6b3df850f32e.png)
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688351-c42b85c6-cc75-42af-82fb-9b77657e043e.png)

**with proxy on**
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688400-df22fbdd-2011-4886-a6fc-adb82ba44ce7.png)
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688422-5550974e-626e-4f7c-a302-7750e975df73.png)

**Comment by venkat2305** [comment]
**with proxy of**
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688566-bf761d24-f03f-4368-a27a-bef2c230a611.png)
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688580-e556adb1-0bd3-4ab2-a862-529b279887d1.png)

with proxy on
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688624-d353cfe4-68d7-495a-a738-2a50393429b9.png)
![Screenshot (46)](https://user-images.githubusercontent.com/55329452/213688664-f08030b3-04e2-4fa3-96f9-9e810393bd43.png)
@brahmkshatriya

**Comment by venkat2305** [comment]
with proxy off getting handshake failed
![handshakefailed](https://user-images.githubusercontent.com/55329452/213688853-f59a1924-ba12-4572-b6d5-2b76e2eb7d8f.png)

with proxy on, im getting an error.
![error](https://user-images.githubusercontent.com/55329452/213689035-5b1a7059-054b-49ec-b4f4-66c9f1e9dc0b.png)

this is one bluestacks 5 @brahmkshatriya

**Comment by venkat2305** [comment]
Can you check , why am I getting this weird error while using the proxy?
