### ISSUE TITLE
translation into other languages

### ISSUE THREAD

**Issue by daviplutao** [saikou-app/saikou#493]
### Summary

Would it be possible to translate the application's INTERFACE?

### The Problem

I'm **Brazilian** and I love the Seikou app.  But unfortunately I'm only limited to English, and I'm not good at English.  So if you could translate the application's interface into **PORTUGUESE** 🇧🇷 I would be **very happy.** - _only if possible_ 
.
.
I would also like to ask you to put sleeve extensions in **Portuguese**. MangaDex has several manga available in **Portuguese** 🇧🇷, so if possible, do that. I love Saikou, please.

### The Ideal Solution

That you translate the application's interface.

**Comment by brahmkshatriya** [comment]
Sorry, this repo will not contain translated languages
If you want you could refer to these:
- Spanish fork - https://github.com/Diegopyl1209/saikouSP
- Vietnamese fork - https://github.com/hoangvu12/saikou

Portugese fork hasn't been made, you or somebody else fork & can make it!
