### ISSUE TITLE
Recommended Manga on Home Section. 

### ISSUE THREAD

**Issue by Mano5JP** [saikou-app/saikou#50]
Currently it recommends Anime only.

![Screenshot_20220207-201626_Saikou.png](https://user-images.githubusercontent.com/64928088/152838265-01988ed5-7895-4374-ae7d-01e69b600066.png)

We could possibly have i.e. Recommended Anime, and Recommended Manga.

 Or Novel when it exists on future.

**Comment by brahmkshatriya** [comment]
Recommendations already recommends both, they are based on your list, if you read more manga, It will recommend you more manga instead of anime. 
This is not controlled by me, thats just how anilist works

**Comment by Mano5JP** [comment]
No problem then,

I noticed all were anime that was thw reason of this post.
