### ISSUE TITLE
[Source Request] https://www2.kickassanime.ro/

### ISSUE THREAD

**Issue by MarJose123** [saikou-app/saikou#502]
### Summary

Source Request for https://www2.kickassanime.ro/

### The Problem

N/A

### The Ideal Solution

N/A

### Additional Context

Please add as additional source for https://www2.kickassanime.ro/

**Comment by xwaay12** [comment]
> Could I please have a go at this?

yea u dont need permission to make ur own fork and add stuff to it, go ahead!

**Comment by TobyBridle** [comment]
> > Could I please have a go at this?
> 
> yea u dont need permission to make ur own fork and add stuff to it, go ahead!

Oh great - cheers 😄

**Comment by brahmkshatriya** [comment]
@TobyBridle If you do successfully add it, make sure to make a PR
If you need help, you can message in #dev channel on discord

**Comment by TobyBridle** [comment]
@MarJose123 Sorry for such a late turnaround but I've finally managed to get an extractor (Maverickki) working! I'm just going to clean up the code and then I'll push it to my fork.
There are still quite a few extractors to get done but I'm hoping now that I've done this one it should be much quicker for me to do the rest :)

**Comment by TobyBridle** [comment]
StreamSB is now also implemented.
The others all seem relatively easy to do and I can find references for them on Github. Unfortunately, Sapphire Duck, which seems to be the best quality of them all as it's pulling straight from CR, is looking like it's going to be a lot harder.

**Comment by MarJose123** [comment]
Hahaha, no worries. Cheer up! 🍻
