### ISSUE TITLE
Dub not working 

### ISSUE THREAD

**Issue by Howlingchaos** [saikou-app/saikou#503]
### Summary

Iruma kun dub is not working 

### Reproduction Steps

Nothing 

### Expected Result

It's was supposed to be dubbed It's not working

### Actual Result

Dub isn't dubbed

### Device Information

Version 1.2.0.23
Brand Samsung 
Arch idk
Android 12

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Provide proper information please

Which source did you select, did you try all of them?
Which server did you tried watching on?
What season of iruma are you trying to watch?
