### ISSUE TITLE
Manga Zoom Feature Enhancement 

### ISSUE THREAD

**Issue by SunglassJerry** [saikou-app/saikou#505]
### Summary

Unlike saikou, in every manga reader app, when you double tap, it zooms. When double tapped again, it zooms more. So, would really appreciate if the app zooms half after double tapping, then zooms fully if double tapped again.

### The Problem

(⁠・⁠∀⁠・⁠)

### The Ideal Solution

<⁠(⁠￣⁠︶⁠￣⁠)⁠>

### The Current Solution

(⁠*⁠´⁠ω⁠｀⁠*⁠)

### Additional Context

It returns to its normal size after double tapping the 3rd time

**Comment by brahmkshatriya** [comment]
Thats not possible without modifying the [gesturesviews](https://github.com/alexvasilkov/GestureViews)
