### ISSUE TITLE
Animixplay is down + banned

### ISSUE THREAD

**Issue by RealMimikyu** [saikou-app/saikou#508]
### Summary

Animixplay doesnt work anymore

### Reproduction Steps

Can you remove animixplay and add a other anime section? And pokemon wont work on all anime sources

### Expected Result

That it would work

### Actual Result

It failed

### Device Information

1.2.0.23
Samsung

13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
Animixplay was already removed (9bb1efe).
