### ISSUE TITLE
All sources are not working like AllAnime

### ISSUE THREAD

**Issue by Ghost5555K** [saikou-app/saikou#510]
### Summary

How to fix it

### Reproduction Steps

.

### Expected Result

.

### Actual Result

.

### Device Information

![Screenshot_2023-01-14-16-19-38-55_8fdea02c47a76e0fe7eccbf0ee9f2748](https://user-images.githubusercontent.com/122673464/212468409-42b40ded-2a28-4d62-b92a-83176afc8c65.jpg)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

...
![Screenshot_2023-01-14-16-19-38-55_8fdea02c47a76e0fe7eccbf0ee9f2748](https://user-images.githubusercontent.com/122673464/212468427-ac1716d7-4bc1-40cc-ad1a-16eb3db72aeb.jpg)

**Comment by xwaay12** [comment]
try using a dns maybe that could help?
