### ISSUE TITLE
"Not Listed" toggle for Searching

### ISSUE THREAD

**Issue by SunglassJerry** [saikou-app/saikou#511]
### Summary

Instead of the checkbox `◻️List only` in the searching page, put it as a dropdown menu inside filters. This way we can have the option to both Listed animes and unlisted animes.

### The Problem

←⁠(⁠>⁠▽⁠<⁠)⁠ﾉ

### The Ideal Solution

(⁠☞⁠ ͡⁠°⁠ ͜⁠ʖ⁠ ͡⁠°⁠)⁠☞

### The Current Solution

(⁠　⁠･⁠ω⁠･⁠)⁠☞

### Additional Context

ԅ⁠(⁠ ͒⁠ ⁠۝⁠ ͒⁠ ⁠)⁠ᕤ

**Comment by scrazzz** [comment]
Please fill out the form completely next time.

> "If it ain't broke, don't fix it"

Why alter the current UI when it already functions properly?

**Comment by SunglassJerry** [comment]
Ok, lemme explain. I once suggested to add the"Unlisted only" feature, to which Shivam replied that he needs to do a drop-down menu for it. That's why I suggested it. And it makes more sense if the drop-down menu is put inside the filters.

**Comment by scrazzz** [comment]
I have no idea what you're talking about. Moreover, the Filter option is bloated enough. There's no for this feature to be there imo.
