### ISSUE TITLE
Sites broken

### ISSUE THREAD

**Issue by UcraNerd** [saikou-app/saikou#512]
### Summary

Most of the sources are broken

### Reproduction Steps

Shouse the following sources:

> `Kamyroll`
> `Twist`
> `Tenshi`
> `9anime - 9anime backup`
> `Animixplay`
> `Animepahe`

### Expected Result

**Use the source for view the anime**

### Actual Result

*The list of all the errors:*

- **Kamyroll (latest beta)**

> `Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: error code: 1020`

- **Twist (latest stable)**

> `java.net.UnknownHostException: Unable to resolve host "api.twist.moe": No address associated with hostname`

- **Tenshi (latest beta / in stable doesn't work but no reports)**

> `For input string: ""`

- **9anime - 9anime backup**

*In the latest stable version:*

> `org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=[https://animekisa.in/filter?keyword=&language%5B%5D=subbed&year%5B%5D=2023&sort=default&season%5B%5D=winter&type%5B%5D=tv]`

*In the latest beta version:*

> `Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: .....inid=5892&sizeid=28&zoneid=7219"></script></body></html>`

*9anime backup: `timeout`*

- **Animixplay (latest beta)**

> `Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: .....udflare</a></div></div></div></body></html>`

- **Animepahe (latest beta)**

> `Field 'slug' is required for type with serial name 'ani.saikou.parsers.anime.AnimePahe.SearchQuery.SearchQueryData', but it was missing at path: $.data[0] at path: $.data[0] at path: $.data[0]`

### Device Information

Saikou Version: 1.2.0.23 and 1.1.6
Device: samsung j6lte
Architecture: arm
OS Version: REL 10 (29)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

> Tenshi.moe is apparently down

**Comment by UcraNerd** [comment]
> I recommend using a [debug build](https://github.com/saikou-app/saikou/actions/runs/3950847928) (available for download in a zip called `artifact.zip`). This provides fixes for some sources and removal of ones like Animixplay, Tenshi and 9anime that no longer work

Do you usually upload them on the discord server?

**Comment by Adolar0042** [comment]
Yes, we have a channel named #gitlog, it will receive any new debug builds

**Comment by UcraNerd** [comment]
> Yes, we have a channel named #gitlog, it will receive any new debug builds

Thanks, i'll check it out very soon; still thanks for the help!
