### ISSUE TITLE
Marin / formerly Tenshi still doesn't work

### ISSUE THREAD

**Issue by Snooby11** [saikou-app/saikou#516]
### Summary

Marin rarely shows up with episodes, and when it does no sources pop up

### Reproduction Steps

Open up any anime and select Marin source

### Expected Result

To see episodes and be able to download 

### Actual Result

Comes up with Couldn't find anything x( Try another source most of the time

Rarely the episodes will show up, but when clicking them no actual videos come up

### Device Information

Version 1.2.0.24
Samsung

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Please if you get a chance to check this out, tenshi is the only reliable one that always has download links. I need to download so I can watch coming home from work with shitty service, not able to stream :(

**Comment by scrazzz** [comment]
Please state the name of the anime you are having issues with. I'm guessing the anime you are trying to watch isn't available on marin.

Here's one anime that works on marin:
![Screenshot](https://user-images.githubusercontent.com/70033559/213614780-80644179-dbb0-4b06-b356-fce8dd0c826e.jpg)

Alternatively, you could do this method to download anime:
1. Open any anime
2. Choose a source that has this anime
3. Choose an episode
4. Long press on one of the source, you'll get a download link copied to your clipboard 
5. Open that link in any download manager.

You can use the help of google to choose any download manager. I'd recommend 1DM from the PlayStore.

**Comment by Snooby11** [comment]
Vinland saga season 1, I was watching it last week with tenshi fine. Unless I'm misunderstand and marin isn't just tenshi but they changed their name

I didn't long about the long press thing though, I just tried it with one, and I have ADM, and it says it can't download because it's a webpage

I'll try and mess around with it though

**Comment by scrazzz** [comment]
Marin works fine for me and loads Vinland Saga:
![Screenshot](https://user-images.githubusercontent.com/70033559/213656910-e462bb9e-1b72-48a5-ba2b-9f3a082a3a27.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/70033559/213657178-a39350b5-c3cf-40d1-91fe-c655520d0601.jpg)

**Comment by Arghadatta** [comment]
> Marin works fine for me and loads Vinland Saga: ![Screenshot](https://user-images.githubusercontent.com/70033559/213656910-e462bb9e-1b72-48a5-ba2b-9f3a082a3a27.jpg) ![Screenshot_2](https://user-images.githubusercontent.com/70033559/213657178-a39350b5-c3cf-40d1-91fe-c655520d0601.jpg)

It also don't work for me.trying black clover and blue lock but it says timeout.but i checked on marin that they exists

**Comment by scrazzz** [comment]
I just realized that marin.moe has ddos guard protection. So it doesn't work for some users.

**Comment by Snooby11** [comment]
> I just realized that marin.moe has ddos guard protection. So it doesn't work for some users.

That's interesting. I guess never lucky for me. Is there a way that this could get fixed eventually or does the ddos protection fuck me

**Comment by scrazzz** [comment]
There's no way to bypass ddos protection in Saikou.

**Comment by brahmkshatriya** [comment]
Please check out the latest Artifact & open the issue again If it doesnt work

**Comment by venkat2305** [comment]
@brahmkshatriya please reopen this issue. It's not working for me. I could play on the browser.

**Comment by scrazzz** [comment]
I can confirm that this issue has not been fixed yet.

**Comment by XDgamerCZ** [comment]
Also doesn't work for me. It worked before, now any anime doesn't work.

**Comment by inthavoc** [comment]
Same here, stuck on the "Couldn't find anything"
Tenshi/Marin was the only stable and fully working source for me, always had issues with the others.
Will be looking forward to a possible resolution.
Thanks

**Comment by venkat2305** [comment]
Update: This issue isn't fixed.
