### ISSUE TITLE
Add Debrid Support for Cached Torrents & MultiScrape

### ISSUE THREAD

**Issue by reddit-reaper** [saikou-app/saikou#518]
### Summary

Add Debrid Support for Cached Torrents

### The Problem

No cached torrent support

### The Ideal Solution

Hey brahmkshatriya so i messaged you on discord but i understand you're a busy guy. So i was wondering if i could request adding cached torrent support from debrid services. This is pretty much what all kodi addons do nowadays + apks like syncler and weyd. I can hook you up with a premiumize account and have some knowledge about how the whole process works for anime as ive helped devs with anime addons in kodi in the past.

Also jw but any reason you only scrape the selected site instead of multiscraping all sites you have scrapers for at the same time? im guessing its due to stupid stuff in anime metadata per site

**Comment by brahmkshatriya** [comment]
> Hey brahmkshatriya so i messaged you on discord but i understand you're a busy guy. So i was wondering if i could request adding cached torrent support from debrid services. This is pretty much what all kodi addons do nowadays + apks like syncler and weyd. I can hook you up with a premiumize account and have some knowledge about how the whole process works for anime as ive helped devs with anime addons in kodi in the past.

Yea I read your DM, what I currently wondering is whether to show this as a Source or not, & I am guessing this requires an account & password thingy too, while also providing a link to a debrid server, Which seems very specific for a generalized anime app. I would def recommend making a seperate fork, but I wouldnt mind if it was in the official app too. So basically, I unsure whether to add this or not

> Also jw but any reason you only scrape the selected site instead of multiscraping all sites you have scrapers for at the same time? im guessing its due to stupid stuff in anime metadata per site

I would rather not want client to be overloaded with sending and receiving so many requests at the same time lmao

**Comment by ShavonHastings** [comment]
Alternative app?

**Comment by reddit-reaper** [comment]
>> Yea I read your DM, what I currently wondering is whether to show this as a Source or not, & I am guessing this requires an account & password thingy too, while also providing a link to a debrid server, Which seems very specific for a generalized anime app. I would def recommend making a seperate fork, but I wouldnt mind if it was in the official app too. So basically, I unsure whether to add this or not
> 
>So imho for it to work how you currently use it, there would be no reason to separate torrent sites into seperate links. Some have APIs you can use and just scrape pretty instantly its just figuring out all the title searches youd have to account for. Currently it seems you depend on the websites for ep metadata instead of scraping based on general metadata acquired from anilist etc. Not a dev unfortunately so i can't really create a fork besides to use updated scrapers on the TV fork lol my idea for it would be the following

1. Meta for show and episode all based on meta provider so you have full meta instead of getting meta from website which would be incompatible with torrents

2. Selectable scrapers the way you have it is fine and i understand it's too lower requests on external websites so that's cool. Just would need an option for torrents called "Cached Torrent search" or something in the scraper list which would look for single ep and episodes within torrent packs on the major torrent websites. Thing is this would depend on your handling of metadata as you'll have to scrape based on meta using different variants of title and ep/season combinations. There's a few examples i can give for this already though but they're in python 

3. As far as adding the login stuff yes that would be needed as well. Its a 0auth token though so not to bad. Basically it's for using the cache check api and the direct download api to get the file matrix and then pick which one you want to stream 

This is of course just my thoughts, not forcing anything just figured I'd mention it. If you're interesting on further discussing hit me up on discord or github is fine as well

**Comment by reddit-reaper** [comment]
Just to add, torrent scraping using metadata while hard, the websites themselves rarely if ever change. The most that changes are the domains where they add more secondary ones if anything. The hardest part is all the logic needed to scrape anime since they follow no standard conventions like US shows

**Comment by reddit-reaper** [comment]
Btw a good example of how well this could work if implemented

Stremio+torrentio+kitsu addons. Works really great, get highest quality links and you always have possible sources vs none when scrapers ask need to be updated as torrent websites never change or rarely do

**Comment by brahmkshatriya** [comment]
As for now, I donot plan on adding a nyaasi scraper
If nyaasi is ever added, I would also like to add torrent support
