### ISSUE TITLE
Add coloredmanga extension in saikou

### ISSUE THREAD

**Issue by KunalSucks** [saikou-app/saikou#520]
### Summary

I want a new enxtension which is colored manga. you can see it on google

### The Problem

Add it pleaseeeee

### The Ideal Solution

Please add it

**Comment by Adolar0042** [comment]
Some sources already provide colored versions. You can find them by using "Wrong Title?" (Most of the time the name format for them is `<title> (colored)`)

**Comment by scrazzz** [comment]
Duplicate of #462
