### ISSUE TITLE
Add 9Anime as Source with Option to Download Episodes 

### ISSUE THREAD

**Issue by legendartist58** [saikou-app/saikou#521]
### Summary

Add 9Anime as Source with Option to Download Episodes 

### The Problem

Add 9Anime as Source with Option to Download Episodes 

### The Ideal Solution

Add 9Anime as Source with Option to Download Episodes

**Comment by SunglassJerry** [comment]
ƪ⁠(⁠‾⁠.⁠‾⁠“⁠)⁠┐ feels like deja vu

**Comment by Searchcat37** [comment]
> ### Summary
> 
> Add 9Anime as Source with Option to Download Episodes 
> 
> ### The Problem
> 
> Add 9Anime as Source with Option to Download Episodes 
> 
> ### The Ideal Solution
> 
> Add 9Anime as Source with Option to Download Episodes 
> 
> ### The Current Solution
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

9Anime was removed in the recent update because the site keeps changing
