### ISSUE TITLE
[Source Request] CrunchyRoll source

### ISSUE THREAD

**Issue by venkat2305** [saikou-app/saikou#525]
### Summary

new sources for cruncyroll

### The Problem

as we know some mfs gave dmca strike to kamyroll, I'm suggesting alternative apis and sites for Crunchyroll. 
1. Consumet api - https://github.com/consumet
2. Animixreplay - https://animixreplay.to/list.php?abc=A&filter=roll
 please don't say animixreplay is just another gogo scraper, it has Crunchyroll too. please check it out. its still in development though. it would be a great addition.
3. Kickassanime - https://www2.kickassanime.ro/
  it has Crunchyroll but not for all shows though. don't know why and it's named as saphire duck. This would be a great addition.

I'm requesting the devs to kindly look into this. 

### The Ideal Solution

I would say consumet api looks better since it has other sources as well and provides the access directly through an API

**Comment by venkat2305** [comment]
this [project](https://github.com/insomniachi/Totoro) has already implemented kamyroll using consumt API. please refer to this if needed.
Thanks in advance

**Comment by Adolar0042** [comment]
* both consumet and the project you mentioned used kamyroll
* animixreplay is still being worked on, so might want to wait until thats finished

I think Kickassanime is possible to add (tho idk how, so someone else will have to do it)

**Comment by venkat2305** [comment]
Please read this conversation. 
https://github.com/insomniachi/Totoro/issues/10#issuecomment-1397117461

**Comment by scrazzz** [comment]
Please don't cramp multiple suggestions/feature requests in one issue next time.

**Comment by Adolar0042** [comment]
yeah, read that soon after my comment and edited it accordingly. For now I sent  a message in the discord if someone wants to implement it
![image](https://user-images.githubusercontent.com/39769465/214932353-58cb01a9-39a4-4021-b6f0-92868a31c785.png)

**Comment by venkat2305** [comment]
> Please don't cramp multiple suggestions/feature requests in one issue next time.

I was requesting for Crunchyroll which was available in all of these sites. So, I mentioned all of these sites.


> yeah, read that soon after my comment and edited it accordingly. For now I sent a message in the discord if someone wants to implement it ![image](https://user-images.githubusercontent.com/39769465/214932353-58cb01a9-39a4-4021-b6f0-92868a31c785.png)

thanks.
Also, I checked it myself, Crunchyroll is working with consumet Api 
![image](https://user-images.githubusercontent.com/55329452/214934303-385d17aa-7213-438a-bad4-36efe1ed6d5d.png)

**Comment by Adolar0042** [comment]
yeah, I took a quick look at that program too, where can I choose the source?
