### ISSUE TITLE
[Source Request] RAW manga sources

### ISSUE THREAD

**Issue by TomasBodas** [saikou-app/saikou#526]
### Summary

Addition of RAW manga  sources.

### The Problem

Some manga are untranslated/here's many japanese learners that are manga/anime fans. 
I don't think it'd be a bad feature to add sources of the original language.

### The Ideal Solution

Addition of RAW manga sources.
If that's not on the scope of this project I'll fork it myself. Just a consideration.

### Additional Context

If that's not on the scope of this project I'll fork it myself. Just a consideration.

**Comment by scrazzz** [comment]
https://github.com/saikou-app/saikou#rejected-stuff
