### ISSUE TITLE
Animepahe source now not working

### ISSUE THREAD

**Issue by Arpitvv** [saikou-app/saikou#527]
### Summary

Now even Animepahe is not working 

### Reproduction Steps

Nkthin

### Expected Result

Nkthinidk

### Actual Result

Not working

### Device Information

Latest version
Lenovo
Aarch64

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Adolar0042** [comment]
Use "Wrong Title?" and select the same anime again, that should fix it for now

**Comment by Arpitvv** [comment]
Thank you brother
