### ISSUE TITLE
I can't see Vidstream server 

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#529]
### Summary

I cant see Vidstream and streamsb is very slow 

### Reproduction Steps

Picking a another server 

### Expected Result

Able to fix it so I can pick the best server

### Actual Result

I can't pick the Vidstream cause of not able to be seen

### Device Information

Saikou 1.2.0.24
Vivo 1606
1.4Ghz Snapdragon 425 Quadcore
Android 6.0.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Searchcat37** [comment]
Which source are you using?

**Comment by 4wadia** [comment]
Yes server's are not working

**Comment by vkgiri11** [comment]
> Which source are you using?

AllAnime, Gogo, Zoro all of them

**Comment by fifomicas** [comment]
> > Which source are you using?
> 
> AllAnime, Gogo, Zoro all of them

Yeah same here

**Comment by chesteruytech** [comment]
I would like to reopen the issue, as I don't see Vidstream in the Gogoanime server. Please refer to this picture below. ![Screenshot_2023-02-13-00-17-01-109_ani.saikou.beta.jpg](https://user-images.githubusercontent.com/26598267/218323077-53e72395-c23f-46c7-a970-ee6703256d68.jpg)
