### ISSUE TITLE
Italian Kamyroll not work

### ISSUE THREAD

**Issue by Yoshinizar** [saikou-app/saikou#530]
### Summary

Italian Kamyroll not work

### Reproduction Steps

Search episode give me error in kamyroll italia

### Expected Result

Work

### Actual Result

Error

### Device Information

Saikou Version: 1.2.0.25
Device: realme RE879AL1
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Adolar0042** [comment]
Kamyroll got a DMCA claim and no longer available.
