### ISSUE TITLE
Zoro server not showing

### ISSUE THREAD

**Issue by BANKAITYBW** [saikou-app/saikou#536]
### Summary

In Zoro source no server is showing 

### Reproduction Steps

No response 

### Expected Result

No response 

### Actual Result

No response 

### Device Information

Saikou Version: 1.2.0.24
Device: Realme RMX1941
Architecture: aarch64
OS Version: REL 10 (29)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by TobyBridle** [comment]
What are you trying to watch? On 1.2.0.24 I seem to be able to use it fine for the ones I've tried.

**Comment by BANKAITYBW** [comment]
> What are you trying to watch? On 1.2.0.24 I seem to be able to use it fine for the ones I've tried.

One piece

**Comment by TobyBridle** [comment]
StreamSB seems to be working fine with it. Does a little toast pop up with an error message or anything?

**Comment by TobyBridle** [comment]
> StreamSB seems to be working fine with it. Does a little toast pop up with an error message or anything?

![Screenshot_20230203-114407.png](https://user-images.githubusercontent.com/52335751/216595279-c2ad6d53-3bb4-47ef-a460-6054d4814db5.png)

**Comment by BANKAITYBW** [comment]
> StreamSB seems to be working fine with it. Does a little toast pop up with an error message or anything?



> > StreamSB seems to be working fine with it. Does a little toast pop up with an error message or anything?
> 
> ![Screenshot_20230203-114407.png](https://user-images.githubusercontent.com/52335751/216595279-c2ad6d53-3bb4-47ef-a460-6054d4814db5.png)

Issue seem to be resolved now thank you

**Comment by BANKAITYBW** [comment]
![Uploading Screenshot_2023-02-03-17-22-52-66.jpg…]()

**Comment by BANKAITYBW** [comment]
![Uploading Screenshot_2023-02-03-17-22-52-66.jpg…]()

**Comment by BANKAITYBW** [comment]
![Screenshot_2023-02-03-17-22-52-66](https://user-images.githubusercontent.com/124359757/216597874-eebde453-c1a0-4027-92ba-bb3f2951cada.jpg)

**Comment by BANKAITYBW** [comment]
> > StreamSB seems to be working fine with it. Does a little toast pop up with an error message or anything?
> 
> ![Screenshot_20230203-114407.png](https://user-images.githubusercontent.com/52335751/216595279-c2ad6d53-3bb4-47ef-a460-6054d4814db5.png)

![Screenshot_2023-02-03-17-22-52-66](https://user-images.githubusercontent.com/124359757/216602024-971f78a0-529c-4e68-92ac-cc0fadf4c258.jpg)

**Comment by scrazzz** [comment]
Try using a DNS in the app settings.
![s](https://user-images.githubusercontent.com/70033559/216604816-d4f9fbee-aa84-4106-9d4b-5bf3d4b98686.jpg)

**Comment by BANKAITYBW** [comment]
> Try using a DNS in the app settings. ![s](https://user-images.githubusercontent.com/70033559/216604816-d4f9fbee-aa84-4106-9d4b-5bf3d4b98686.jpg)

Still nothing happened issue is still tere

**Comment by TobyBridle** [comment]
> > > StreamSB seems to be working fine with it. Does a little toast pop up with an error message or anything?
> > 
> > 
> > ![Screenshot_20230203-114407.png](https://user-images.githubusercontent.com/52335751/216595279-c2ad6d53-3bb4-47ef-a460-6054d4814db5.png)
> 
> ![Screenshot_2023-02-03-17-22-52-66](https://user-images.githubusercontent.com/124359757/216602024-971f78a0-529c-4e68-92ac-cc0fadf4c258.jpg)

I also had this popup and after clearing cache it had gone. Maybe a bad link has been cached or something?
