### ISSUE TITLE
Zoro not working

### ISSUE THREAD

**Issue by subby2006** [saikou-app/saikou#542]
### Summary

Zoro source not working, nothing is showing up for that source

### Reproduction Steps

Open any show and select the Zoro source

### Expected Result

Episodes should show and at least the streamsb source should come up

### Actual Result

Nothing, simply shows couldn't find anything. Using wrong title doesn't work either as nothing appears for the search

### Device Information

Saikou Version: 1.2.0.24
Brand: Google
Architecture: aarch64
Android: 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by xwaay12** [comment]
zoro has cf protection now making it unusable

**Comment by fifomicas** [comment]
This is also happening to me and Gogo does the same thing
