### ISSUE TITLE
Full title on wrong title menu

### ISSUE THREAD

**Issue by venkat2305** [saikou-app/saikou#545]
### Summary

Right now we have to wait to check the title of the show and check all of the shows

### The Problem

Right now we have to wait to check the title of the show and check all of the shows

### The Ideal Solution

It would be great to have a list view to see full title. It is difficult when there are lot of shows and the app couldn't select the correct title.
![Screenshot_2023-02-09-17-31-50-516_ani saikou beta](https://user-images.githubusercontent.com/55329452/217807812-e1374f0f-5c8e-451c-b723-1a0c5929396b.jpg)
It's seven deadly sins season 3, all anime.

**Comment by Xx-Mohit-xX** [comment]
Totally agree with this issue. It pain in a** to wait to wait for the hovering text to show the whole title. Especially when the anime title is too long.

**Comment by subby2006** [comment]
You can hold down on the anime cover and it'll show the full title

**Comment by venkat2305** [comment]
> You can hold down on the anime cover and it'll show the full title

It would be great if it shows the full title by default preferably in a list view

**Comment by brahmkshatriya** [comment]
> > You can hold down on the anime cover and it'll show the full title
> 
> It would be great if it shows the full title by default preferably in a list view

yea would really make it ugly to look at

**Comment by venkat2305** [comment]
> 
> 
> > > You can hold down on the anime cover and it'll show the full title
> > 
> > It would be great if it shows the full title by default preferably in a list view
> 
> yea would really make it ugly to look at

Can you please find a better solution then?

**Comment by venkat2305** [comment]
@brahmkshatriya 
Can you please find a better solution then?
