### ISSUE TITLE
AnimePahe source not working

### ISSUE THREAD

**Issue by JasonBlitz5** [saikou-app/saikou#546]
### Summary

Nothing shows up for the AnimePahe source for any anime

### Reproduction Steps

Go to any anime and Select AnimePahe Source

### Expected Result

Episodes should show up with quality choices

### Actual Result

Get weird error shows up and no episodes shows up

### Device Information

Saikou Version: 1.2.0.24
Device: samsung c2q
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Here's a picture with the weird error message I got:

![Screenshot_20230213_195549_Saikou ](https://user-images.githubusercontent.com/97261684/218611435-96ffb003-7540-4838-89b7-bafcfb0ef36f.jpg)

**Comment by Arpitvv** [comment]
Atleast fix it fast

**Comment by scrazzz** [comment]
> Atleast fix it fast

No. But feel free to contribute by fixing the source by yourself. If you don't know how to fix the source the only option for you is to wait.

**Comment by TobyBridle** [comment]
> Atleast fix it fast

⏱ https://paypal.me/toby_bridIe_1

**Comment by bitchm** [comment]
Pls I need animepahe to work soon pls hurry up and fix it

**Comment by Moayedvoi** [comment]
Bruh u stupid?

**Comment by TobyBridle** [comment]
> 

How are you reliant on it?

**Comment by JasonBlitz5** [comment]
Did I cause something here?

**Comment by TobyBridle** [comment]
> Did I cause something here?

Seems like this issue has attracted some entitled 12 year olds.

**Comment by JasonBlitz5** [comment]
> > Did I cause something here?
> 
> Seems like this issue has attracted some entitled 12 year olds.

Oh gotcha

**Comment by Aesira01** [comment]
bitchm - Joined 2 days ago.

Name and profile checks out...
