### ISSUE TITLE
Animepahe not working 

### ISSUE THREAD

**Issue by ShadowHuNTER694208** [saikou-app/saikou#551]
### Summary

As mentioned in tittle 

### Reproduction Steps

Choose anime and select animepahe as source 

### Expected Result

Episodes should be displayed and play as usual 

### Actual Result

Episodes are displayed but you cannot watch them and select server 

### Device Information

Saikou Version: 1.2.0.24
Device: Redmi sunny
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![Screenshot_2023-02-15-20-34-35-035_ani saikou beta](https://user-images.githubusercontent.com/125473222/219065855-6bbc1567-8a8e-4e16-9313-91ef446ff1a3.jpg)

**Comment by Aesira01** [comment]
Issue has already been mentioned, refer to Issue#546.
