### ISSUE TITLE
Allanime source not working after artifact update

### ISSUE THREAD

**Issue by Kuuhakuxx** [saikou-app/saikou#554]
### Summary

Update my app and the source stop working

### Reproduction Steps

Nil

### Expected Result

Nil

### Actual Result

![Screenshot_20230217_091948_Saikou ](https://user-images.githubusercontent.com/122075694/219525542-82ec05de-406a-490a-b611-a15ce7ed8b02.jpg)

**UPDATE allanime source is now allanime.co and not allanime.site so I hope admin see this**
### Device Information

Saikou version: 1.2.0.24
Brand: Samsung s10 plus

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by arunkumarkd** [comment]
Ya the same error occurs to me, to open any anime in any sources, kindly need to fix it ASAP

**Comment by sjain3097** [comment]
Same for Me 
![Uploading Screenshot_2023-02-18-15-56-39-099_ani.saikou.beta.jpg…]()

**Comment by TobyBridle** [comment]
Fixed by #567
