### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by Maniac-Mit** [saikou-app/saikou#558]
### Summary

Keep showing "Error data loading" and some codes

### Reproduction Steps

![Screenshot_20230218-141516](https://user-images.githubusercontent.com/103870652/219851151-656f6300-ea71-40b8-8178-d0508ecff702.jpg)

### Expected Result

I dont know..bt the servers are not working
Allanime, Zoro, Gogo
Vidstreaming and Streamsb

### Actual Result

Want to run the app like before...
Love this app

### Device Information

Saikou Version: 1.2.0.24
Device: Infinix Infinix-X6812
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
Both Gogo and Zoro works for me. Make sure you use the latest artifact from [GitHub Actions](https://github.com/saikou-app/saikou/actions).

![skillissue](https://user-images.githubusercontent.com/70033559/219851473-cacb8565-b045-42b9-9e34-b07bc5d8dc87.jpg)

**Comment by Maniac-Mit** [comment]
How can i fix it
