### ISSUE TITLE
Wrong Manga/Anime selected.

### ISSUE THREAD

**Issue by XxMCBxX** [saikou-app/saikou#56]
Hello.
I watched anime and manga from aniyomi for a while now and i saw this new app so i  tried it and it was great untill the point where when i was adding my manga and saw that almoast all of theme didnt have the chapters. I tried every engine and it still didnt work, some worked but showed the wrong manga.
I hope that you can fix this.

**Comment by brahmkshatriya** [comment]
![wrongtitle.png](https://user-images.githubusercontent.com/69040506/158335875-64f059e1-5368-4936-abcd-f9688730c187.png)


When it shows a wrong title, you can click on wrong title.

**Comment by XxMCBxX** [comment]
I thinck i figured it out.
The engine didnt load the right manga.
Now i have to manualy search for difarent titels if the manga to find it.
I hope you have a better way of doing this in the future.
