### ISSUE TITLE
App crashes after trying to open settings

### ISSUE THREAD

**Issue by RealMimikyu** [saikou-app/saikou#560]
### Summary

App crashes

### Reproduction Steps

Hi, the app is crashing if i try to open settings
Can you look into it?

### Expected Result

To open settings

### Actual Result

The app crashed

### Device Information

1.2.0.24
Android 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Clear data, or redownload the app
