### ISSUE TITLE
Streams aren't working  

### ISSUE THREAD

**Issue by Iamroni25** [saikou-app/saikou#562]
### Summary

Stream aren't showing in any servers                

### Reproduction Steps

Idk

### Expected Result

I expect to happen that streams would appear but it didn't 

### Actual Result

When I click on episode it usually pops up and let you choos server like vidstream. But after update it doesn't show anything like that and says there's an error

### Device Information

Saikou Version: 1.2.0.24
Device: Redmi selene
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Pls fix this

**Comment by brahmkshatriya** [comment]
duplicate of https://github.com/saikou-app/saikou/issues/559

**Comment by Iamroni25** [comment]
Yes exactly like #559

**Comment by edgehub-cloud** [comment]
Make the streams break Harder daddy.

**Comment by Lakshya5088** [comment]
> Make the streams break Harder daddy.

Aw hell naw 🗿

**Comment by ShivamB25** [comment]
sooooo hoooot
