### ISSUE TITLE
GoGo Anime server giving errors

### ISSUE THREAD

**Issue by Arsalan-devil** [saikou-app/saikou#564]
### Summary

When ever i try to watch anime from gogo anime the video server get brokes and also there is only one server available for watching which name is xstreamcdn and is very slow.

### Reproduction Steps

Select any anime. Then select source to gogo then play episode after that list of server for watching comes but there is only one server available. All the other is gone. And error msg get displayed.

### Expected Result

List of servers should have shown like they are available on the source website.

### Actual Result

Only one server shows which is very slow. And also error msg is shown below.
 
Expected start of the object '{', but had 'EOF'

instead at path: $

JSON input: <!DOCTYPE HTML PUBLIC "-//

IETF//DTD HTML 2.0//EN">

<html> <head>

<title>404 Not Found</title>

</head> <body>

<h1>Not Found</h1>

<p>The requested URL was not found on this

server.</p>

</body></html>

### Device Information

Saikou version: 1.2.0.24
Brand: Realme Gt Neo 2 5g
Architecture: kernel architecture: aarch64.
Soc Architecture: kyro 585
Android: 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Nevenon** [comment]
![Screenshot_20230220_162246](https://user-images.githubusercontent.com/107057902/220051601-c8655c54-23a8-475b-a2be-4ac8f34b7644.jpg)
Me to!

**Comment by Luzmiel** [comment]
I've downloaded the latest artifact and still I have this error message when trying to watch several anime.

**Comment by Arsalan-devil** [comment]
![Screenshot_2023-02-20-01-58-58-06_8fdea02c47a76e0fe7eccbf0ee9f2748](https://user-images.githubusercontent.com/54109777/220101792-0540d7c6-7e95-481a-a985-eb2b8bc410dc.jpg)
@Luzmiel @Nevenon yes same is happening in my app

**Comment by DarkKurogane** [comment]
I've encountered the same issue for the last couple of days, there seems to be a few issues open here. Let's be patient and not create duplicate issues, I hope the it gets fixed soon.

**Comment by Nevenon** [comment]
The bug is fix now.
