### ISSUE TITLE
Servers not working 

### ISSUE THREAD

**Issue by Howlingchaos** [saikou-app/saikou#569]
### Summary

All servers aren't working 

### Reproduction Steps

Nothing 

### Expected Result

A good running and working server

### Actual Result

Servers aren't working 

### Device Information

Latest
Samsung 
Don't know
Don't know

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by TobyBridle** [comment]
Have you downloaded the latest debug build?

**Comment by TobyBridle** [comment]
> Happening to me too, I was watching anime and then everything just stopped working

Are you on the latest debug build?

**Comment by fifomicas** [comment]
> > Happening to me too, I was watching anime and then everything just stopped working
> 
> Are you on the latest debug build?

Yes

**Comment by TobyBridle** [comment]
Are AllAnime, Gogo and Zoro not working? What are you trying to watch?
If you haven't already, please try to remove your cache and see if that helps.

**Comment by fifomicas** [comment]
> Are AllAnime, Gogo and Zoro not working? What are you trying to watch? If you haven't already, please try to remove your cache and see if that helps.

I removed my cache but I was watching blue exorcist when it stopped working, then I used other servers to see if they worked and they didn't. Then I went to check on other anime and it did the same thing.

**Comment by TobyBridle** [comment]
> > Are AllAnime, Gogo and Zoro not working? What are you trying to watch? If you haven't already, please try to remove your cache and see if that helps.
> 
> I removed my cache but I was watching blue exorcist when it stopped working, then I used other servers to see if they worked and they didn't. Then I went to check on other anime and it did the same thing.

I have just tried and can confirm that Blue Exorcist (Sub) is working on AllAnime and the dub is working on Zoro.
What error(s) are you getting from AllAnime?

**Comment by fifomicas** [comment]
> > > Are AllAnime, Gogo and Zoro not working? What are you trying to watch? If you haven't already, please try to remove your cache and see if that helps.
> > 
> > 
> > I removed my cache but I was watching blue exorcist when it stopped working, then I used other servers to see if they worked and they didn't. Then I went to check on other anime and it did the same thing.
> 
> I have just tried and can confirm that Blue Exorcist (Sub) is working on AllAnime and the dub is working on Zoro. What error(s) are you getting from AllAnime?

"Couldn't find anything x( Try another source." Or the episodes show up but I can't select any servers because none appear

**Comment by scrazzz** [comment]
I can confirm that it's working for me on the latest build.
![majorskillissue](https://user-images.githubusercontent.com/70033559/220451981-be709cd6-a0d7-417e-bb1a-5b3d11f14611.jpg)

Make sure you install the latest build from [GitHub Actions](https://github.com/saikou-app/saikou/actions).

**Comment by fifomicas** [comment]
> > > > > Are AllAnime, Gogo and Zoro not working? What are you trying to watch? If you haven't already, please try to remove your cache and see if that helps.
> > > > 
> > > > 
> > > > I removed my cache but I was watching blue exorcist when it stopped working, then I used other servers to see if they worked and they didn't. Then I went to check on other anime and it did the same thing.
> > > 
> > > 
> > > I have just tried and can confirm that Blue Exorcist (Sub) is working on AllAnime and the dub is working on Zoro. What error(s) are you getting from AllAnime?
> > 
> > 
> > "Couldn't find anything x( Try another source." Or the episodes show up but I can't select any servers because none appear
> 
> Does your Saikou appear as just Saikou or is it Saikou β?

Saikou β

**Comment by TobyBridle** [comment]
Please follow the link in Scruz' response and install that. If you are still having trouble after that then I would advise coming into the support channel in our discord [server](https://discord.com/invite/saikou-app) as your case doesn't seem to be related to a fault within the app itself but rather something going wrong on your end.
