### ISSUE TITLE
feat: load scraper logic from repo

### ISSUE THREAD

**Issue by TobyBridle** [saikou-app/saikou#572]
### Summary

Rather than having the scrapers embedded into Saikou, have them stored in another repository and then loaded on app execution

### The Problem

With how volatile scrapers are, app updates just to fix scraper logic is common. This is problematic because it requires the users to manually update their app. Lots of users often plague the support channels repeating the same "x isn't working" messages.

### The Ideal Solution

Rather than embedding this into the client, there might be a way to load the code from an external repository using kotlin custom scripting.
This would be much more convenient for the users as scraper could be hotfixed and not require app installs.
This would also remove a lot of repetition within the support channels of people asking when the latest update is & how to update it.

### The Current Solution

N/A

**Comment by reddit-reaper** [comment]
This is actually what's done in pretty much all streaming apps nowadays to help with issues exactly as you stated. Syncler, WeyD, even Kodi addons all have seperate scrapers so they can update them individually. Stremio as well.

**Comment by soymadip** [comment]
So in short, extensions.

**Comment by TobyBridle** [comment]
> So in short, extensions. Right?

Sort of. The intention of this wasn't to ask for "extensions" but rather to move the logic of the scrapers to an external platform. If you're thinking of user installable extensions, that's not what this is.

**Comment by reddit-reaper** [comment]
May as well use the scraper logic a few different things use now, what was originally called wako style scrapers. They technically work in syncler as well but they changed slightly to have them updateable with version numbers

Example
https://syncler-providers.herokuapp.com/syncler/express-hybrid.json

**Comment by gaminglnk** [comment]
I think, the default scrapers embedded in Saikou shouldn't be removed, instead they should be used as a backup in certain scenarios, like when scrapper code isn't accessible.
But when connection is possible, it should get updated on its own as an auto-updating extension kind of thing.

**Comment by TobyBridle** [comment]
Of course, but when you have no connection, Saikou wouldn't work anyway? But yes, the idea was that the copy was stored locally and only updated when necessary.

**Comment by reddit-reaper** [comment]
im not a dev but personally i wouldnt even ship the app with scrapers loaded by default. its risky. best to have them separate and leave the app as an indexer by default pretty much. safest option, but this is just my opinion as I've been in this scene for a while
