### ISSUE TITLE
caching the list

### ISSUE THREAD

**Issue by N0N4M3ND** [saikou-app/saikou#575]
### Summary

idk if this is already added but, what if we cache the anime listings in the phone storage itself so you sometimes dont need to login with phone

### The Problem

j

### The Ideal Solution

j

### The Current Solution

j

**Comment by scrazzz** [comment]
Your proposed enhancement does not make any sense. Consider opening another issue and elaborate what you meant. Also fill in all the fields properly or else your suggestion will be discarded.
