### ISSUE TITLE
[providers] Some sites

### ISSUE THREAD

**Issue by OshekharO** [saikou-app/saikou#58]
Here are some sites i managed to find. Feel free to cross off sites that are not feasible to implement.

### Animes:

- [ ] https://anime-world.in
- [ ] https://lmanime.com
- [ ] https://animexin.xyz
- [ ] https://123animes.ru
- [ ] https://animenana.com
- [ ] https://animefox.sbs
- [ ] https://animeonsen.xyz
- [ ] https://11anime.fr
- [ ] https://www2.kickassanime.ro
- [ ] https://kimcartoon.li
- [ ] https://animeflick.net
- [ ] https://www.animeworld.tv

**Comment by Diegopyl1209** [comment]
https://anime-world.in/ ✅
https://lmanime.com/ ✅
https://animexin.xyz/ ❌
https://123animes.ru/ ✅
https://animenana.com/ ✅
https://animeonsen.xyz/ ❌
https://11anime.fr ✅
https://www2.kickassanime.ro/ ❌
https://kisscenter.net ✅
https://animeflick.net ✅
https://www.animeworld.tv/ ❌



I only check if the video url is easy to scrape

**Comment by brahmkshatriya** [comment]
Most of these are gogo based, & some are multilingual
only thing that is good is,
https://animenana.com/
but this also has a smaller library

**Comment by OshekharO** [comment]
@brahmkshatriya you can try these: https://github.com/OshekharO/Link-Crawler
