### ISSUE TITLE
Wrap Images setting not working as expected

### ISSUE THREAD

**Issue by ofek150** [saikou-app/saikou#580]
### Summary

The "Wrap Images" setting zooms out images when enabled

### Reproduction Steps

I enabled the Wrap Images option on a large screen device, and in my case a tablet.
Then I tried to read some mangas/manwhas(it doesn't matter)

### Expected Result

I expected **only** the spacing between the images to change

### Actual Result

When I enabled the setting, the spacing was removed but it also zoomed out the images and made it uncomortable to read.
I know that zooming is an option but when I do that I often accidentally move the images horizontally aswell(I am using webtoon type reading)

### Device Information

Saikou Version: 1.2.1.0
Brand: Samsung
Architecture: aarch64
Android Version: 13
Device: Samsung S6 Lite

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

"Wrap Images" disabled:
![IMG-20230228-WA0009](https://user-images.githubusercontent.com/45180767/221827544-e1f177d5-a6f5-46c4-8e24-845703bfdbf8.jpg)
"Wrap Images" enabled:
![IMG-20230228-WA0008](https://user-images.githubusercontent.com/45180767/221827643-196ed4a4-be15-48ca-bd1c-034cab34405c.jpg)

**Comment by brahmkshatriya** [comment]
> I expected only the spacing between the images to change

That's changed using "space pages" toggle

> the spacing was removed but it also zoomed out the images and made it uncomortable to read

Yea thats why it's toggle, because it cant really be fixed by me
