### ISSUE TITLE
Horizontal spacing issue on tablets

### ISSUE THREAD

**Issue by ofek150** [saikou-app/saikou#581]
### Summary

There's horizontal spacing between the images and screen's edge when reading manwhas on a tablet

### Reproduction Steps

Read manwhas on a tablet

### Expected Result

I expected that the will be no horizontal spacing between the images and the screen edge

### Actual Result

When I am reading any kind of manwha thete's horizontal spacing between the images and the screen edge

### Device Information

Saikou Version: 1.2.1.0
Android Version: 13
Device: Samsung S6 Lite

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
duplicate of #580
