### ISSUE TITLE
Casting with Web Video Caster doesn't work on LG C1 (webOS)

### ISSUE THREAD

**Issue by taltal121** [saikou-app/saikou#587]
### Summary

Tried to cast anime with the Web Video Caster (WVC) phone app and the WVC receiver app on my television (LG C1), but nothing happens or I keep getting "Oops! Error: 1000".

### Reproduction Steps

Successfully connected my WVC app to the WVC receiver app on my television. Then tried to cast anime (I tried this with multiple shows).

### Expected Result

The episode plays on my television and I can control it with the WVC phone app.

### Actual Result

I get a black screen on my phone or the "Oops! Error: 1000!" message on the phone app and nothing happens on my television.

### Device Information

Saikou Version: 1.2.1.0
Brand: Samsung
Architecture: ?
Android Version: 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

I use Gogo as my default source for anime on Saikou. When I go to the site on the WVC phone app browser directly, instead of via Saikou, it casts anime on my LG C1 without a problem.

**Comment by brahmkshatriya** [comment]
You should consult WVC devs, 
This issue not in my hands

**Comment by casolorz** [comment]
I'm the wvc developer. I can take a look at it but I'm guessing it is related to this https://github.com/saikou-app/saikou/discussions/591

@taltal121 feel free to email us at webvideo@instantbits.com so we can help you.
