### ISSUE TITLE
For new links to compensate the old removed ones.

### ISSUE THREAD

**Issue by Devansh7u** [saikou-app/saikou#593]
### Summary

Add new links to increase the value for the app.

### The Problem

After the last update many links or extensions have been removed. So this issue is to suggest new alternative and there benefits for the app.

### The Ideal Solution

The ideal solution is to bring the old links along with the new links. So the viewers have a lot of options for ther both preferences and at some point when some links are not working.

'Animesuge' is the best alternative for 9anime as all the anime has 9anime watermark but you can also promote it as viz media as all the links are directed from viz cloud servers 

'Kickassanime' can be the next crunchy roll or kamyroll as it has all there anime along with multiple languages and even the video links are from crunchy roll servers.

My personal favourite and many have been using it in cloudstream app that is 'kronch' just like kickassanime it's also a nice alternative to kamyroll but it's links are their own.

### The Current Solution

Add the links
https://animesuge.to
https://www2.kickassanime.ro
Kronch
Also please make the app available on both Android TV and windows. Please 

### Additional Context

Please add new links and the links mentioned above so that the viewers have options if some links don't work.

**Comment by TobyBridle** [comment]
Are you on the latest artifact? You mentioned adding KAA but it's already there. Cronchy is also in the process of being added so we will have that soon too

**Comment by Devansh7u** [comment]
I can't find KAA on my app latest
Version

**Comment by brahmkshatriya** [comment]
Wait for an update
