### ISSUE TITLE
Screen rotation bug in Saikou anime streaming app

### ISSUE THREAD

**Issue by i486** [saikou-app/saikou#596]
### Summary

Screen reverse rotates while landscape is locked in Android

### Reproduction Steps

    Put your tablet in landscape mode and lock it on the quick panel
    Open Saikou app on Android device
    Select a video to play
    Wait for the video to start playing
    Notice that the screen rotates in the opposite direction

### Expected Result

Start video in same orientation as Android/Saikou app.

### Actual Result

It reverse rotates when the video starts.

### Device Information

Saikou Version: 1.2.1.0
Brand: Samsung Galaxy Tab A (SM-T515N) - Stock
Architecture: AArch64 
Android: 11

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

I noticed a bug in the Saikou anime streaming app where the screen rotation is rotated in the opposite direction when a video starts playing, even though the rotation setting is locked in the Android settings. The app does not have any rotation settings of its own, which makes it impossible to fix the issue from within the app.

**Comment by brahmkshatriya** [comment]
Looks very much like a device only issue, 

I would suggest turning off the rotate toggle from the video player settings

If anyone else gets the same issue, feel free to open the issue again
