### ISSUE TITLE
Notify when a New Episode or Chapter is added to a source

### ISSUE THREAD

**Issue by XxMCBxX** [saikou-app/saikou#60]
I was useing aniyomi befor this app and on there i didnt have to manualy look at every manga to see if a new chapter is out wich i have to do on saikou.

**Comment by Eumiella** [comment]
This is already planned if I remember correctly

**Comment by XxMCBxX** [comment]
Then when is the new update comeing?

**Comment by Eumiella** [comment]
No ETA dev is focusing on settings

**Comment by XxMCBxX** [comment]
Wdym?

**Comment by Eumiella** [comment]
Dev is working on the app's settings

**Comment by XxMCBxX** [comment]
But when is the update going to be if you know

**Comment by Eumiella** [comment]
I dont know when but if you ask me I think it'll come after he adds light novel support

**Comment by XxMCBxX** [comment]
I watched a video from like 2 weeks ago about this app and the guy said that he contacted the creator of the app and said that light novel support is going to be addes in a week or the week after wich is now

**Comment by Eumiella** [comment]
Dev's top priority right now is the settings maybe after he's finished working on the app's settings he'll work on light novels

**Comment by XxMCBxX** [comment]
https://youtu.be/9ryRnk9pLw0 go to 8:39

**Comment by Eumiella** [comment]
Already watched that video, like I said dev is still working on the app settings

**Comment by XxMCBxX** [comment]
Do i leave this or do i close the isue idk what to do?

**Comment by XxMCBxX** [comment]
So did they add the notification yet?

**Comment by brahmkshatriya** [comment]
the issue will be closed when it is added

**Comment by XxMCBxX** [comment]
It's been 2 months since I added this ad it's still not added.
When is it going to come out because I can't wait anymore.
Aniyomi started to be boring.

**Comment by Eumiella** [comment]
Be patient, dev is working on a lot of things right now. Feel free to join their discord and ask the people there when it's going to be added.

**Comment by Eumiella** [comment]
Use 3rd party apps like al chan for notifs
