### ISSUE TITLE
ComickFun issue

### ISSUE THREAD

**Issue by SunglassJerry** [saikou-app/saikou#601]
### Summary

It doesn't load the first few chapters for the selected manga.

### Reproduction Steps

Go to any manga with more than 100 or more chapters. Select comick as source.

### Expected Result

All chapters should load properly.

### Actual Result

First few tens of chapter doesn't load

### Device Information

‎‎‎‎‎‎‎‎ㅤ 

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

I think it would be better if you can make the app organise chapter divisions a little better. It's like 1st category is 1-25, 2nd is 26-53 3rd is 54-71. All are kinda messed up

**Comment by TobyBridle** [comment]
I've fixed this and am just about to do a PR.
