### ISSUE TITLE
Download Unsuccessful Error When Downloading

### ISSUE THREAD

**Issue by megamorphg** [saikou-app/saikou#609]
### Summary

When I click the download button it says "Download Unssuccesful". Viewing normally works fine.

### Reproduction Steps

1. Go to Attack on Titan
2. Select Marin source
3. Click 1st episode
4. Click any download button

### Expected Result

Successful download

### Actual Result

Unusuccessful download

### Device Information

Saikou Version: 1.2.1.0
Device: samsung d2q
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

I am guessing this is because of a lack of download permission? It never asked for permission. I manually enabled in the settings for the media location (Android 12 only allows media location unless app requests specific directories). Also tried SD card option and get same message.

**Comment by Sam13789** [comment]
Download 1dm and select default download manager to 1dm from settings/common/download manager. Also after installing 1dm give storage storage permission to 1dm and then download from saikou app

**Comment by brahmkshatriya** [comment]
Unable to reproduce, device : pixel 3, android : 12
& seems like resolved
