### ISSUE TITLE
Gogo server  is not working

### ISSUE THREAD

**Issue by Kuronagi** [saikou-app/saikou#612]
### Summary

Also zoro sever is having some issue plzz see through this trouble which i al going through

### Reproduction Steps

🥲
No i was just watching and suddenly it happen

### Expected Result

. 

### Actual Result

. 

### Device Information

Saikou Version: 1.2.1.0
Device: POCO miel
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

.

**Comment by brahmkshatriya** [comment]
Unable to reproduce, 
both gogo & zoro are working
I suggest using vpn or changing dns from settings

**Comment by Kuronagi** [comment]
Ohh u r right
