### ISSUE TITLE
The manga chapters read not updating

### ISSUE THREAD

**Issue by NoxBurst** [saikou-app/saikou#614]
### Summary

After reading manga the chapters read is not updating on the homescreen

### Reproduction Steps

I read the manga a lot of chapters

### Expected Result

On the chapters read on the homescreen the number of chapters i read should be displayed

### Actual Result

It stays zero eventhough i read more than 100 chapters of manga

### Device Information

Saikou Version: 1.2.1.0
Device: samsung m30s
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

The chpters should be updated so that i can keep track of how much i read (anime episode count works without any problem)

**Comment by scrazzz** [comment]
Are you logged into AniList or MAL?

**Comment by SunglassJerry** [comment]
Scruz ignorance kawaii (//ω//)
