### ISSUE TITLE
Animesuge.to

### ISSUE THREAD

**Issue by vamshidhar1211** [saikou-app/saikou#617]
### Summary

adding animesuge to streaming sources

### The Problem

in previous versions of saikou 9anime sources is avaliable but cruently removed due to isp blocked in many country's as well as other reasons. animesuge will be perfect replace for 9anime as you know animesuge website is scrapped from 9anime with unique features.

### The Ideal Solution

i hope animesuge.to source is added in future update

**Comment by vamshidhar1211** [comment]
i think this can't be scrapped

**Comment by brahmkshatriya** [comment]
Animesuge is 9anime

**Comment by vamshidhar1211** [comment]
> Animesuge is 9anime

yes it is .9anime is isp blocked in many countries so adding animesuge in streaming sources would be appreciated
