### ISSUE TITLE
Couldn't find any file manager to open sd card

### ISSUE THREAD

**Issue by Spencer089** [saikou-app/saikou#619]
### Summary

I activated the Download on sd card cuz i don't have enough space left on my internal, but when I click the downloads it says "Couldn't find any file manager to open sd card"

### Reproduction Steps

By clicking the Download

### Expected Result

To open it

### Actual Result

some error suddenly occurred

### Device Information

1.2.1.0
Oppo
arch64
android 5.0

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment]
Try this: https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files

**Comment by Spencer089** [comment]
it still doesn't work

**Comment by brahmkshatriya** [comment]
seems like device only issue, will reopen someone else gets it
