### ISSUE TITLE
GOGO not working, tried all DNS servers!

### ISSUE THREAD

**Issue by calmhero** [saikou-app/saikou#621]
### Summary

For multiple anime, I tried using GOGO but it didn't work. At first I thought maybe my ISP is blocking links, so I changed DNS & tried every DNS but not working. BTW, GOGO website works good in Browser & without VPN (my ISP isn't blocking it). So I guess there's some problem with the Gogo Scrapper.

### Reproduction Steps

**1. Searched for Vinland Saga**

**2. Went to Watch Menu & Selected GOGO**

**3. It took 15-20 seconds & finally it said 'Couldn't find anything x( Try another source'**

![Screenshot_20230329-200239](https://user-images.githubusercontent.com/106139532/228579486-0beef940-3b73-42d9-8dc6-5b7a56ee618d.png)

**4. Changed DNS, Restarted the Saikou app & tried again. (Note- I repeated the Step 4 with Every DNS available in Settings of Saikou app)**

### Expected Result

Expected that GOGO show the Episodes of that anime 
i.e. Vinland Saga S1.

### Actual Result

`Couldn't find anything x( Try another source`

### Device Information

Saikou Version: 1.2.1.0
Device: motorola cypfq
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [x] I have searched the open AND closed issues for any duplicates.

### Additional Information

Gogo site works in browser, but the Saikou app experience is on another level. Also, GOGO as a source is the best one for me because it consumes less data than other sources (like Marin for eg.) and gives the same quality in lesser MB.

I would appreciate if you get GOGO to work in the next release. Also, GOGO has good download system (aniHDplay) - if you can add that one too, then GOGO will be the best source in Saikou app for many users.

**Finally, thanks to all the contributers to make 'The Best' app for Anime & Manga. The UI is the best one I've ever used, even better than Hotstar & Netflix's UI. You guys work selflessly for us and give us a great Anime watching & Manga reading experience for free, that I can't thank you enough. Thank you all.**

**Comment by brahmkshatriya** [comment]
Better use another server or use a vpn, gogo is working on my end

**Comment by calmhero** [comment]
Now it's working, after New Update. Without any DNS.
