### ISSUE TITLE
KickAssAnime or Kaas.AM isn't available in Sources, but on GitHub page it says it is working.

### ISSUE THREAD

**Issue by calmhero** [saikou-app/saikou#623]
### Summary

KickAssAnime is a great source with multiple quality options and fast servers. On the GitHub page of Saikou, it says KickAssAnime is working (in Available Anime Sources). But it is NOT available in the App.

### Reproduction Steps

**Went to the GitHub page of Saikou to see Available Anime Sources.**

**Went to the app to find KickAssAnime but isn't available.**

### Expected Result

KickAssAnime or Kaas.AM as a Source in Anime.

### Actual Result

KickAssAnime not available in Sources.

### Device Information

Saikou Version: 1.2.1.0
Device: motorola cypfq
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

I hope you'll add KickAssAnime & if you've updated the page and KAAS is coming in next update, then I'm waiting eagerly.

Also, a Bug in Saikou is that, when minimized and opened again, sometimes it Cuts the Open/Watch button in half (maybe because of Full-screen).

**Comment by Adolar0042** [comment]
Kickassanime are currently doing changes to their site, so we've temporarily disabled the source
