### ISSUE TITLE
Possibility of deactivating the app's Google Tracker

### ISSUE THREAD

**Issue by Daniele1012** [saikou-app/saikou#633]
### Summary

Disable Google tracker

### The Problem

When browsing the Saikou app, RethinkDNS (app to block advertisements and trackers) shows some Google trackers from Saikou

![Screenshot_20230405-144136-01](https://user-images.githubusercontent.com/129958621/230084781-b0e76f7e-ccec-4d05-999d-499df18946f6.jpeg)

![Screenshot_20230405-144627-01](https://user-images.githubusercontent.com/129958621/230084812-682e7518-88ad-476e-88ef-1c381508fb92.jpeg)

### The Ideal Solution

An option to disable these trackers

**Comment by brahmkshatriya** [comment]
googesads? huh 🤨
Can you check on original saikou, & not saikou IT

**Comment by scrazzz** [comment]
Saikou uses YouTube to play the anime trailers. Hence the Google ads.

**Comment by brahmkshatriya** [comment]
ah, ig so
Yea so thats out of our hands,
Also dont plan to remove firebase anytime soo

**Comment by brahmkshatriya** [comment]
> Sorry for the insistence 😅
> 
> But add at least an option to use some frontend alternative like Piped or Invidious instead of YouTube?

That alone would increase the app size by 2mb, so yea i preferred using the actual embed provided by YouTube

Also i do not get, how is that interfering with your privacy, the "ad data" is limited within saikou's webview, it doesn't know who you are

And as for "ads" themselves, they are most likely in the background, afaik youtube doesn't show ads on embeds

**Comment by soymadip** [comment]
> > Sorry for the insistence 😅
> > 
> > But add at least an option to use some frontend alternative like Piped or Invidious instead of YouTube?
> 
> That alone would increase the app size by 2mb, so yea i preferred using the actual embed provided by YouTube
> 
> Also i do not get, how is that interfering with your privacy, the "ad data" is limited within saikou's webview, it doesn't know who you are

With all respect i wanna ask one thing, doesn't all of the Google's tracker services like double click or firebase can access your android's advertisement id? 
That way can't this be a little non-privacy friendly?

Pardon of i am wrong, I'm just little curious 🙂
