### ISSUE TITLE
9anime sub and dub 

### ISSUE THREAD

**Issue by Amoureaux** [saikou-app/saikou#635]
### Summary

Basically it randomly turned into dubbed and I can't find any way to change it

### Reproduction Steps

1. Change server to Consume9anime
2. Hope that it happens because it's seemingly random 

### Expected Result

Not this

### Actual Result

This

### Device Information

Saikou Version: 1.2.1.2
Device: Redmi merlinnfc
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
wait for update
