### ISSUE TITLE
Zoro.to videos buffering a lot

### ISSUE THREAD

**Issue by iamdhar** [saikou-app/saikou#636]
### Summary

There is a lot of buffer in the videos from zoro website. 

### Reproduction Steps

Start watching any video through the zoro server

### Expected Result

Normal to no buffer while watching

### Actual Result

The video stops in every 5-10 seconds for buffering

### Device Information

Saikou latest version
Android 12

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by iamdhar** [comment]
I know its not my internet because animapahe source is working fine. I can use that instead but because the episode names, i wanted to use zoro

**Comment by iamdhar** [comment]
![Uploading Screenshot_20230409-205734.png…]()

**Comment by iamdhar** [comment]
![Screenshot_20230409-205734](https://user-images.githubusercontent.com/87235606/230781817-71505a62-abb3-4643-930f-1d7772fd871f.png)
This is an example, the video is not using the internet fully to buffer and gets stuck in the opening

**Comment by brahmkshatriya** [comment]
Tell that zoro's site, not here

**Comment by iamdhar** [comment]
> 

My guy the videos are loading fine on the website only in the app there is the issue

**Comment by MustardChef** [comment]
Very sad moment
