### ISSUE TITLE
Gogo - Stream SB showing live stream

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#637]
### Summary

It show a different kind of video instead of the anime

### Reproduction Steps

When I Change my Quality in GOGO StreamSB server it changes to a Korean stream of a Woman

### Expected Result

I would be able to Change my Quality of my Video without changing The video itself.

### Actual Result

The video on the streamsb Server change when I Change my Quality Of video

### Device Information

Saikou 1.2.2.0
Vivo 1606
1.4GHz Snapdragon 425 Quad-core 
Android 6.0.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![Screenshot_20230410_004903](https://user-images.githubusercontent.com/107057902/230786968-08721aa2-92e5-4bf8-9086-8d16960ccbef.jpg)

**Comment by Adolar0042** [comment]
Sounds like an error on gogo's end, can you check their website?

**Comment by brahmkshatriya** [comment]
Wtf 😂
Show which anime it gogo selected (the text above source tab in watching page)

**Comment by Nevenon** [comment]
> Sounds like an error on gogo's end, can you check their website?

Yeah I checked but it's the anime that is showing at every kind of server in gogo

**Comment by Nevenon** [comment]
> Wtf 😂 Show which anime it gogo selected (the text above source tab in watching page)

Yeah hahaha this thing is so random sometimes

**Comment by brahmkshatriya** [comment]
Not a problem on saikou's end
But damn this is funny

**Comment by Nevenon** [comment]
> Not a problem on saikou's end But damn this is funny

Yeah I just want to watch my Tokyo Ravens hahaha
