### ISSUE TITLE
No start & finish date in MAL?

### ISSUE THREAD

**Issue by KhaiCo** [saikou-app/saikou#641]
### Summary

After I started watching an anime, although my anime list did update to watching the start date did not,  this is not the case with Anilist which updates correctly

### Reproduction Steps

So I just started watching a planned anime in my list and so the status changed from planning to watching and the start date was added, and when I was done watching and set it to completed a finish date was added, and it should've synced with both tracking account.

I also tried changing an existing date which also did not update specifically in MAL

### Expected Result

The start and finish date syncing in both tracking accounts, both Anilist and MAL

### Actual Result

Only Anilist synced correctly while MAL only synced the status and leave the dates blank

### Device Information

Saikou Version : 1.2.2.0
Brand : Xiaomi POCO
Android Version : 12

### Checklist

- [x] I have searched the open AND closed issues for any duplicates.

### Additional Information

Sorry if this is not the correct use of the bug report

**Comment by brahmkshatriya** [comment]
Tell mal to fix their API 👍

**Comment by KhaiCo** [comment]
But I'm pretty sure in apps like Tachiyomi and the anime fork Aniyomi the date synced correctly? (Sorry if it offends anyone that I'm making a comparison)

**Comment by brahmkshatriya** [comment]
> But I'm pretty sure in apps like Tachiyomi and the anime fork Aniyomi the date synced correctly? (Sorry if it offends anyone that I'm making a comparison)

I did look into their stuff, i had got it working on my end too
But for some unknown reason the API just decided to not change stuff on the server when requesting using post while providing dates, it does respond with 200

Now i have no idea what's going on there
