### ISSUE TITLE
Can't read anilist 

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#643]
### Summary

The loading of my playlist is slow and an error 

### Reproduction Steps

Maybe when I Cancelled my favorite anime and reload the page

### Expected Result

I would see my list and watch again

### Actual Result

I can't see my Anime list and the App is saying perhaps your internet sucks? And can't read anilist account 

### Device Information

Saikou 1.2.2.0
Vivo 1606
Snapdragon 425 Quad-core 
Android 6.0.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

/
![Screenshot_20230413_025949](https://user-images.githubusercontent.com/107057902/231559266-0d78be18-7c03-4c0d-92f0-b56ed4cecc41.jpg)
![Screenshot_20230413_025928](https://user-images.githubusercontent.com/107057902/231559287-dbd9f578-b73d-4571-9ec0-2c409bfa94ac.jpg)
![Screenshot_20230413_025931](https://user-images.githubusercontent.com/107057902/231559307-78696516-ebbd-4428-9e69-5f6453acfe81.jpg)
![Screenshot_20230413_025930](https://user-images.githubusercontent.com/107057902/231559327-29149bb7-3675-471e-a03b-29def3b8e6c6.jpg)

**Comment by brahmkshatriya** [comment]
Anilist is going through some downtime
