### ISSUE TITLE
Zoro: quality selection doesn't work in player, stuck on default "Auto" selection.

### ISSUE THREAD

**Issue by Seth1singh** [saikou-app/saikou#648]
### Summary

Quality selection doesn't work for any selected multi quality server of Zoro.

### Reproduction Steps

Select any anime> source Zoro> select any multi quality server> when player opens click quality change button> try changing quality to any available options.
![Screenshot_2023-04-14-17-55-35-319](https://user-images.githubusercontent.com/130760333/232046470-79431658-21a9-4784-8cf9-588fa4ff3a5f.jpeg)

### Expected Result

You should be able to change quality just like any other source.
![Screenshot_2023-04-14-18-06-35-267](https://user-images.githubusercontent.com/130760333/232046767-d61bc230-5b20-433c-b030-f26c11b854d1.jpeg)

### Actual Result

Can't select to any available quality. Its stuck on Default "Auto" selection.
![Screenshot_2023-04-14-17-55-35-319](https://user-images.githubusercontent.com/130760333/232047340-086d57d0-bdce-4f33-84e0-7ed6a48b4c5d.jpeg)

### Device Information

Saikou Version: 1.2.2.0
Device: Lenovo TB-7304F
Architecture: aarch64
OS Version: REL 7.0 (24)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Thats why the N/A is added, cuz zoro streams are a bit fucked
