### ISSUE TITLE
Add Share button.

### ISSUE THREAD

**Issue by gaminglnk** [saikou-app/saikou#650]
### Summary

Just a request to add Share button to share, either Anilist or Mal links directly from the app.

### The Problem

In case of sharing the links, It requires to externally get it from the Anilist or Mal website.

### The Ideal Solution

Just listing the anime/manga link withing the app as a button would be great.

Although, I am just providing a suggestion for implementing this; it all depends on y'all.

**Comment by scrazzz** [comment]
Already exists 
![balls](https://user-images.githubusercontent.com/70033559/232182212-3cfc725e-e6a2-4fa9-825a-71e4b66b9f2d.jpg)

**Comment by brahmkshatriya** [comment]
balls

**Comment by gaminglnk** [comment]
my bad!!!

> balls
