### ISSUE TITLE
date remover for past anime?

### ISSUE THREAD

**Issue by KhaiCo** [saikou-app/saikou#652]
### Summary

Removing/leaving the date blank for an anime that was completed in the past before saikou

### The Problem

So if I am documenting/listing past anime that I've watched before using saikou and any kind of anime list and I set it to completed the start and end date is automatically set to today's date with no way to remove the date or leave it blank because there is no way to know the exact date that I start/finished it in the past

### The Ideal Solution

Adding a way after setting it to completed to just remove the automatically set date and leave it blank

### The Current Solution

No way to remove it from the app so I have to go to MAL and Anilist to remove it directly

### Additional Context

I use both Anilist and MAL so it's quite the problem to keep going to their respective website to remove the date because leaving the start and finish date in today's date doesn't sit quite right 😅

**Comment by brahmkshatriya** [comment]
Instead of editing list by opening the anime/manga
Try long clicking the anime/manga's thumbnail, This will open a mini list editor, which doesnt contain Dates
This should probably prevent adding dates for both anilist & mal

**Comment by KhaiCo** [comment]
I see I've tried it out, but it seems like it still is listed with today's date

I wanted to send screen recording but it seems that I can't so here's some screenshots 


![Screenshot_2023-04-17-17-11-52-543_ani saikou beta](https://user-images.githubusercontent.com/130490107/232455341-f008def5-d776-4b21-a9e0-673e72478353.jpg)
![Screenshot_2023-04-17-17-12-02-125_com android chrome](https://user-images.githubusercontent.com/130490107/232455353-cc31bb5d-c00b-4801-a79f-3857c52c7d94.jpg)

**Comment by brahmkshatriya** [comment]
ah actually, thats being set by anilist itself automatically, So welp cant really handle that one
