### ISSUE TITLE
[Suggestion] add  trending now and popular this season 

### ISSUE THREAD

**Issue by ShiSix** [saikou-app/saikou#66]
If possible add trending now and popular this season anime list with popular anime list.
![Screenshot_20220320-152550_Iceraven](https://user-images.githubusercontent.com/101547113/159157258-d26181b5-8a7d-47df-8ae2-3daeaafd3cf9.png)
and remove watched/completed anime from popular anime
![Screenshot_20220320-153230_Saikou](https://user-images.githubusercontent.com/101547113/159157335-59e2a089-41d4-427f-8c1e-a62cb1594e49.png)

**Comment by brahmkshatriya** [comment]
Trending now, is already there.
And popular this season is rejected.
