### ISSUE TITLE
Add episode releases to android calendar

### ISSUE THREAD

**Issue by RuboGubo** [saikou-app/saikou#664]
### Summary

Android has an API which can be used to create events in a calendar for a specific app.

### The Problem

This would help integrate the app more into the android ecosystem, and can also then be displayed on widgets provided by various android calendar apps.

Example events could be:
- When the next episode of an anime is released
- When the next issue of a manga is released
- At what date upcoming anime will begin releasing
- etc.

### The Ideal Solution

Add the dates of releasing anime/manga to the android calendar

**Comment by brahmkshatriya** [comment]
It's a cool idea, but I don't particularly find it being used by people
So, I am rejecting it

Thanks for the suggestion
