### ISSUE TITLE
Consume 9anime Not working 

### ISSUE THREAD

**Issue by AnimeCracker** [saikou-app/saikou#670]
### Summary

Consume 9anime source not working 

### Reproduction Steps

Hello,

When I try to use the Consume 9anime source it gives some kind of error please fix it.

Sincerely,

AnimeCracker

### Expected Result

Just for the source to work properly like the others.

### Actual Result

Not working.

### Device Information

Saikou Version: Latest
Phone: Xiaomi note 10 pro
Android version: 11

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Please help.

**Comment by brahmkshatriya** [comment]
already fixed, 
use https://github.com/saikou-app/saikou/suites/12715975554/artifacts/682853426

**Comment by AnimeCracker** [comment]
Thank you
