### ISSUE TITLE
Manga4Life :  Omniscient Reader chapter 156

### ISSUE THREAD

**Issue by Vortex786** [saikou-app/saikou#672]
### Summary

Webtoon page not displaying even though it is there and can be downloaded.

### Reproduction Steps

1. Open Omniscient Reader chapter 156.

### Expected Result

-

### Actual Result

-

### Device Information

Saikou Version: 1.2.3.1
Device: motorola nicklaus_f
Architecture: arm
OS Version: REL 7.1.1 (25)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![Screenshot_20230508-194336](https://user-images.githubusercontent.com/111473779/236849460-cd2f6b85-c6ea-4e52-9523-63b18dfc49a9.png)

![Screenshot_20230508-194348](https://user-images.githubusercontent.com/111473779/236849770-a5d28f88-f307-46fa-b85e-04742745a99c.png)

**Comment by rheemarc15** [comment]
Same issue can't read the chapters for Wind Breaker, Solo Leveling and other Manhwa

**Comment by brahmkshatriya** [comment]
Cannot confirm, all of the manhwa mentioned are working on my end
