### ISSUE TITLE
sort by number of unread chapters

### ISSUE THREAD

**Issue by imeed166** [saikou-app/saikou#674]
### Summary

new sorting option in the manga list "by unread chapters"

### The Problem

When viewing my manga list, I want to see the manga that have unread chapters, so I want to the manga with most/least number of unread chapters to be appear at the top.

### The Ideal Solution

have that sort available with the number of chapter not read for each manga like this example from malysinc chrome extension 
![image](https://github.com/saikou-app/saikou/assets/38974541/9c0c74af-73c7-4959-868c-0868183fa3c9)

![Screen Shot 2023-05-12 at 4 05 56 PM](https://github.com/saikou-app/saikou/assets/38974541/1e5c81eb-67bc-4f2e-89aa-8b7e7383806b)

### The Current Solution

manually search for the manga you want to read,

**Comment by brahmkshatriya** [comment]
what site/app is that? where is it getting the total number of chapters released?
It's not possible for saikou to do this, as the total number of chapters that are released are unknown to saikou until the manga is opened

**Comment by imeed166** [comment]
I see, here is the app, it's chrome extension https://malsync.moe/
