### ISSUE TITLE
Wrong source for Hentai

### ISSUE THREAD

**Issue by itachi-9282** [saikou-app/saikou#675]
### Summary

All sources are streaming wrong media for hentai.

### Reproduction Steps

I first clicked on anylist settings and moved to anime & manga section, on that section I viewed 18+ content check box. 

When I checked that box, I can see a new genre added to my anime list which was "hentai" 

### Expected Result

I expected after clicking a hentai show, when I select any source I should view the video related to that particular show which I select. 

It should show all the episodes which are released for the show

It should show the source like example hanime, hentaiheven, etc. 

### Actual Result

After selecting hentai genre when I started viewing a hentai,
I checked that all the sources are providing wrong media and there was no correct  source for viewing hentai.

Some of the source searched one piece when I was on hentai section. And some was showing only one video instead.

### Device Information

Saikou version: 1.2.3.1
Brand: Iqoo
Architecture: 64bit
Android Version: 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Adolar0042** [comment]
Unfortunately saikou doesn't always get the correct result automaticalls, so sometimes you have to manually find the correct show with the "Wrong Title?" button. It should be right below the source name.

**Comment by itachi-9282** [comment]
I already did that as well still it's wrong media....

**Comment by Adolar0042** [comment]
Hmm, then either the sites don't have it, or it goes by a different name on them

**Comment by itachi-9282** [comment]
It goes to different name totally whole new anime.......,  Some hentai media is coming correct when searched with wrong title...
