### ISSUE TITLE
Nineanime not working 

### ISSUE THREAD

**Issue by AnimeCracker** [saikou-app/saikou#678]
### Summary

9anime source not working 

### Reproduction Steps

I think there is a new bug with the source.

### Expected Result

For it to work.

### Actual Result

It didn't work.

### Device Information

Saikou Version : latest beta debug
Mobile: Xiaomi note 10 pro

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by givemyusd** [comment]
Its working now
