### ISSUE TITLE
Player's brightness and volume not functioning 

### ISSUE THREAD

**Issue by Yahya98** [saikou-app/saikou#68]
I honestly have no idea how did it happen but after watching several dozen of episode, the player's gesture control of volume and brightness just stopped working for me.

I tried to restart the app and even restart my phone, and it doesn't fix the problem.

I wish I can provide more detail about how to reproduce the problem, but I don't think I did something extraordinary other than watching animes. Well, aside from the fact that I actively change volume and brightness while watching anime... Then that's it.

**Comment by brahmkshatriya** [comment]
Will be fixed in the next update
