### ISSUE TITLE
System Font

### ISSUE THREAD

**Issue by MrigendraB** [saikou-app/saikou#680]
### Summary

Option to let the app use system font 

### The Problem

Different types of users like different type of fonts and OEMs give an option to set a custom font in their custom skins/UIs. Saikou app would look visually more appealing with the font user want and will give a sense of uniformity among the apps user have.
(For me it is SegoeUI Variable font).

### The Ideal Solution

An option to use system font through-out the app or a font picker which import font files from system storage.

**Comment by brahmkshatriya** [comment]
I don't I'll be adding that support to do that
But if you really want to do it

All you need to do is change font in
https://github.com/saikou-app/saikou/blob/main/app/src/main/res/font/poppins_family.xml

That would be the easy way to do it

And if you want to totally add a separate font, you would need to change the font in every layout, so yeah good luck

**Comment by brahmkshatriya** [comment]
another way to change it is through changing the fonts in themes, but that won't work for some layouts

Since most layouts use the default font in the theme
But i had to manually put some different fonts for some layout, so changing stuff here will cause inconsistency

**Comment by MrigendraB** [comment]
> I don't I'll be adding that support to do that But if you really want to do it
> 
> All you need to do is change font in https://github.com/saikou-app/saikou/blob/main/app/src/main/res/font/poppins_family.xml
> 
> That would be the easy way to do it
> 
> And if you want to totally add a separate font, you would need to change the font in every layout, so yeah good luck

Oh! No problem then. I don't have any knowledge of codes and how github works but still I would want to tinker with it and will see if I could make any change regardless of how long willl take.
