### ISSUE TITLE
Add anime-world.in as a source

### ISSUE THREAD

**Issue by Aeropro4** [saikou-app/saikou#688]
### Summary

Pls add anime-world.in cause it has hindi language 

### The Problem

There's no source that provides hindi language anime

### The Ideal Solution

This will add it 👍

### Additional Context

It just looks like any other site and is direct not much ad

**Comment by scrazzz** [comment]
Read https://github.com/saikou-app/saikou#rejected-stuff

**Comment by Aeropro4** [comment]
Wait with "Sources of any language except English" do u mean the website language or the anime's?

**Comment by scrazzz** [comment]
Both

**Comment by Aeropro4** [comment]
😐
