### ISSUE TITLE
Manhwa and manhua

### ISSUE THREAD

**Issue by Gitzoid01** [saikou-app/saikou#689]
### Summary

Additional manhwa and manga category 

### The Problem

I like to request you to add manhwa and manhua and webcomic category to your app that will be very helpful full. I hope you will work on that and provide your best
All the best for your future 

### The Ideal Solution

Add that manhwa and manhua category in app

**Comment by brahmkshatriya** [comment]
Manga category contains both manga & manwha
Please atleast use the app before making an issue
