### ISSUE TITLE
Video Player - Stuck Ripple Effect

### ISSUE THREAD

**Issue by VipulOG** [saikou-app/saikou#691]
### Summary

When performing a seek gesture (double-clicking) to skip forward or backward within the video player, a visual glitch occurs where the ripple effect, becomes stuck on the video. This issue only occur when the animation scale from the developer options is set to a value greater than 1.

### Reproduction Steps

1. Select "Developer options" in device settings.
2. Locate "Window animation scale," "Transition animation scale," and "Animator duration scale" settings and Set the value to greater than 1 (e.g., 1.5 or 2).
3. Play any video in Saikou.
4. Perform a seek gesture by double-clicking on the left or right side of the video player.
5. Observe that the ripple effect, becomes stuck on the video, persisting as a black overlay.

### Expected Result

The ripple effect should be displayed briefly and then vanish after performing seek gesture.

### Actual Result

Performing a seek gesture in the video player causes the ripple effect to become stuck on the video.

https://github.com/saikou-app/saikou/assets/90324465/40eeedef-6e4f-4c4b-bba1-a35dfc0e2784

### Device Information

Saikou Version: 1.2.3.1
Device: samsung m21
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Thats very helpful, thanks for making the issue & mentioning how to reproduce it

**Comment by VipulOG** [comment]
I have identified the cause of this issue.

In the file ExoplayerView.kt at line 1435:
https://github.com/saikou-app/saikou/blob/main/app/src/main/java/ani/saikou/anime/ExoplayerView.kt#L1435
we start animation(for showing ripple) for 800ms, which sets the view's alpha to 1.

Then, at lines 595-600
https://github.com/saikou-app/saikou/blob/main/app/src/main/java/ani/saikou/anime/ExoplayerView.kt#L595-L600
using a ResettableTimer, we call the stopDoubleTapped after a 750ms delay which will start animation for hiding ripple.

Finally, at line 1442
https://github.com/saikou-app/saikou/blob/main/app/src/main/java/ani/saikou/anime/ExoplayerView.kt#L1442
we start animation(for hiding ripple) for 150ms, setting the alpha to 0.

Since ResettableTimer does not consider animation scale, its duration remain unchanged.

The issue arises when the device's animation scale is set to a high value. This causes the show animation duration to increase significantly, exceeding the delay of 750ms plus the duration of the hide animation. Meaning hide animation will finish before show animation.

I am new on GitHub, this is my first issue, and I really love Saikou. I would like to contribute further. If you don't mind, I can open a pull request to address this issue.

**Comment by brahmkshatriya** [comment]
Yea i will really appreciate a good PR to fix this

Also before this issue, I thought ObjectAnimator actually changed the value of the view after it is done animating, apparently it doesn't
