### ISSUE TITLE
Consume 9anime isn't working

### ISSUE THREAD

**Issue by DreamChasr** [saikou-app/saikou#696]
### Summary

Whenever I select 9anime as the source it says "Field 'results' is required for type with serial name 'ani.saikou.parsers.anime.Consume9Anime.SearchResponse', but it was missing at path: $"

### Reproduction Steps

1. Select an Anime, in ny case it was Pokemon: Horizons and Bleach
2. Select Consume 9anime as the source

### Expected Result

The list of episodes for that anime to load

### Actual Result

The following error appeared:

Field 'results' is required for type with serial name 'ani.saikou.parsers.anime.Consume9Anime.SearchResponse', but it was missing at path: $"

### Device Information

Saikou Version: 1.2.3.1
Device: Xiaomi cupid
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by sam-gq** [comment]
That's the same thing still. I also like to bring back that server, it was still broken 2 months ago.

**Comment by brahmkshatriya** [comment]
should be fixed in the latest push
