### ISSUE TITLE
Allanime source slowly not working

### ISSUE THREAD

**Issue by Kuuhakuxx** [saikou-app/saikou#698]
### Summary

Missing other allanime links

### Reproduction Steps

![Screenshot_20230605_202840_Saikou ](https://github.com/saikou-app/saikou/assets/122075694/a40b87bc-1fb8-4bfa-bd73-119184d8d988)

### Expected Result

Only two link are available but not others

### Actual Result

..

### Device Information

Saikou version: 1.2.3.1
Model: Samsung s10 plus

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Spot-nabil** [comment]
Marin and some other links are also not working for me.

**Comment by sam-gq** [comment]
Here is the toast message when pressing the episode in the allanime server. That was an error.
![Screenshot_20230605-231317~01](https://github.com/saikou-app/saikou/assets/80607823/8a994d42-6c70-4c59-873a-396133f27b5e)
![Screenshot_20230605-231232~01](https://github.com/saikou-app/saikou/assets/80607823/1abf3023-e271-4f86-bfca-9aeb6d97cf5c)

**Comment by Kuuhakuxx** [comment]
Link also not appearing in the non beta version
