### ISSUE TITLE
Characters and Media Info in Video player

### ISSUE THREAD

**Issue by VipulOG** [saikou-app/saikou#699]
### Summary

Proposal for a feature to display character and media information directly in video player.

### The Problem

Currently, when a user wants to identify a character or check some other info, they have to exit the video player and navigate back to the media info screen. This interrupts the viewing experience and requires buffering again when the video is resumed.

### The Ideal Solution

I suggest implementing a feature within the video player that allows users to easily access character and media information without leaving the player. This could be achieved by adding an information overlay.

### Additional Context

AnYme used to have similar feature like this:
https://www.reddit.com/r/anYme/comments/eddmzg/vydia_new_builtin_video_player_for_anyme/
![images (3)](https://github.com/saikou-app/saikou/assets/90324465/310a399d-93e4-427f-96f1-0396d97c30f2)

**Comment by VipulOG** [comment]
If people are interested in this feature, I can open a pull request.

**Comment by brahmkshatriya** [comment]
I personally think it will crowd the video player, so I'd prefer not adding this

**Comment by VipulOG** [comment]
> I personally think it will crowd the video player, so I'd prefer not adding this

Maybe we can add an Info button to show the overlay and add option to hide the button from player in player settings?

**Comment by brahmkshatriya** [comment]
hmm well depends on where you place it

**Comment by VipulOG** [comment]
> hmm well depends on where you place it

Somthing like this?
![PlayerPaused](https://github.com/saikou-app/saikou/assets/90324465/92ac7404-0b37-4a1f-89bc-33711e56f40e)
![PlayerMediaInfo](https://github.com/saikou-app/saikou/assets/90324465/6788858d-a4e4-409e-a864-19c91a21d019)
![SettingsScreen](https://github.com/saikou-app/saikou/assets/90324465/16bd0923-ddef-413f-bdb6-6c0a36f7b45f)

**Comment by brahmkshatriya** [comment]
okay yea thats fine, I recommend 2 things

- putting the button to top-left corner
- changing that ugly fat close button

**Comment by VipulOG** [comment]
> okay yea thats fine, I recommend 3 things
> 
> * putting the button to top-left corner
> * changing that ugly fat close button
> * putting fading edges on the recyclerview of characters (but ig yours is just a prototype)



Yes, it was a quick prototype. I will change the close button. Also, which button are you suggesting to move to top-left corner? The info button or the close button?

**Comment by scrazzz** [comment]
@VipulOG Do you mind if you could discuss about this over [discord](https://discord.gg/2T7TunuwFZ)? Would be a lot easier to get feedback from the other devs.

**Comment by VipulOG** [comment]
Closing for now.
