### ISSUE TITLE
Anime Source Suggestion

### ISSUE THREAD

**Issue by SamarthMehta** [saikou-app/saikou#7]
First of all i have got a lot of suggestions to add for the source, the one with (.) Will be important, atleast for me!

1- Animixplay (.)
2- AnimePahe(.)
3- ArrayAnime(.)
4- Genoanime
5- YugenAnime

And lastly the zoro source in the app isn't working! 

That's it i hope you can add all the above sources!
Bye!

**Comment by brahmkshatriya** [comment]
> 2- AnimePahe(.)
Only animepahe will be added.
All others are just scraping from other websites.
for VRV streams I plan to add allanime.site

wait for update, to get zoro working
