### ISSUE TITLE
App response time is slow. 

### ISSUE THREAD

**Issue by rayn000** [saikou-app/saikou#7]
Response is slow for almost all actions.
The app is in early stage I guess, so it needs so many features. I know that the devs also know this.

**Comment by brahmkshatriya** [comment]
Can you explain, how is exactly is it slow? Does it take time to load trending anime/manga? Or does it take time load episodes? 

Please explain it

**Comment by rayn000** [comment]
> Can you explain, how is exactly is it slow? Does it take time to load trending anime/manga? Or does it take time load episodes?
> 
> Please explain it

It feels sluggish while using the app because the animation speed is slow.
Yes it does take time load the content of anime/manga. I'm using WiFi not mobile data.
I hope you understand what I'm trying to say.

**Comment by rayn000** [comment]
> Can you explain, how is exactly is it slow? Does it take time to load trending anime/manga? Or does it take time load episodes?
> 
> Please explain it

Yeah exactly. It takes time for loading contents of anime/manga and It does take time to load episode. For info I'm using WiFi.

**Comment by brahmkshatriya** [comment]
Uh, I would prefer you could message on the discord server or the telegram group

Also which version of the app are you on? Please try 1.0.6, it has some fixes that might make it faster

**Comment by rayn000** [comment]
Can you add ⭐animepahe.com⭐ and ⭐mangareader.to⭐. These are top sites for me. Check them out. If you like it please add them.

**Comment by rayn000** [comment]
> Uh, I would prefer you could message on the discord server or the telegram group
> 
> Also which version of the app are you on? Please try 1.0.6, it has some fixes that might make it faster

I am using 1.0.6.
OK I'll message on discord / telegram
