### ISSUE TITLE
Continues reeding

### ISSUE THREAD

**Issue by XxMCBxX** [saikou-app/saikou#70]
Is there going to be a way to just reed manga continuesly, like rn when i finish a chapter i have to close out of the chapter thene check it as read and thene open a new chapter thene again. Pls add a fix for that.

Thank you.

**Comment by XxMCBxX** [comment]
And i hope there will be a way if you do add the continues reedi that you dont have to maualy check that the chapter is read.

**Comment by brahmkshatriya** [comment]
duplicate of #18
