### ISSUE TITLE
"please verify you are not a robot" forever...

### ISSUE THREAD

**Issue by wangrocky** [saikou-app/saikou#700]
### Summary

register not finished due to "robot check" popup 

### Reproduction Steps

register and you can get this rediculous "please verify you are not a robot" popup, and can not finish registration. 

### Expected Result

register successfully. 

### Actual Result

can not register normally

### Device Information

sakou version: latest
android:12

![image](https://github.com/saikou-app/saikou/assets/6724040/645bc188-bfd6-4dee-8a7e-3005f7499412)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Thats an anilist problem, report to anilist
