### ISSUE TITLE
Gogo Banned: DNS not working & VPN gives error

### ISSUE THREAD

**Issue by calmhero** [saikou-app/saikou#701]
### Summary

When trying to play any anime from Gogo, it shows 'Connection Reset' error, same with EVERY DNS. After connecting NordVPN, it did load the episodes but gave error while Selecting Servers. I think Gogo is banned or dead totally. (Note - I use Indian ISP & I connected to Canada VPN using Nord but still it gave errors).

### Reproduction Steps

`1. Select Anime & Click Watch.
2. Select Gogo as a source.
3. It won't load episodes & give Timeout error as shown in the Screenshot below.
4. Same 'Connection Reset' error for every single DNS: Google, Cloudflare & AdGuard, all three aren't of any benefit.`

![Screenshot_20230610-221903](https://github.com/saikou-app/saikou/assets/106139532/fe46097d-793a-4a76-87bc-5eb9b2dbf237)

5. Finally set DNS to None, force stop the app & connect to VPN & try again.
6. This time it gives a long error which can't be seen as it hides under the Server Select pop-up, but can be seen by quickly clicking elsewhere on the screen to close the Pop-up. See the SS.

![Screenshot_20230610-221019](https://github.com/saikou-app/saikou/assets/106139532/58481602-5c80-4db1-aa12-0624d71f7a70)

### Expected Result

Being able to use Gogo source.

### Actual Result

Gogo doesn't work. Either it's banned in India or it is totally dead all over the world (can't access even via VPN).

### Device Information

Saikou Version: 1.2.3.1
Device: motorola cypfq
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

If gogo has changed server then update the source in next app update guys. 
BTW devs, I think the $1,000 goal has been reached, so are you working on Offline Manga Reader & Downloads features?

**Comment by meetsolanki8763** [comment]
Well I use proton vpn and use Netherlands server 
This happen with me too. So I just click on the anime and after it give error I close anime and Re open it and works for me (I use Indian isp too but I'm watching jojo)
