### ISSUE TITLE
Gogo Server links aren't available.

### ISSUE THREAD

**Issue by shahryarsalmaan** [saikou-app/saikou#706]
### Summary

I watch Dub anime with Gogo. I tried to watch it like I used watch using the Saikou App but it's now showing no links like the screenshot.

### Reproduction Steps

It's neither showing sub anime links too for Gogo sources.

### Expected Result

It should show the server to click and watch.

### Actual Result

I don't know why it's a happening.

### Device Information

Saikou Latest Version
Android: 10

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by awildredpanda** [comment]
I have had same issue and i looked into it and it seems as though the site saikou is trying to access is (https://gogoanime.cl) which currently is no longer up since its apparently been moved to (https://gogoanime.hu)
since i tried visting the old one and got redirected to the new domain

**Comment by Ninja51** [comment]
I have same problem with gogo no server, I think you need to update gogo to gogoanime.hu just as comment above said. Thanks 😊
