### ISSUE TITLE
Video Quality resets after the episode changes in multi quality server. 

### ISSUE THREAD

**Issue by Aeropro4** [saikou-app/saikou#707]
### Summary

When watching anime using a multi quality server/source its default goes to 720p and i have to change it everytime to 1080p and also when the episode changes the quality changes to its lowest aka 360p and its annoying to change it everytime. that's why i use a one quality server like animepahe but there's an anime called "death march to the parallel world rhapsody" and it has a lot of written content that only 9anime has dubbed while animepahe didn't but 9anime has multi quality servers only and idk if its only my phone which is doing it.

### Reproduction Steps

1. select a random anime.
2. select any source which has a multi quality server.
3. change the quality to 1080p if it is something else.
4. progress episode to the next and see if the quality changes to the lowest

### Expected Result

It should've been the same quality and didn't change to the lowest.

### Actual Result

it changes to lowest.

### Device Information

Saikou: 1.2.3.1
Brand: Samsung
Architecture: armv8a
Android version: 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Unable to reproduce, If someone else could confirm it, help will be appreciated
@Aeropro4 if possible can you send a video

**Comment by Aeropro4** [comment]
Yeah sure.
https://github.com/saikou-app/saikou/assets/113044496/30f2b54d-c10f-45a3-afb7-a17913b37480

**Comment by SunglassJerry** [comment]
ye, full hd din default doesnt work
known issue since last year

**Comment by brahmkshatriya** [comment]
> Yeah sure. https://github.com/saikou-app/saikou/assets/113044496/30f2b54d-c10f-45a3-afb7-a17913b37480
> 
> Here I have chosen a random anime and the source is 9anime but this issue is in every multi-quality source. But in 720p it remains constant

Can you tell me the exact dimensions of your screen?
I really think its because your device's screen isnt larger than 1920x1080

**Comment by Aeropro4** [comment]
> > Yeah sure. https://github.com/saikou-app/saikou/assets/113044496/30f2b54d-c10f-45a3-afb7-a17913b37480
> > 
> > Here I have chosen a random anime and the source is 9anime but this issue is in every multi-quality source. But in 720p it remains constant
> 
> Can you tell me the exact dimensions of your screen?
> I really think its because your device's screen isnt larger than 1920x1080

Umm yeah you're right, it's 1900x720
![Screenshot_20230707_180545_Chrome.jpg](https://github.com/saikou-app/saikou/assets/113044496/d133aca2-a36e-463c-bd7b-97e54982c337)

**Comment by brahmkshatriya** [comment]
well exoplayer decides which video to play automatically, It's not really in my hand, unless the resolutions are seperated
but Yea I am not gonna do that

I suggest using mp4 links honestly, if you want 1080p

but its best to watch on 720p, as there would be minimal difference

**Comment by Aeropro4** [comment]
> well exoplayer decides which video to play automatically, It's not really in my hand, unless the resolutions are seperated
> but Yea I am not gonna do that
> 
> I suggest using mp4 links honestly, if you want 1080p
> 
> but its best to watch on 720p, as there would be minimal difference

K thanks
