### ISSUE TITLE
add stretch option 

### ISSUE THREAD

**Issue by ZeoGOD4** [saikou-app/saikou#71]
The internal player crops the video rather than streching it resulting in no subs on my screen when i tap on full screen mode

**Comment by brahmkshatriya** [comment]
It is already there, you just decided to not click the fullscreen button again & directly decided to create an issue

**Comment by ZeoGOD4** [comment]
https://drive.google.com/file/d/1s0ILAuAtBpmMse2565wH1UPCu299wGmz/view?usp=drivesdk i guess it doesn't work or im just dumb

**Comment by brahmkshatriya** [comment]
Why is it not showing popup? How old is that version?
