### ISSUE TITLE
Animepahe video Buffers 

### ISSUE THREAD

**Issue by iamdhar** [saikou-app/saikou#710]
### Summary

Animepahe source videos are just buffering and not starting.

### Reproduction Steps

Start any anime from the animepahe source. 

### Expected Result

The video starts as usual without any issues.

### Actual Result

Video not starting

### Device Information

Saikou latest
Android 12
ArmV8

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Cannot be controlled by the app
