### ISSUE TITLE
Auto update latest debug build 

### ISSUE THREAD

**Issue by Ash69123** [saikou-app/saikou#721]
### Summary

Hello it would be great if you all could make it so that debug builds  auto update 

### The Problem

right now to update a debug-build of the app you have to go to discord and then download it every time its updated

### The Ideal Solution

The ideal solution would be to have the app download the latest debug build from github or discord every time the app is opened and show a user prompt like that implemented in saikou stable releases

**Comment by SunglassJerry** [comment]
Auto update latest ***merged***  debug build

**Comment by brahmkshatriya** [comment]
Not planned, why create a beta for a beta lmao
I just dont use beta as lol, well anyway I will from now on
