### ISSUE TITLE
Fast Forward Bug

### ISSUE THREAD

**Issue by Gamingartist18** [saikou-app/saikou#722]
### Summary

Everytime when I double tap the right side of my screen to fast forward the warping black shape animation is left on the screen  

### Reproduction Steps

I have no clue 

### Expected Result

I expected there to be no black shape blocking my view of the screen 

### Actual Result

I have no clue 

### Device Information

Saikou 1.2.3.1
Moto g power 2021
arch64 
Android 11

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
@VipulOG didnt you fix this already?

**Comment by brahmkshatriya** [comment]
Oh I havent updated the app yet, should be fixed in the next version
