### ISSUE TITLE
Change Zoro to Aniwatch

### ISSUE THREAD

**Issue by Catgithub768** [saikou-app/saikou#728]
### Summary

Its just a name change

### The Problem

Its not a problem at all, its just that Zoro rebranded to Aniwatch today

### The Ideal Solution

Since it rebranded, why not changing the name on the app too, something like "Aniwatch (Zoro)"

**Comment by scrazzz** [comment]
https://github.com/saikou-app/saikou/commit/5e1f6f7427619d407f593aa0913e8e1ce391f3b8
