### ISSUE TITLE
Way to read positions not listed on AL

### ISSUE THREAD

**Issue by zakius** [saikou-app/saikou#736]
### Summary

Ability to search the source directly or to use MAL db as a fallback

### The Problem

There are positions on manga reading sources missing from the AL database, currently we can't read them in Saikou at all. 

### The Ideal Solution

Probably ability to choose your primary database per category (anime, manga, novels), fallback to the other DB on demand and if that also fails fallback to search sources directly would probably be optimal from UX perspective

**Comment by brahmkshatriya** [comment]
![image](https://github.com/saikou-app/saikou/assets/69040506/e710046c-8f93-4b4e-872b-100f3e2e9cdb)

**Comment by zakius** [comment]
that's an interesting workaround, thanks!
