### ISSUE TITLE
Manga never loads

### ISSUE THREAD

**Issue by SKYICE01** [saikou-app/saikou#739]
### Summary

Basically the title manga takes 5+min to load or never loads often cuts off and then when I read on pc I see I missed a huge chunk

### Reproduction Steps

Every time I try and read manga Anima works great

### Expected Result

Manga to load 

### Actual Result

Manga doesn't load and always cuts off

### Device Information

Saikou Version: 1.2.4
Device: samsung t2s
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Provide how to produce your error
