### ISSUE TITLE
Quality of life improvement for seeking/skipping

### ISSUE THREAD

**Issue by KhaiCo** [saikou-app/saikou#748]
### Summary

Making the "double tap seek" feature in video player better

### The Problem

To seek/skip in the video player you will need to double tap, and to add the amount of time that is skipped it would need another double tap to make +10 +15 +20 and so on depending on the set amount in settings

### The Ideal Solution

I think it should be like for example YouTube in which you skip with a double tap first and to add the amount of skip, you would need to make just another tap on top the double tap rather than another double tap so for example
Double tap +10
Tripple tap +20
Quadruple tap +30
And so on

### Additional Context

Sorry if it's kinda a small thing that's maybe not worth the effort to implement, Its not a huge deal but is nice to have rather than having to furiously double tap over and over

**Comment by brahmkshatriya** [comment]
Looking at how I have coded it, Android has prebuilt function to detect if a double tap was made
& I am using it, so to fix this It would need a seperate function to do this

**Comment by KhaiCo** [comment]
I see, so is it worth the effort to fix such a small problem? 
Or is it simple enough that it may be fixed?

**Comment by KhaiCo** [comment]
Forgive my ignorance since I don't really know much about programming android apps in general

**Comment by itachi88** [comment]
@brahmkshatriya is anyone working on this currently? Would you need this enhancement to be addressed or is it not needed? Please let me know. I would like to take a look.
