### ISSUE TITLE
Please make external video player support available 

### ISSUE THREAD

**Issue by Trainiscool** [saikou-app/saikou#753]
### Summary

Making external video player support available will be really appealing 

### The Problem

Alot of people myself including are more accustomed to using other more favorable apps like mpv or vlc for their media experience, especially those who have tinkered with their player in the past. Normally in anime watching apps like this one will allow us to watch our content through external video players however we please for the ease of use but having your beautiful app be one of the only one without it is a very big roadblock for some of us

### The Ideal Solution

In the "player settings" section of your settings just add an option for to choose their video player if they so desire like this
![Screenshot_2023-07-17-20-39-24-59_dd604340c1d7941d42aee14dd16e00e8](https://github.com/saikou-app/saikou/assets/96657889/7a619d8b-79bf-4fe0-909e-2b4d626a54a1)

**Comment by SunglassJerry** [comment]
🗿🗿

**Comment by SunglassJerry** [comment]
Go to any episode, and hold press any server
