### ISSUE TITLE
PreviewSeekBar support

### ISSUE THREAD

**Issue by kairusds** [saikou-app/saikou#755]
### Summary

Add a small popup window above the seekbar that shows a preview of the timestamp.

### The Problem

Easier to preview timestamps when seeking.

### The Ideal Solution

[PreviewSeekBar](https://github.com/rubensousa/PreviewSeekBar)'s Example:
![](https://github.com/rubensousa/PreviewSeekBar/raw/master/screenshots/sample.gif "sample")

**Comment by brahmkshatriya** [comment]
Not possible to do efficiently on streaming services, so I am gonna reject this
