### ISSUE TITLE
Secondary display bug

### ISSUE THREAD

**Issue by FrequencyX4** [saikou-app/saikou#757]
### Summary

Video pauses when you're app casting on Galaxy devices and interact with the other display

### Reproduction Steps

- Start screencast
- open saikou and play an anime (this casts fine)
- tap the casting options and then tap app cast
- interact with the phone instead of the secondary display in the pop-up

### Expected Result

The popup keeps playing the anime

### Actual Result

the anime pauses every tap outside of its window

### Device Information

Saikou Version: 1.2.5
Device: samsung dm3q
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

This normally works fine on most other streaming apps

**Comment by Adolar0042** [comment]
Can you share a screen recording of this issue? Normally screencasts are handled by a third party app (Web Video Caster) and app cast and secondary screen seem to be a manufacturer specific feature

**Comment by SunglassJerry** [comment]
Go to `Saikou > Settings > Anime > Player Settings > Behaviour ` and turn off `Pause video when not in focus` see if that helps ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by FrequencyX4** [comment]
@SunglassJerry dang, that fixed it. thanks so much
