### ISSUE TITLE
Fixed watching position

### ISSUE THREAD

**Issue by Artmansky** [saikou-app/saikou#76]
I think It would be nice if animes could be played only in horizontal posion and would only switch between up and down depending on phone's position. I don't think vertical player is useful to anyone. But still keep it up your app is great!

**Comment by Fireboy6** [comment]
> I think It would be nice if animes could be played only in horizontal posion and would only switch between up and down depending on phone's position. I don't think vertical player is useful to anyone. But still keep it up your app is great!

That's Nice suggestion, i found it weird too.

**Comment by brahmkshatriya** [comment]
Nope it's gonna stay.
