### ISSUE TITLE
QoL improvement for differentiating between new animes vs animes already on list

### ISSUE THREAD

**Issue by ElectricTailMonkey** [saikou-app/saikou#767]
### Summary

To make adding animes to the planning list easier.

### The Problem

Currently, when you long press on an anime you want to add to the list, you get a popup that defaults to adding the anime to the planning list. This is perfectly fine. 
But the problem is when you try to add an anime that is already on one of your lists it shows the same prompt and does not let you know that the anime is already on your list. This leads to adding the same anime multiple times to the list in case you don't remember the name. This causes the newer animes that you discover to get pushed down the Planning list and ones that you already know about move back up, which in most cases you don't want to happen. Most of the time you would want to keep the newer current animes to the top of the planning list instead of them getting pushed down unintentionally. This also leads to adding the same anime multiple times to the list without knowing if you already added the anime or not to the list and then it moves back up multiple times to the top of the list. 

### The Ideal Solution

Adding new anime to the list: No change needed 
Adding anime already on the list: A popup or a message of some sort to let the user know that the anime is already on the list and doesn't need to be added again.

### The Current Solution

Currently, when a new anime or old anime is added to the list it moves to the top of the planning list regardless of if its a new anime or an anime that is already on the list, there is no differentiation. 

### Additional Context

Thank you for your time and the awesome app. If it can't be implemented its okay. This just makes it so you know that you have already added an anime on the list so you don't waste time repeatedly adding the same anime over and over.

**Comment by SunglassJerry** [comment]
Yk that we have a "List Only" and 'Not Listed" filter right?

**Comment by SunglassJerry** [comment]
Under the searchbar

**Comment by ElectricTailMonkey** [comment]
Yes sorry for not clarifying. What i mean is when you are in the anime tab and you see an anime u like and you long press on it, it will show a popup to add the anime to the list that is what i was talking about
