### ISSUE TITLE
Episode title [AnimePahe]

### ISSUE THREAD

**Issue by SunglassJerry** [saikou-app/saikou#769]
### Summary

Titles for Animepahe episodes

### The Problem

Animepahe doesn't host episode titles. So it should follow kitsu's. Afaik source details are usually prioritized over kitsu's details. But Incase of Animepahe, even tho the source doesn't give episode titles, it still doesn't show kitsu's details.

### The Ideal Solution

Kitsu provides titles for most of the animes. So letting kitsu overlap Animepahe for episode titles would be great.

### The Current Solution

~

### Additional Context

Idk if it's supposed to be a bug or feature request. I love cyan, so I chose enhancement tag

**Comment by DaniD3v** [comment]
https://github.com/saikou-app/saikou/pull/793

this should fix it
