### ISSUE TITLE
Download at once

### ISSUE THREAD

**Issue by KirigayaCedrick** [saikou-app/saikou#775]
### Summary

Download anime at once rather clicking them and download one by one

### The Problem

You need to play first the video before you can even download

### The Ideal Solution

Theres a download button just like aniyomi or bilibili, if any, and click  download then you can select them all at once plz add up also if possible that can make desktop version of it 🙏

**Comment by Adolar0042** [comment]
You don't need to play the video to download it; you can directly download by either long-pressing on the stream you want to download or by setting one of the third party download managers as your downloading service in the settings of the app and then pressing on the download icon on streams.

_Idk about bulk downloads, just wanted to point out that you don't have to play each episode to download it_

**Comment by brahmkshatriya** [comment]
probably talking about #15
