### ISSUE TITLE
Subbed-Dubbed toggle [Animepahe | Kaido]

### ISSUE THREAD

**Issue by SunglassJerry** [saikou-app/saikou#776]
### Summary

Both Zoro and Animepahe has dubs but we need to select them from servers. Would be cool you gave a SUB-DUB toggle got these too.

### The Problem

~

### The Ideal Solution

~

### The Current Solution

~

### Additional Context

Btw, I think it would be better if a loading animation appears in the episode list after we toggle from sub to dub or dub to sub. Many toggle dub and immediately presses on a episode. So he ends up entering a server from the subbed episodes.

**Comment by brahmkshatriya** [comment]
no pointing in hidin

**Comment by SunglassJerry** [comment]
Please explain what did you mean by that poetry
