### ISSUE TITLE
Anime title cut in player when video info is turned off

### ISSUE THREAD

**Issue by Fireboy6** [saikou-app/saikou#78]
Selected zoro as a Source there's no subtitle
Anime Title and Episode's is fuck up

![Screenshot_2022-03-30-06-40-16-57](https://user-images.githubusercontent.com/75554729/160719618-c5e31ecf-2288-4916-9a83-610e8cc6abea.png)

**Comment by brahmkshatriya** [comment]
Turn on video info to fix for now

**Comment by Fireboy6** [comment]
> Turn on video info to fix for now

Their size have changed i hope it gets back to normal! 
Nevertheless i was surprised of the big changes of the app, Thank You 👍🏻
