### ISSUE TITLE
Captions for dubbed anime 

### ISSUE THREAD

**Issue by Lalosalamanca-7** [saikou-app/saikou#784]
### Summary

Make it so that we can have captions for dubbed anime 

### The Problem

When I am watching dubbed anime it kinda hard to understand without captions 

### The Ideal Solution

Add a captions button on both sub and dub anime 

### The Current Solution

Just add captions to dubbed anime 

### Additional Context

Please add captions to dubbed anime

**Comment by brahmkshatriya** [comment]
Provide a site, that provide subs in dub
