### ISSUE TITLE
AnimePahe issue

### ISSUE THREAD

**Issue by SunglassJerry** [saikou-app/saikou#785]
### Summary

On behalf of every sufferer, Please fix Animepahe not working temporarily quite often. Will work fine, but suddenly stops working for like a few hours. Many people are facing this. apparently reselecting the title from wrong title loads the episodes

### Reproduction Steps

~

### Expected Result

Episode loads fine 

### Actual Result

Doesn't load

### Device Information

~

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information
You can fix that by triggering a refresh the moment it gives you an error. Only happens twice. 
[Error_1.txt](https://github.com/saikou-app/saikou/files/12369105/Error_1.txt)

**Comment by brahmkshatriya** [comment]
Not fixable, its a server side error
