### ISSUE TITLE
Ability to delete anime/manga from lists

### ISSUE THREAD

**Issue by scrazzz** [saikou-app/saikou#789]
### Summary

A feature to delete anime/manga from the available lists in the app.

### The Problem

You are not able to delete the anime/manga from the watching, reading, completed, dropped, etc lists.

### The Ideal Solution

Add a button in the List Editor to Delete the item from the list.

### The Current Solution

Current solution involves going to anilist.co and deleting the anime/manga.

### Additional Context

n/a

**Comment by Sickhead01** [comment]
You can already do that. Go on the anime/manga, press the bubble that says "Watching", "Planning", "Complete" or whatever and you can delete it from there

**Comment by scrazzz** [comment]
> You can already do that. Go on the anime/manga, press the bubble that says "Watching", "Planning", "Completed" or whatever and you can delete it from there

Sorry, but I don't see anything that reads "Delete" here.
![dumbass](https://github.com/saikou-app/saikou/assets/70033559/c03bbb65-3d2d-418c-9cf7-2e8a6bef90d6)

**Comment by Sickhead01** [comment]
![Screenshot_20230820-082248](https://github.com/saikou-app/saikou/assets/70452344/ba32c3c5-2f6f-4e31-a30c-66364ca534d3)


This is what i'm seeing on mine, and i've remove multiple shows from my anilist in the app over the past few months

**Comment by scrazzz** [comment]
I see, thanks for pointing it out. It only shows up when we're on the "Info" page of the anime.

This seems like an odd behaviour. It *should* show the same List Editor nonetheless.

If I'd know this earlier then I'd open a bug report addressing this instead.

**Comment by scrazzz** [comment]
After a chat with @brahmkshatriya on Discord, it is clear that in order to show the full list editor additional data should be requested (which is only done in the "Info" page) to Delete the item from the list. Hence, without an extensive refactor to the underlying code this cannot be changed or fixed.
