### ISSUE TITLE
Komori Anime/Manga separation

### ISSUE THREAD

**Issue by 6r0ck3n** [saikou-app/saikou#79]
This app Called Komori has better Theme, UI, and Font Style. decent Navigation too.

Search and Setting move to Navigation of the app

I'd still love OLD UI

@![IMG_20220330_114351](https://user-images.githubusercontent.com/101026460/160748997-c169984b-c1f5-47f2-8fd5-0787dec3420b.jpg)

**Comment by Light7654** [comment]
But I like saikou UI better than kamori

**Comment by KillerDogeEmpire** [comment]
Can I have the link for komori

**Comment by 6r0ck3n** [comment]
@Light7654  Use it yourself you'll see the difference. Well They're different in the first place, but Komori was nice to navigate and Well Arranged. Komori's separating Anime/Manga is amazing they didn't mix it to Navigation button of the app.

@KillerDogeEmpire unfortunately it's just Tracking List you can find it on Playstore

**Comment by KillerDogeEmpire** [comment]
Ok thanks
