### ISSUE TITLE
Allanime server soucre not working

### ISSUE THREAD

**Issue by Kuuhakuxx** [saikou-app/saikou#791]
### Summary

Allanime other server source not appearing or working

### Reproduction Steps

![Screenshot_20230821_014803_Saikou ](https://github.com/saikou-app/saikou/assets/122075694/3dbafb6a-be43-4d8e-ba2d-78751fd95f9d)

### Expected Result

Expecting that all the soucre would pop out after the least beta update but it still bugging. Picture below of all the source that was supposed to be inside (Pictures taken from Allanime website)

### Actual Result

![Screenshot_20230821_015215](https://github.com/saikou-app/saikou/assets/122075694/fdf283b0-7eb6-4c1e-afc1-9e65c005da26)

### Device Information

Saikou version: least beta 
Device: s10 plus 

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by DaniD3v** [comment]
https://github.com/saikou-app/saikou/pull/796

my PR fixes it.
