### ISSUE TITLE
Anilist login not working 

### ISSUE THREAD

**Issue by CdtShin42** [saikou-app/saikou#807]
### Summary

I'm trying to login to anilist but not working

### The Problem

Anilist login not working 

### The Ideal Solution

Please try to resolve the problem

**Comment by Adolar0042** [comment]
Please provide further details:
- what version of the app do you use?
- which browser do you use?

**Comment by scrazzz** [comment]
You should have opened a bug report and not a feature request. Open a new **Bug Report** issue.
