### ISSUE TITLE
( Feature ) Watching Movie Function 

### ISSUE THREAD

**Issue by OshekharO** [saikou-app/saikou#81]
Hii if possible add 3 to 4 movie sources which can be used for long time without requiring regular maintenance.

2embed , apimdb & sflix is more than enough.

Scrapper: [Movie / Series / Anime Scrapper ](https://oshekharo.github.io/Link-Crawler/)

**Comment by Jasonsmith236** [comment]
Wish that were true the only app I know that does that is only available for ios it's called ketsu a modular app
