### ISSUE TITLE
Manga inverted colors 

### ISSUE THREAD

**Issue by Btpatil** [saikou-app/saikou#811]
### Summary

I am facing issue where black and white manga are showing inverted colors instead normal black and white 

### Reproduction Steps

I just normally open any manga where instead of showing normal colour it shows inverted colors in case black and white manga. The colored mangas are working fine showing colour properly but the issue is with non colored black and white mangas

### Expected Result

Expected is the manga shows the normal colours that's all

### Actual Result

Here's the sample of what I am getting 
![Screenshot_2023-09-09-18-50-07-415_ani saikou](https://github.com/saikou-app/saikou/assets/89716684/370d9433-af68-46b0-9be4-0944bcf89aa8)

### Device Information

Saikou Version: 1.2.5
Device: POCO citrus
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Adolar0042** [comment]
Looks like that might be the result of a forced dark mode? Please check if you have something like that enabled for Saikou.

**Comment by Btpatil** [comment]
Yeah that was the case. Thank you very much and sorry for any inconveniences caused. Again thanks for the help. Btw great app love it.
