### ISSUE TITLE
Source problem 

### ISSUE THREAD

**Issue by y669jjf** [saikou-app/saikou#816]
### Summary

Many sources isn't working 

### Reproduction Steps

Open app / choose anime / choose the source / 

### Expected Result

Choose server and watch

### Actual Result

![Screenshot_20230912-224656](https://github.com/saikou-app/saikou/assets/109913181/6044004c-3ad2-4163-bb6b-33eb7f24e8f5)

### Device Information

Last version
Realms
RMX2061
Android 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Try to release more updates and make the video player in another app because it's awesome

**Comment by y669jjf** [comment]
> ### Summary
> Many sources isn't working
> 
> ### Reproduction Steps
> Open app / choose anime / choose the source /
> 
> ### Expected Result
> Choose server and watch
> 
> ### Actual Result
> ![Screenshot_20230912-224656](https://user-images.githubusercontent.com/109913181/267443960-6044004c-3ad2-4163-bb6b-33eb7f24e8f5.png)
> 
> ### Device Information
> Last version Realms RMX2061 Android 13
> 
> ### Checklist
> * [x]  I have searched the open AND closed issues for any duplicates.
> 
> ### Additional Information
> Try to release more updates and make the video player in another app because it's awesome

-try to add aniwave.bz because it's working smoothly
At the end it's an alternative for aniwatch

**Comment by Adolar0042** [comment]
Your app seems to be outdated, please make sure to use the latest pre-release.

> try to add aniwave.bz because it's working smoothly

We already have the original site (`Aniwatch.to`) working in the app.
