### ISSUE TITLE
[providers] Some sites

### ISSUE THREAD

**Issue by OshekharO** [saikou-app/saikou#82]
Here are some sites i managed to find. Feel free to cross off sites that are not feasible to implement.

### Anime ( hentai ):

- [ ] https://haho.moe
- [ ] https://hentaifreak.org
- [ ] https://hentaibar.com
- [ ] https://hanime.tv

### Manga ( doujin ):

- [ ] https://manytoon.com
- [ ] https://toonily.me
- [ ] https://animeidhentai.com
- [ ] https://9hentai.to
- [ ] https://comics.8muses.com
- [ ] https://18comic.vip
- [ ] https://www.cartoon18.com

### Manga ( Regular ):

- [ ] https://mangaowls.com
- [ ] https://manhuafast.com
- [ ] https://readm.org
- [ ] https://ninemanga.com
- [ ] https://mangatx.com

### Anime ( Regular ):

- [ ] https://animixplay.to
- [ ] https://wcostream.cc
- [ ] https://simplyaweeb.to/anime/
- [ ] https://fsapi.xyz
- [ ] https://genoanime.com

### Light Novel ( Regular ):

- [ ] https://novelsrealm.com
- [ ] https://www.wnmtl.org
- [ ] https://www.mtlnovel.com
- [ ] https://comrademao.com
- [ ] https://www.readwn.com

### Movies & Series ( Regular ):

- [ ] https://www.2embed.ru
- [ ] https://v2.apimdb.net
- [ ] https://fsapi.xyz
- [ ] https://www.superembed.stream
- [ ] https://autoembed.xyz
- [ ] https://streamo.cc
- [ ] https://databasegdriveplayer.co
- [ ] https://sflix.to

_Note_: **Almost all of them are without cloudflare protection.**

**Comment by brahmkshatriya** [comment]
Thankyou
