### ISSUE TITLE
Date clear/remove not working for MAL

### ISSUE THREAD

**Issue by KhaiCo** [saikou-app/saikou#824]
### Summary

MAL not updating when no date is entered (Anilist works fine)

### Reproduction Steps

Basically I tried to set an anime that I completed I the past and removed the date from the list modifier since I don't remember anyways (the feature that was recently added in beta  #812). But weirdly I noticed that even though Anilist added the title correctly with no dates included MAL didn't respond to the list change and basically act like no change was made (stays unlisted) and when I tried to use a decoy date (today) MAL works correctly and listed the title with the decoy date. I've tried this multiple times and the result are consistent.
Pictures:
![Screenshot_2023-09-19-21-23-37-312_ani saikou beta](https://github.com/saikou-app/saikou/assets/130490107/f28414b9-4da0-417e-9afc-7e35f8106ccf)
^Set Without date
![Screenshot_2023-09-19-21-23-59-745_net myanimelist app](https://github.com/saikou-app/saikou/assets/130490107/e868fe7f-69aa-49e5-abb9-f07d4a348045)
^Not listed
![Screenshot_2023-09-19-21-24-10-448_ani saikou beta](https://github.com/saikou-app/saikou/assets/130490107/8cebffe6-3978-4382-9057-dfe32f4982c3)
^With decoy date 
![Screenshot_2023-09-19-21-24-25-612_net myanimelist app](https://github.com/saikou-app/saikou/assets/130490107/e3a9c235-6543-4968-9259-37d970fec4f4)
^Correctly listed

### Expected Result

Mal correctly listing titles without date

### Actual Result

Not listing anything

### Device Information

Saikou Version: 1.2.5.b56c7fd
Device: POCO lmi
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Similar apps like tachiyomi works when setting no date so probably not from the MAL API

**Comment by Aiz0** [comment]
Sorry I don't have a MAL account so this issue went under my radar.
The date should probably be made into an empty string when querying MAL, I don't know for sure though.
The functions in FuzzyDate don't seem to be made under the assumption that the date is fuzzy which is causing some issues.
