### ISSUE TITLE
Add clipping/cutting.

### ISSUE THREAD

**Issue by tangymc** [saikou-app/saikou#825]
### Summary

Adding a way to clip an anime and download the part that has been clipped only.

### The Problem

Some people wants to download only part of the anime for an edit or something but it becomes hard to do so since you'll need to download the whole anime and then edit the part that you want from it.

### The Ideal Solution

Adding that feature would fix that issue.

**Comment by scrazzz** [comment]
No. The app is only meant to watch anime or read manga.
