### ISSUE TITLE
Continue Watching Option

### ISSUE THREAD

**Issue by Zeroo097** [saikou-app/saikou#83]
Can U Add an option on the homepage to continue watching the episode which you left.Right Now we have to scroll to the anime which we were watching last time to continue.

**Comment by brahmkshatriya** [comment]
Are you logged in with anilst?

**Comment by Zeroo097** [comment]
Yes.Let me add an attachment as an example

![Screenshot_20220331-142235.jpg](https://user-images.githubusercontent.com/91909890/161016670-cc43f82e-cb3b-4c7d-ac84-37ddc7868009.jpg)

**Comment by brahmkshatriya** [comment]
🤨
![Screenshot_20220331-142453.png](https://user-images.githubusercontent.com/69040506/161017149-ccfe8d06-8a9a-4639-a24e-5bc1e087abef.png)

**Comment by Zeroo097** [comment]
Yeah it shows continue watching if i add it.But it would be great if we can get an option just resume by tapping on the episode instead of going to the anime to resume it.

**Comment by brahmkshatriya** [comment]
That's not possible in saikou

**Comment by Zeroo097** [comment]
Ohhh uhh okay
