### ISSUE TITLE
Tor/DNS support 

### ISSUE THREAD

**Issue by Helpful-Neko** [saikou-app/saikou#831]
### Summary

To be able to run the application when Tor is enabled. 

### The Problem

I can't get the application to run when Tor is enabled. I receive a Error (Error loading Anilist user data) when Tor is enabled. 

Pretty sure it might be caused by a cloud flare issue. 

### The Ideal Solution

The ability to run Tor while using the Saikou App without the app breaking. 

I'd really like to see features for getting around ISP blocking [DNS support] and Tor support. I'd prefer my ISP not being able to see my love of anime or anything I do for that matter 🤣

I think the solution would be the ability to verify my connection with cloud flare somehow I think. I'm not certain 

### The Current Solution

I have to disable Tor for the application to work. 

### Additional Context

![Screenshot_20230928-021330-820](https://github.com/saikou-app/saikou/assets/126541816/a54af660-d52c-4921-a6fa-9b167145403d)

Screenshot of connection issue.

**Comment by scrazzz** [comment]
This is not possible. Consider using a VPN instead.

**Comment by Helpful-Neko** [comment]
> This is not possible. Consider using a VPN instead.

No worries I just thought I'd ask.
