### ISSUE TITLE
Auto Quality

### ISSUE THREAD

**Issue by Zeroo097** [saikou-app/saikou#85]
When I Use 9anime vidstreaming multi quality server it used the highest quality possible even on slower networks i tried tapping on auto repeatedly but nothing happened.Can u tell me how can I solve that, it changes quality depending on the network.

**Comment by brahmkshatriya** [comment]
Yeah, due to having a quality selector in settings, inbuilt auto quality of the video player doesn't work

But i removed it because I was not seeing any auto quality selection based on network, I will try it out again and if it does work i'll add a setting to enable auto quality
