### ISSUE TITLE
spanish support

### ISSUE THREAD

**Issue by Emiilychiquita** [saikou-app/saikou#87]
I need this app in Spanish please🥺😥🙏

**Comment by brahmkshatriya** [comment]
Checkout the Spanish fork of the app!
https://github.com/Diegopyl1209/saikouSP

**Comment by Emiilychiquita** [comment]
it's only in english :C

**Comment by Diegopyl1209** [comment]
La aplicación está en inglés pero tiene la opción de ver los capítulos en Monoschinos y animefenix que son páginas que tienen los subtítulos en español

**Comment by Diegopyl1209** [comment]
> it's only in english :C
![Screenshot_20220401_165714](https://user-images.githubusercontent.com/80992641/161333087-c191a68e-dc5b-46dc-a0b4-3aca6e4cc1a7.jpg)

**Comment by Diegopyl1209** [comment]
> it's only in english :C

![Screenshot_20220401_170057_ani saikou](https://user-images.githubusercontent.com/80992641/161333372-28e6e472-df44-4823-bfd5-b657dfde5055.jpg)

**Comment by Kratos14** [comment]
> > it's only in english :C
> 
> La aplicación está en inglés pero tiene la opción de ver los capítulos en Monoschinos y animefenix que son páginas que tienen los subtítulos en español

I love the app, good job. Can you add more spanish sources like jkanime,animeflv,tioanime. That would be great thanks.
