### ISSUE TITLE
Trending Now with more options

### ISSUE THREAD

**Issue by MrConqueror** [saikou-app/saikou#90]
![IMG_20220402_075602](https://user-images.githubusercontent.com/102837820/161360993-947b1217-0b85-4102-af78-4131bacab7b1.jpg) 
Sir, I like your app looking forward to future updates
But Can you make the trending now like this? Like old saikou?
And make Add to list like this like not large. Also to shrink saikou same like other app example komori so title like this one is not cut.

**Comment by brahmkshatriya** [comment]
I like the idea of trending that's a cool option, but I will not change add to list option
Thanks for the suggestions

**Comment by MrConqueror** [comment]
> I like the idea of trending that's a cool option, but I will not change add to list option Thanks for the suggestions

Thanyou for appreciating, does it mean you will bring back the old Saikou Trending now? And make it even more better? Anyway i discovered something i set my dpi to 420👌it was set to 360 maybe this is the default, here's what Saikou look like
![IMG_20220403_082343](https://user-images.githubusercontent.com/102837820/161406492-a4149660-05eb-4849-96c3-c35fb2abbca5.jpg) Anime Title cut no more except for those long ass Title ofcourse. But when i closed the app went to YouTube its looks surprised me and the other apps it looks funny as hell. So i set back to default (360) in my opinion Anime Titles Font weight and Scale are very Large in Saikou.
