### ISSUE TITLE
Fix Zoro please

### ISSUE THREAD

**Issue by TitansSami** [saikou-app/saikou#92]
Please fix Zoro vidstreaming server in the next update. Thank you.

**Comment by brahmkshatriya** [comment]
sir your old issue is still open, no point in making a new one, this issue is a duplicate of #31

**Comment by TitansSami** [comment]
Please sir do something about it. You have fixed gogo server. It would be
amazing if you kindly could take a look at the Zoro vidstreaming server
situation. It just randomly gives a source exception error. Please, I love
this app just make this issue fixed.
