### ISSUE TITLE
Manga List Viewing 

### ISSUE THREAD

**Issue by SmokinRay01** [saikou-app/saikou#93]
So idk if this is a bug or not...
Actually I'm having problem in opening my "Manga List". It gives an error notice.
I can see the "Continue Reading" section in the home page (with the mangas I'm reading and it is updating too) but I am not able to access the Manga list.
The Anime List works great.

![Screenshot_20220403-133250__01](https://user-images.githubusercontent.com/86943042/161418674-99caee41-0eab-4780-afc4-7b1e318832cd.jpg)
![IMG_20220403_135559_194](https://user-images.githubusercontent.com/86943042/161419049-a35f1cbb-7ca5-40fa-b9bf-1ca11054a448.jpg)

Thank you ❤️

**Comment by brahmkshatriya** [comment]
huh, can you send me your anilist username? I'll try checking what's causing it,
It seems like a manga you have in your list is sending some weird data

**Comment by SmokinRay01** [comment]
> huh, can you send me your anilist username? I'll try checking what's causing it, It seems like a manga you have in your list is sending some weird data

I'll link my profile: https://anilist.co/user/SmokinRay/

(regarding the list names having emoji's in it... I did try removing it and trying but it didn't work) 
once again thank you ❤

**Comment by SmokinRay01** [comment]
Oh and I think that I had seen this manga's name in the error notice once: https://anilist.co/manga/139569/Liang-Ge-Baba-Yi-Ge-Wa/
but the notice keeps changing so I'm not sure abt it...

**Comment by brahmkshatriya** [comment]
Fixed, turns out your list is way too big, So had to remove the 2mb limit

**Comment by SmokinRay01** [comment]
> Fixed, turns out your list is way too big, So had to remove the 2mb limit

ohhh 😅. 
Thank You ❤
