### ISSUE TITLE
An anime streaming server that has separate subtitles for anime 

### ISSUE THREAD

**Issue by TitansSami** [saikou-app/saikou#96]
Hey can you tell me if there's any other anime server besides Zoro who have separate subtitles for anime. 9 anime and gogo anime have subtitles embedded into the anime which is annoying for full screen devices as it cuts off the subtitles. Please if you know of any other server consider adding it into the next update. Wishing For your immense progress.

**Comment by brahmkshatriya** [comment]
Show me which does, I can try to add it
